
/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "پیشفرض سیستم",
  "PROJECT_BUSY": "عملیات پروژه در حال انجام است",
  "DUPLICATING": "در حال تکرار {0}",
  "MOVING": "در حال انتقال {0}",
  "COPYING": "در حال کپی کردن {0}",
  "DELETING": "در حال حذف {0}",
  "RENAMING": "تغییر نام",
  "GENERIC_ERROR": "(خطا {0})",
  "NOT_FOUND_ERR": "پرونده پیدا نشد.",
  "NOT_READABLE_ERR": "پرونده قابل خواندن نیست.",
  "EXCEEDS_MAX_FILE_SIZE": "فایل های بزرگتر از {0} MB قابل ویرایش در {APP_NAME} نیست.",
  "NO_MODIFICATION_ALLOWED_ERR": "دایرکتوری هدف قابل ویرایش نیست.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "دسترسی های تعریف شده برای شما اجازه تغییرات را نمی دهند.",
  "CONTENTS_MODIFIED_ERR": "فایل خارج از محیط {APP_NAME} تغییر یافته است.",
  "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} فعلا تنها از پرونده ها با ساختار یونیکدی UTF-8 پشتیبانی می کند.",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} نتوانست محتویات فایل را رمزگذاری کند.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} نتوانست محتویات فایل را رمزگشایی کند.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} در حال حاضر از فایل‌های متنی کدگذاری شده UTF-16 پشتیبانی نمی‌کند.",
  "FILE_EXISTS_ERR": "پرونده یا پوشه مد نظر موجود می باشد.",
  "FILE": "پرونده",
  "FILE_TITLE": "فایل",
  "DIRECTORY": "پوشه",
  "DIRECTORY_TITLE": "پوشه",
  "DIRECTORY_NAMES_LEDE": "نام های پوشه",
  "FILENAMES_LEDE": "نام های پرونده",
  "FILENAME": "نام پرونده",
  "DIRECTORY_NAME": "نام پوشه",
  "ERROR_LOADING_PROJECT": "خطا در بارگذاری پروژه",
  "OPEN_DIALOG_ERROR": "خطا در باز کردن پرونده خوان. (خطا {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "خطا بهنگام بارگذاری پوشه <span class='dialog-filename'>{0}</span>. (خطا {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "بروز خطا در خواندن اطلاعات پوشه <span class='dialog-filename'>{0}</span>. (خطا {1})",
  "ERROR_OPENING_FILE_TITLE": "خطا در باز کردن پرونده",
  "ERROR_OPENING_FILE": "خطا بهنگام تلاش برای باز کردن پرونده <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "خطا بهنگام بارگذاری پرونده های زیر:",
  "ERROR_RELOADING_FILE_TITLE": "خطا در بارگذاری تغییرات از حافظه",
  "ERROR_RELOADING_FILE": "بروز خطا بهنگام تلاش برای بارگذاری پرونده <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "خطا در ذخیره سازی پرونده",
  "ERROR_SAVING_FILE": "بروز خطا بهنگام تلاش جهت ذخیره پرونده <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "خطا در تغییر نام پرونده {0}",
  "ERROR_RENAMING_FILE": "بروز خطا بهنگام تلاش برای تغییر نام پرونده {2} <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "فایل یا دایرکتوری بخشی از پروژه باز شده فعلی نیست. متاسفانه در این مرحله فقط فایل های پروژه را می توان تغییر نام داد.",
  "ERROR_MOVING_FILE_TITLE": "خطا در انتقال {0}",
  "ERROR_MOVING_FILE": "هنگام تلاش برای جابجایی {2} <span class='dialog-filename'>{0}</span> خطایی روی داد. {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "نمی توان فایل/پوشه را جابجا کرد، زیرا آنها بخشی از پروژه فعلی نیستند.",
  "ERROR_DELETING_FILE_TITLE": "خطا در حذف پرونده {0}",
  "ERROR_DELETING_FILE": "بروز خطا بهنگام تلاش برای تغییر نام پرونده {2} <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "غیر مجاز {0}",
  "CANNOT_PASTE_TITLE": "نمی‌توان {0} را جای‌گذاری کرد",
  "CANNOT_DOWNLOAD_TITLE": "نمی توان {0} را دانلود کرد",
  "ERR_TYPE_DOWNLOAD_FAILED": "هنگام دانلود <span class='dialog-filename'>{0}</span> خطایی روی داد",
  "ERR_TYPE_PASTE_FAILED": "هنگام چسباندن <span class='dialog-filename'>{0}</span> به <span class='dialog-filename'>{1}</span> خطایی روی داد",
  "CANNOT_DUPLICATE_TITLE": "نمی توان کپی کرد",
  "ERR_TYPE_DUPLICATE_FAILED": "هنگام کپی کردن <span class='dialog-filename'>{0}</span> خطایی روی داد",
  "INVALID_FILENAME_MESSAGE": "{0} نمیتوانید از عبارات مورد استفاده نرم افزار, نقطه ها پایانی (.) یا کاراکترهای شامل موارد زیر استفاده کنید: <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "پوشه یا پرونده ی با نام  <span class='dialog-filename'>{0}</span> هم اکنون موجود است.",
  "ERROR_CREATING_FILE_TITLE": "خطا در ایجاد {0}",
  "ERROR_CREATING_FILE": "خطا بهنگام ایجاد {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "نمی توان یک پوشه را همزمان به عنوان سایر فایل ها باز شده در نظر گرفت",
  "ERROR_KEYMAP_TITLE": "خطا در خواندن نقشه ی کلید مورد استفاده",
  "ERROR_KEYMAP_CORRUPT": "فایل نقشه کلید شما در  JSON نامعتبر میباشد. زمانی فایل باز خواهد شده که شما آن را به شکل صحیح بنویسید.",
  "ERROR_LOADING_KEYMAP": "فایل نقشه کلید شما هست یک فایل متنی غیر معتبر با کدگذاری UTF-8 .و نمی توان بارگذاری شود",
  "ERROR_RESTRICTED_COMMANDS": "شما نمی توان با این دستور کلیدهای میانبر را اختصاص دهید: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "شما این میانبرها را نمیتوانید اختصاص دهید: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "شما با این دستور کلید میانبر چندگانه ایجاد کرده اید: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "شما مقادیر متعددی برای این میانبر دارید: {0}",
  "ERROR_INVALID_SHORTCUTS": "این میانبر نامعتبر میباشد: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "شما در حال اختصاص کلید میانبر برای دستوراتی که وجود ندارند هستید: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "خطا در خواندن تنظیمات",
  "ERROR_PREFS_CORRUPT": "پرونده تنظیمات شما از نوع پرونده JSON معتبر نیست. از آنجایی که پرونده قابل دسترسی و خواندن است، میتواند بصورت دستی توسط شما تصحیح گردد. البته جهت اعمال تغییرات می بایست {APP_NAME} بارگذاری مجدد گردد.",
  "ERROR_PROJ_PREFS_CORRUPT": "فایل تنظیمات برگزیده پروژه شما JSON معتبر نیست. فایل باز می شود تا بتوانید فرمت را اصلاح کنید. برای اعمال تغییرات باید پروژه را دوباره بارگیری کنید.",
  "ERROR_IN_BROWSER_TITLE": " متاسفم! {APP_NAME}اکنون در این مرورگر اجرا نمیشود .",
  "ERROR_IN_BROWSER": "{APP_NAME} در اچ تی ام ال ساخته شده است, اما در حال حاضر آن به عنوان یک نرم افزار در دسکتاپ اجرا میشود بنابراین شما میتوانید جهت ویرایش فایل ها از آن استفاده کنید. لطفا از اپلیکیشن shell در <b>github.com/adobe/brackets-shell</b> جهت اجرای مخازن  {APP_NAME} استفاده کنید.",
  "ERROR_MAX_FILES_TITLE": "خطا در فهرست بندی پرونده ها",
  "ERROR_MAX_FILES": "این پروژه شامل بیش از 30000 فایل است. امکانات که در فایل های چندگانه کار می کنند ممکن است غیرفعال و یا به عنوان پروژه خالی در نظر گرفته شوند. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>اطلاعات بیشتر در مورد کار با پروژه های بزرگ</a>.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "خطا در اجرای مرورگر",
  "ERROR_CANT_FIND_CHROME": "مرورگر گوگل کروم پیدا نشد. لطفا از نصب بودن آن اطمینان حاصل کنید.",
  "ERROR_LAUNCHING_BROWSER": "بروز خطا بهنگام اجرای مرورگر. (error {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "خطا در پیش نمایش زنده",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "در حال اتصال به مرورگر",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "به هر صورت بهنگام اتصال به حالت پیش نمایش, مرورگر کروم احتیاج دارد به فعال بودن اشکال زدای راه دور (خطایابی راه دور).<br /><br />آیا تمایل دارید به اجرای دوباره کروم و فعال سازی اشکال زدای راه دور(اشکال زدایی از راه دور)?",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "ناتوان در بارگذاری صفحه توسعه زنده.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "جهت اجرای پیش نمایش زنده بصورت پرونده در سمت سرور(server-side), می بایست یک URL پایه برای پروژه تعریف نمایید.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "خطا در اجرای سرویس دهنده HTTP برای توسعه زنده پرونده ها. لطفا دوباره تلاش کنید",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "برای اطلاعات بیشتر, ببینید <a href='{0}' title='{0}'>عیب یابی خطاهای اتصال پیش نمایش زنده</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "پیش نمایش زنده",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "پیش نمایش زنده: درحال اتصال…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "پیش نمایش زنده: درحال مقداردهی اولیه…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "قطع اتصال از پیش نمایش زنده",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "پیش نمایش زنده",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "File To Live Preview را انتخاب کنید",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "بارگذاری مجدد صفحه",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "موارد برجسته پیش‌نمایش زنده را تغییر دهید",
  "LIVE_DEV_CLICK_POPOUT": "پیش نمایش زنده پنجره بازشو به پنجره جدید",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "پین کردن صفحه پیش‌نمایش لغو پین",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "پیش نمایش زنده (به دلیل خطا در سینتکس، بروزرسانی نشده است)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "پیش نمایش زنده لغو شد زیرا از برخی از ابزارهای توسعه مختص مرورگرتان استفاده کرده اید.",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "پیش نمایش زنده لغو شد زیرا پنجره یا زبانه مربوط به صفحه در مرورگر بسته شده.",
  "LIVE_DEV_NAVIGATED_AWAY": "پیش نمایش زنده لغو شد زیرا پنجره یا زبانه موجود در مرورگر آدرس دیگری را پیمایش کرده است.",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "پیش نمایش زنده به دلیل نامشخصی لغو شد ({0})",
  "SAVE_CLOSE_TITLE": "ذخیره تغییرات",
  "SAVE_CLOSE_MESSAGE": "آیا مایلید تغییرات داده شده در سند ذخیره گردند <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "آیا مایلید تغییرات داده شده در پرونده های زیر، ذخیره گردند?    ",
  "EXT_MODIFIED_TITLE": "تغییرات خارجی",
  "CONFIRM_DELETE_TITLE": "تایید حذف",
  "CONFIRM_FILE_DELETE": "آیا مطمئن هستید که می خواهید فایل <span class='dialog-filename'>{0}</span> را حذف کنید؟",
  "CONFIRM_FOLDER_DELETE": "آیا مطمئنید می خواهید این پوشه حذف گردد <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "پرونده حذف گردید",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> خارج از براکتس ویرایش شده.<br /><br />آیا می خواهید پرونده را ذخیره و تغییراتی را که داده اید دوباره بر روی پرونده ویرایش شده اعمال نمایید؟",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> تغییراتی بر روی دیسک انجام شده, ولی تغییرات بر روی براکتس ذخیره نگردیده.<br /><br />کدام نسخه را می خواهید نگه دارید?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> برخی مقادیر از دیسک حذف شده, ولی تغییرات بر روی براکتس اعمال/ذخیره نشده.<br /><br />آیا می خواهید تغییرات را حفظ کنید?",
  "WINDOW_UNLOAD_WARNING": "آیا مطمئن هستید که می‌خواهید به URL دیگری بروید و Brackets را ترک کنید؟",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "شما تغییرات ذخیره نشده ای دارید! آیا مطمئن هستید که می‌خواهید به URL دیگری بروید و Brackets را ترک کنید؟",
  "DONE": "انجام",
  "OK": "تائید",
  "CANCEL": "لغو",
  "DONT_SAVE": "ذخیره نکن",
  "SAVE": "ذخیره",
  "SAVE_AS": "ذخیره با نام…",
  "SAVE_AND_OVERWRITE": "دوباره نویسی",
  "DELETE": "حذف",
  "BUTTON_YES": "بله",
  "BUTTON_NO": "خیر",
  "FIND_MATCH_INDEX": "{0} از {1}",
  "FIND_NO_RESULTS": "بدون نتیجه",
  "FIND_QUERY_PLACEHOLDER": "جستجو…",
  "FIND_HISTORY_MAX_COUNT": "حداکثر تعداد موارد جستجو در تاریخچه جستجو",
  "REPLACE_PLACEHOLDER": "جایگزینی با…",
  "BUTTON_REPLACE_ALL": "همه…",
  "BUTTON_REPLACE_BATCH": "دسته…",
  "BUTTON_REPLACE_ALL_IN_FILES": "جایگزینی…",
  "BUTTON_REPLACE": "جایگزینی",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "تطبیق یافته بعدی",
  "BUTTON_PREV_HINT": "تطبیق یافته قبلی",
  "BUTTON_CASESENSITIVE_HINT": "مورد تطبیق یافته",
  "BUTTON_REGEXP_HINT": "عبارت منظم",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "جایگزینی بدون بازگشت",
  "REPLACE_WITHOUT_UNDO_WARNING": "بدلیل اعمال تغییر در تعداد {0} پرونده, {APP_NAME} پرونده های باز نشده را نیز ویرایش و تغییر خواهد داد. به همین جهت مقادیر تغییر یافته (جایگزین شده) غیر قابل بازگشت خواهند بود.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "جایگزینی بدون بازگشت",
  "OPEN_FILE": "باز کردن پرونده",
  "SAVE_FILE_AS": "ذخیره پرونده",
  "CHOOSE_FOLDER": "انتخاب یک پوشه",
  "RELEASE_NOTES": "نکات انتشار",
  "NO_UPDATE_TITLE": "شما بروز هستید!!",
  "NO_UPDATE_MESSAGE": "شما درحال استفاده از آخرین نسخه  {APP_NAME} هستید.",
  "FIND_REPLACE_TITLE_LABEL": "جایگزینی",
  "FIND_REPLACE_TITLE_WITH": "با",
  "FIND_TITLE_LABEL": "جستجو",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} با {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "در <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "در پروژه",
  "FIND_IN_FILES_ZERO_FILES": "فیلترسازی تمامی پرونده های منع شده {0}",
  "FIND_IN_FILES_FILE": "پرونده",
  "FIND_IN_FILES_FILES": "پرونده ها",
  "FIND_IN_FILES_MATCH": "تطبیق",
  "FIND_IN_FILES_MATCHES": "تطبیق ها",
  "FIND_IN_FILES_MORE_THAN": "بیش تر از ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "جهت بازکردن/بستن منوها کلید Ctrl/Cmd را گرفته و کلیک کنید.",
  "FIND_IN_FILES_INDEXING": "در حال نمایه سازی برای جستجوی فوری…",
  "FIND_IN_FILES_INDEXING_PROGRESS": "نمایه سازی {0} از {1} فایل برای جستجوی فوری…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "خطاهای جایگزینی مقادیر",
  "REPLACE_IN_FILES_ERRORS": "پرونده های زیر قابل ویرایش نبودن. علت می تواند از قابل نوشتن نبودن پرونده های و یا تغییر آن های بعد از جستجو باشد.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "درحال بروزرسانی اطلاعات خطا",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "بروز خطا در هنگام دستیابی به آخرین اطلاعات بروزرسانی از سرویس دهنده. اطمینان حاصل کنید که به اینترنت متصل بوده و دوباره تلاش نمایید.",
  "NEW_FILE_FILTER": "اعمال یک تصویه(فیلتر) جدید…",
  "CLEAR_FILE_FILTER": "رفع نادیده گیری پرونده ها",
  "NO_FILE_FILTER": "این پرونده ها از پرونده های نادیده گرفته شده نیستند",
  "EXCLUDE_FILE_FILTER": "نادیده گیری {0}",
  "EDIT_FILE_FILTER": "ویرایش…",
  "FILE_FILTER_DIALOG": "ویرایش نادیده گرفته شده ها",
  "FILE_FILTER_INSTRUCTIONS": "نادیده گیری پرونده ها و پوشه های منطبق با عبارات زیر یا برخی / substrings or <a href='{0}' title='{0}'>نویسه های عام</a>. هر عبارت را در یک سطر جدید وارد کنید.",
  "FILTER_NAME_PLACEHOLDER": "منع نام (اختیاری)",
  "FILTER_NAME_REMAINING": "{0} کاراکتر باقی مانده است",
  "FILE_FILTER_CLIPPED_SUFFIX": "و {0} بیشتر",
  "FILTER_COUNTING_FILES": "شمارش پرونده ها…",
  "FILTER_FILE_COUNT": "همیشه {0} از {1} پرونده {2}",
  "FILTER_FILE_COUNT_ALL": "تایید {0} پرونده {1}",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "امکان ویرایش سریع برای مکان فعلی نشانگر موجود نمی باشد",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "ویرایشگر سریع CSS: نشانگر را روی یک کلاس قرار دهید",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "ویرایشگر سریع CSS: صفات/خصوصیات این کلاس کامل نیست",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "ویرایشگر سریع CSS: صفات/خصوصیات این id کامل نیست",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "ویرایشگر سریع CSS: نشانگر را بر روی یک تگ، کلاس یا id قرار دهید",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "تابع زمانبندی ویرایشگر سریع CSS: خطا در نحو",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "ویرایشگر سریع JS: نشانگر را روی نام تابع قرار دهید",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "سند سریع برای مکان فعلی نمایشگر مکان موجود نمی باشد",
  "PROJECT_LOADING": "درحال بارگذاری…",
  "UNTITLED": "عنوان گذاری نشده",
  "WORKING_FILES": "پرونده های کاری",
  "TOP": "بالا",
  "BOTTOM": "پایین",
  "LEFT": "چپ",
  "RIGHT": "راست",
  "CMD_SPLITVIEW_NONE": "بدون دو بخشی کردن",
  "CMD_SPLITVIEW_VERTICAL": "دو بخشی کردن عمودی",
  "CMD_SPLITVIEW_HORIZONTAL": "دو بخشی کردن افقی",
  "SPLITVIEW_MENU_TOOLTIP": "دو بخشی کردن ویرایشگر به صورت عمودی یا افقی",
  "GEAR_MENU_TOOLTIP": "پیکربندی پرونده های کاری",
  "SPLITVIEW_INFO_TITLE": "هم اکنون باز است",
  "SPLITVIEW_MULTIPANE_WARNING": "این پرونده هم اکنون در پنجره ای دیگر باز شده است. {APP_NAME} بزودی باز کردن همان پرونده در سایر پنجره ها را پشتیبانی خواهد نمود. تا آن زمان پرونده ها تنها در پنجره ای که باز شده اند نمایش داده خواند شد.<br /><br />(این پیغام تنها یک بار مشاهده خواهد شد.)",
  "STATUSBAR_CURSOR_POSITION": "خط {0}, ستون {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — {0} ستون انتخاب شده",
  "STATUSBAR_SELECTION_CH_PLURAL": " — {0} ستون های انتخاب شده",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — {0} خط انتخاب شده",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — {0} خط های انتخاب شده",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} انتخاب شده ها",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "کلیک کنید تا به این فضاها منتقل شوید",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "کلیک کنید تا به این زبانه ها منتقل شوید",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "جهت تغییر تعداد فضاهای خالی استفاده شده در هنگام فاصله دهی خطوط از چپ، کلیک کنید",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "کلیک کنید تا طول زبانه کاراکتر ها تغییر کند",
  "STATUSBAR_SPACES": "فاصله ها:",
  "STATUSBAR_TAB_SIZE": "اندازه زبانه:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} خط",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} خط ها",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "غیرفعال سازی افزونه ها",
  "STATUSBAR_INSERT": "واردسازی",
  "STATUSBAR_OVERWRITE": "دوباره نویسی",
  "STATUSBAR_INSOVR_TOOLTIP": "جهت تغییر حالت از وارد سازی (INS) به بازنویسی (OVR) یا برعکس، کلیک کنید",
  "STATUSBAR_LANG_TOOLTIP": "جهت تغییر نوع پرونده، کلیک کنید.",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. باز و بسته کردن پنل گزارشات.",
  "STATUSBAR_DEFAULT_LANG": "(پیش فرض)",
  "STATUSBAR_SET_DEFAULT_LANG": " اعمال بعنوان پیش فرض برای .{0} پرونده ها",
  "STATUSBAR_ENCODING_TOOLTIP": "رمزگذاری را انتخاب کنید",
  "ERRORS_PANEL_TITLE_MULTIPLE": " {0} خطا",
  "SINGLE_ERROR": " 1 {0} خطا",
  "MULTIPLE_ERRORS": " {1} {0} خطا",
  "NO_ERRORS": "هیچ خطایی یافت نشد {0} - کارت خوبه!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "خطایی پیدا نشد - کارت خوبه!",
  "LINT_DISABLED": "Linting غیرفعال شد",
  "NO_LINT_AVAILABLE": "linter برای {0} دردسترس نیست",
  "NOTHING_TO_LINT": "linter برای {0} دردسترس نیست",
  "LINTER_TIMED_OUT": "فعالیت{0} پس از انتظار بمدت{1} میلی ثانیه خاتمه یافت",
  "LINTER_FAILED": "{0} با خطای زیر پایان یافته: {1}",
  "FILE_MENU": "فایل",
  "CMD_FILE_NEW_UNTITLED": "جدید",
  "CMD_FILE_NEW": "فایل جدید",
  "CMD_FILE_DUPLICATE": "دو نسخه کردن خط",
  "CMD_FILE_DOWNLOAD_PROJECT": "دانلود پروژه",
  "CMD_FILE_DOWNLOAD": "دانلود",
  "CMD_FILE_CUT": "بریدن",
  "CMD_FILE_COPY": "رونوشت",
  "CMD_FILE_COPY_PATH": "مسیر را کپی کنید",
  "CMD_FILE_PASTE": "چسباندن رو نوشت",
  "CMD_PROJECT_NEW": "پروژه جدید",
  "CMD_FILE_NEW_FOLDER": "پوشه جدید",
  "CMD_FILE_OPEN": "باز کردن…",
  "CMD_RECENT_FILES_OPEN": "فایل های اخیر…",
  "CMD_ADD_TO_WORKING_SET": "افزودن به محیط کاری و باز کردن آن",
  "CMD_OPEN_DROPPED_FILES": "باز کردن پرونده های در نظر گرفته نشده",
  "CMD_OPEN_FOLDER": "باز کردن پوشه…",
  "CMD_FILE_CLOSE": "بستن",
  "CMD_FILE_CLOSE_ALL": "بستن همه",
  "CMD_FILE_CLOSE_LIST": "بستن لیست",
  "CMD_FILE_CLOSE_OTHERS": "بستن سایر موارد",
  "CMD_FILE_CLOSE_ABOVE": "بستن موارد بالایی",
  "CMD_FILE_CLOSE_BELOW": "بستن موارد پایینی",
  "CMD_FILE_SAVE": "ذخیره پرونده",
  "CMD_FILE_SAVE_ALL": "ذخیره همه",
  "CMD_FILE_SAVE_AS": "ذخیره با نام…",
  "CMD_LIVE_FILE_PREVIEW": "پیش نمایش زنده",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "فعال کردن پیش نمایش تجربی",
  "CMD_RELOAD_LIVE_PREVIEW": "بارگذاری مجدد پیش نمایش زنده (با فشار)",
  "CMD_PROJECT_SETTINGS": "تنظیمات پروژه…",
  "CMD_FILE_RENAME": "تغییر نام",
  "CMD_FILE_DELETE": "حذف",
  "CMD_INSTALL_EXTENSION": "نصب افزونه …",
  "CMD_EXTENSION_MANAGER": "مدیریت افزونه…",
  "CMD_FILE_REFRESH": "نوسازی درختی پرونده",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "ابتدا پوشه ها را مرتب کنید",
  "CMD_QUIT": "ترک کردن",
  "CMD_EXIT": "خروج",
  "EDIT_MENU": "ویرایش",
  "CMD_UNDO": "مرحله قبل",
  "CMD_REDO": "یک مرحله به بعد",
  "CMD_CUT": "بریدن",
  "CMD_COPY": "رونوشت",
  "CMD_PASTE": "چسباندن رو نوشت",
  "CMD_SELECT_ALL": "انتخاب همه",
  "CMD_SELECT_LINE": "انتخاب خط",
  "CMD_SPLIT_SEL_INTO_LINES": "تقسیم انتخاب شده به چند سطر",
  "CMD_ADD_CUR_TO_NEXT_LINE": "افزودن نشانگر به سطر بعدی",
  "CMD_ADD_CUR_TO_PREV_LINE": "افزودن نشانگر به سطر قبلی",
  "CMD_INDENT": "یک فاصله از چپ",
  "CMD_UNINDENT": "حذف یک فاصله از چپ",
  "CMD_DUPLICATE": "دو نسخه کردن خط",
  "CMD_DELETE_LINES": "حذف خط",
  "CMD_COMMENT": "تعویض خط به نظر",
  "CMD_BLOCK_COMMENT": "تعویض نظر به خط",
  "CMD_LINE_UP": "خط را یکی به بالا ببر",
  "CMD_LINE_DOWN": "خط را یکی به پایین ببر",
  "CMD_OPEN_LINE_ABOVE": "باز کردن خط بالا",
  "CMD_OPEN_LINE_BELOW": "باز کردن خط زیرین",
  "CMD_TOGGLE_CLOSE_BRACKETS": "پرانتزها را خودکار ببند",
  "CMD_SHOW_CODE_HINTS": "نمایش نکات کد",
  "CMD_BEAUTIFY_CODE": "زیباسازی کد",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "زیباسازی کد پس از ذخیره",
  "FIND_MENU": "یافتن",
  "CMD_FIND": "یافتن",
  "CMD_FIND_NEXT": "یافتن بعدی",
  "CMD_FIND_PREVIOUS": "یافتن قبلی",
  "CMD_FIND_ALL_AND_SELECT": "جستجو برای تمامی موارد و انتخاب آن ها",
  "CMD_ADD_NEXT_MATCH": "عبارت انطباق یافته بعدی را به انتخاب شده ها اضافه کن",
  "CMD_SKIP_CURRENT_MATCH": "پرش از این مورد و افزودن مورد انطباق یافته بعدی",
  "CMD_FIND_IN_FILES": "جستجو در پرونده ها",
  "CMD_FIND_IN_SUBTREE": "جستجو در…",
  "CMD_REPLACE": "جایگزینی",
  "CMD_REPLACE_IN_FILES": "جایگزینی در پرونده ها",
  "CMD_REPLACE_IN_SUBTREE": "جایگزینی در…",
  "VIEW_MENU": "نمایش",
  "CMD_HIDE_SIDEBAR": "پنهان کردن نوار کناری",
  "CMD_SHOW_SIDEBAR": "نمایش نوار کناری",
  "CMD_TOGGLE_SIDEBAR": "نوار کناری را تغییر دهید",
  "CMD_TOGGLE_PANELS": "پانل ها را تغییر دهید",
  "CMD_TOGGLE_PURE_CODE": "بدون حواس پرتی",
  "CMD_INCREASE_FONT_SIZE": "افزایش سایز نوشته ها",
  "CMD_DECREASE_FONT_SIZE": "کاهش سایز نوشته ها",
  "CMD_RESTORE_FONT_SIZE": "پیشفرض سایز نوشته ها",
  "CMD_SCROLL_LINE_UP": "حرکت به بالا",
  "CMD_SCROLL_LINE_DOWN": "حرکت به پایین",
  "CMD_TOGGLE_LINE_NUMBERS": "شماره گذاری خط ها",
  "CMD_TOGGLE_ACTIVE_LINE": "نشانه گذاری خط فعال",
  "CMD_TOGGLE_WORD_WRAP": "شکستن عبارات طولانی",
  "CMD_LIVE_HIGHLIGHT": "نشانه گذاری پیش نمایش",
  "CMD_VIEW_TOGGLE_INSPECTION": "نشانه گذاری پرونده های تغییر یافته برای ذخیره سازی",
  "CMD_WORKINGSET_SORT_BY_ADDED": "مرتب سازی بر اساس ترتیب اضافه شدن",
  "CMD_WORKINGSET_SORT_BY_NAME": "مرتب سازی بر اساس نام",
  "CMD_WORKINGSET_SORT_BY_TYPE": "مرتب سازی بر اساس نوع",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "مرتب سازی خودکار",
  "CMD_THEMES": "پوسته ها…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "بستن خودکار جستجو",
  "NAVIGATE_MENU": "انتقال",
  "CMD_QUICK_OPEN": "باز کردن سریع",
  "CMD_GOTO_LINE": "برو به خط",
  "CMD_GOTO_DEFINITION": "تعریف جستجوی سریع",
  "CMD_GOTO_DEFINITION_PROJECT": "تعریف سریع یافتن در پروژه",
  "CMD_GOTO_FIRST_PROBLEM": "رجوع به اولین خطا/اخطار",
  "CMD_TOGGLE_QUICK_EDIT": "ویرایش سریع",
  "CMD_TOGGLE_QUICK_DOCS": "مستند گزاری سریع",
  "CMD_QUICK_EDIT_PREV_MATCH": "تطبیق یافته قبلی",
  "CMD_QUICK_EDIT_NEXT_MATCH": "تطبیق یافته بعدی",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "قائده جدید",
  "CMD_NEXT_DOC": "سند بعدی",
  "CMD_PREV_DOC": "سند قبلی",
  "CMD_NAVIGATE_BACKWARD": "به عقب حرکت کنید",
  "CMD_NAVIGATE_FORWARD": "حرکت به جلو",
  "CMD_NEXT_DOC_LIST_ORDER": "سند بعدی در لیست",
  "CMD_PREV_DOC_LIST_ORDER": "سند قبلی در فهرست",
  "CMD_SHOW_IN_TREE": "نمایش در پرونده ها به صورت درختی",
  "CMD_SHOW_IN_EXPLORER": "نمایش در پیمایشگر",
  "CMD_SHOW_IN_FINDER": "نمایش در جستجوگر",
  "CMD_SHOW_IN_OS": "نمایش در OS",
  "CMD_SWITCH_PANE_FOCUS": "سوئیچ پانل فوکوس",
  "CMD_OPEN_VFS": "سیستم فایل مجازی را باز کنید",
  "CMD_OPEN_VIRTUAL_SERVER": "سرور مجازی را باز کنید",
  "HELP_MENU": "راهنما",
  "CMD_CHECK_FOR_UPDATE": "بررسی بروزرسانی ها",
  "CMD_HOW_TO_USE_BRACKETS": "چگونگی استفاده از {APP_NAME}",
  "CMD_SUPPORT": "{APP_NAME} پشتیبانی",
  "CMD_SUGGEST": "پیشنهاد یک امکان جدید",
  "CMD_RELEASE_NOTES": "نکات انتشار",
  "CMD_GET_INVOLVED": "درگیرش شوید",
  "CMD_SHOW_EXTENSIONS_FOLDER": "نمایش پوشه افزونه ها",
  "CMD_HEALTH_DATA_STATISTICS": "گزارش سلامت",
  "CMD_HOMEPAGE": "صفحه اصلی {APP_NAME}",
  "CMD_TWITTER": "{TWITTER_NAME} در توییتر",
  "CMD_ABOUT": "درباره {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "تنظیمات باز کردن فایل",
  "CMD_OPEN_KEYMAP": "باز کردن نقشه کلیدهای کاربردی",
  "EXPERIMENTAL_BUILD": "ساخت آزمایشی",
  "RELEASE_BUILD": "ساختن و انتشار",
  "DEVELOPMENT_BUILD": "ایجاد توسعه",
  "PRERELEASE_BUILD": "ساخت پیش انتشار",
  "RELOAD_FROM_DISK": "بارگذاری مجدد از دیسک",
  "KEEP_CHANGES_IN_EDITOR": "نگه داشتن تغییرات در ویرایشگر",
  "CLOSE_DONT_SAVE": "بستن (بدون ذخیره سازی)",
  "RELAUNCH_CHROME": "اجرای دوباره کروم",
  "ABOUT": "پیرامون",
  "CLOSE": "بستن",
  "ABOUT_TEXT_LINE1": "انتشار {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "زمان ساخت:",
  "ABOUT_TEXT_LINE3": "کتابخانه های شخص ثالثی که ما استفاده می کنیم - <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>مجوزها و اسناد</a> .",
  "ABOUT_TEXT_LINE4": "مستندات و منبع در <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "ساخته شده با ❤ و جاوا اسکریپت توسط:",
  "ABOUT_TEXT_LINE6": "افراد زیادی (اما در حال حاضر در بارگیری این داده ها با مشکل مواجه هستیم).",
  "ABOUT_TEXT_MDN_DOCS": "اسناد و مدارک صفحات وب و آرم اصلی گرافیکی تحت مجوز , <a href='#' class='clickable-link' data-href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 .پایه ریزی شده است</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "ساخته ی جدیدی از {APP_NAME} هم اکنون در دسترس است! جهت مشاهده جزئیات کلیک کنید.",
  "UPDATE_AVAILABLE_TITLE": "بروزرسانی جدید در دسترس است",
  "UPDATE_RELOAD_APP": "لطفاً همه پنجره‌ها/برگه‌های {APP_NAME} را ببندید و برای دریافت آخرین نسخه، {APP_NAME} را دوباره باز کنید.",
  "UPDATE_MESSAGE": "نسخه جدیدی از {APP_NAME} هم اکنون در دسترس است. برخی از مشخصه های آن:",
  "GET_IT_NOW": "اکنون برو به!",
  "PROJECT_SETTINGS_TITLE": "تنظیمات پروژه برای: {0}",
  "PROJECT_SETTING_BASE_URL": "پیش نمایش URL اصلی/پایه",
  "PROJECT_SETTING_BASE_URL_HINT": "جهت استفاده از سرویس دهنده داخلی, از url بمانند http://localhost:8000/ استفاده کنید.",
  "BASEURL_ERROR_INVALID_PROTOCOL": "پروتکول {0} با پیش نمایش زنده پشتیبانی نمی شود&mdash;لطفا از http: یا https: استفاده نمایید.",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "URL اصلی نمی تواند شامل پارامترهای جستجو بمانند \"{0}\" باشد.",
  "BASEURL_ERROR_HASH_DISALLOWED": "URL اصلی نمی تواند hashes مشابه \"{0}\" داشته باشد.",
  "BASEURL_ERROR_INVALID_CHAR": "برخی کاراکترهای خاص شبیه '{0}' می بایست %-encoded.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "خطای ناشناخته در URL اصلی/پایه",
  "EMPTY_VIEW_HEADER": "<em>انتخاب کنید یک فایلی را در حالی که بر روی این قسمت تمرکز شده است</em>",
  "FLIPVIEW_BTN_TOOLTIP": "این نما را به صفحه {0} برگردانید",
  "CURRENT_THEME": "پوسته فعلی",
  "USE_THEME_SCROLLBARS": "استفاده از نوار شناور پوسته",
  "FONT_SIZE": "اندازه قلم",
  "FONT_FAMILY": "نوع قلم",
  "THEMES_SETTINGS": "تنظیمات پوسته ها",
  "THEMES_ERROR": "خطای تم",