/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "Langue par défaut du système",
  "PROJECT_BUSY": "Opérations du projet en cours",
  "DUPLICATING": "Dupliquer {0}",
  "MOVING": "Déménagement {0}",
  "COPYING": "Copie de {0}",
  "DELETING": "Suppression de {0}",
  "RENAMING": "Renommer",
  "GENERIC_ERROR": "(Erreur {0})",
  "NOT_FOUND_ERR": "Fichier/répertoire introuvable.",
  "NOT_READABLE_ERR": "Impossible de lire le fichier/répertoire.",
  "EXCEEDS_MAX_FILE_SIZE": "Les fichiers dont la taille excède {0} Mo ne peuvent pas être ouverts dans {APP_NAME}.",
  "NO_MODIFICATION_ALLOWED_ERR": "Le répertoire cible ne peut pas être modifié.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Vous n’êtes pas autorisé à effectuer des modifications.",
  "CONTENTS_MODIFIED_ERR": "Le fichier a été modifié dans une application autre que {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "Format de codage inconnu",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} n’a pas pu coder le contenu du fichier.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} n’a pas pu décoder le contenu du fichier.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "Actuellement, {APP_NAME} ne prend pas en charge les fichiers texte codés UTF-16.",
  "FILE_EXISTS_ERR": "Le fichier ou le répertoire existe déjà.",
  "FILE": "fichier",
  "FILE_TITLE": "Fichier",
  "DIRECTORY": "répertoire",
  "DIRECTORY_TITLE": "Répertoire",
  "DIRECTORY_NAMES_LEDE": "noms de répertoires",
  "FILENAMES_LEDE": "noms de fichiers",
  "FILENAME": "Nom de fichier",
  "DIRECTORY_NAME": "Nom du répertoire",
  "ERROR_LOADING_PROJECT": "Erreur lors du chargement du projet",
  "OPEN_DIALOG_ERROR": "Une erreur s’est produite lors de l’affichage de la boîte de dialogue Ouvrir. (Erreur {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Une erreur s’est produite lors de la tentative de chargement du répertoire <span class='dialog-filename'>{0}</span>. (Erreur {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Une erreur s’est produite lors de la lecture du contenu du répertoire <span class='dialog-filename'>{0}</span>. (Erreur {1})",
  "ERROR_OPENING_FILE_TITLE": "Erreur lors de l’ouverture du fichier",
  "ERROR_OPENING_FILE": "Une erreur s’est produite lors de la tentative d’ouverture du fichier <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Une erreur s’est produite en tentant d’ouvrir les fichiers suivants :",
  "ERROR_RELOADING_FILE_TITLE": "Erreur lors du rechargement des modifications à partir du disque",
  "ERROR_RELOADING_FILE": "Une erreur s’est produite lors de la tentative de rechargement du fichier <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Erreur lors de l’enregistrement du fichier",
  "ERROR_SAVING_FILE": "Une erreur s’est produite lors de la tentative d’enregistrement du fichier <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Erreur lors du changement de nom du {0}",
  "ERROR_RENAMING_FILE": "Une erreur s’est produite lors de la tentative de changement de nom du {2} <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Le fichier ou le répertoire ne fait pas partie du projet actuellement ouvert. Or, seuls les fichiers appartenant au projet peuvent être renommés à ce stade.",
  "ERROR_MOVING_FILE_TITLE": "Erreur lors du déplacement de l’élément {0}",
  "ERROR_MOVING_FILE": "Une erreur s’est produite lors du déplacement de l’élément {2} <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Impossible de déplacer le fichier/dossier, car ils ne font pas partie du projet en cours.",
  "ERROR_DELETING_FILE_TITLE": "Erreur lors de la suppression du {0}",
  "ERROR_DELETING_FILE": "Une erreur s’est produite lors de la tentative de suppression du {2} <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "{0} non valide",
  "CANNOT_PASTE_TITLE": "Impossible de coller {0}",
  "CANNOT_DOWNLOAD_TITLE": "Impossible de télécharger {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "Une erreur s&#39;est produite lors du téléchargement de <span class='dialog-filename'>{0}</span>",
  "ERR_TYPE_PASTE_FAILED": "Une erreur s&#39;est produite lors du collage de <span class='dialog-filename'>{0}</span> dans <span class='dialog-filename'>{1}</span>",
  "CANNOT_DUPLICATE_TITLE": "Impossible de dupliquer",
  "ERR_TYPE_DUPLICATE_FAILED": "Une erreur s&#39;est produite lors de la duplication de <span class='dialog-filename'>{0}</span>",
  "INVALID_FILENAME_MESSAGE": "Les {0} ne peuvent pas utiliser de termes réservés au système, finir par un point (.) ou contenir l’un des caractères suivants : <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Il existe déjà un fichier ou un répertoire portant le nom <span class='dialog-filename'>{0}</span>.",
  "ERROR_CREATING_FILE_TITLE": "Erreur lors de la création de l’élément {0}",
  "ERROR_CREATING_FILE": "Une erreur s’est produite lors de la tentative de création du {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "Impossible d’ouvrir un dossier en même temps que d’autres fichiers.",
  "ERROR_KEYMAP_TITLE": "Erreur lors de la lecture du mappage de touches utilisateur",
  "ERROR_KEYMAP_CORRUPT": "Votre fichier de mappage de touches n’est pas un fichier JSON valide. Il va s’ouvrir afin que vous puissiez corriger le format.",
  "ERROR_LOADING_KEYMAP": "Votre fichier de mappage de touches n’étant pas un fichier texte codé en UTF-8 valide, il ne peut pas être chargé.",
  "ERROR_RESTRICTED_COMMANDS": "Vous ne pouvez pas réaffecter de raccourcis à ces commandes : {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Vous ne pouvez pas réaffecter ces raccourcis : {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Vous réaffectez plusieurs raccourcis à ces commandes : {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Plusieurs liaisons ont été définies pour les raccourcis suivants : {0}",
  "ERROR_INVALID_SHORTCUTS": "Ces raccourcis ne sont pas valides : {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Vous affectez des raccourcis à des commandes qui n'existent pas : {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Erreur lors de la lecture des préférences",
  "ERROR_PREFS_CORRUPT": "Votre fichier de préférences n’est pas un fichier JSON valide, il va donc être ouvert afin que vous puissiez corriger le format. Vous devrez ensuite redémarrer {APP_NAME} pour que les modifications prennent effet.",
  "ERROR_PROJ_PREFS_CORRUPT": "Votre fichier de préférences de projet n’est pas un fichier JSON valide, il va donc être ouvert afin que vous puissiez corriger le format. Vous devrez ensuite recharger le projet pour que les modifications prennent effet.",
  "ERROR_IN_BROWSER_TITLE": "Malheureusement, {APP_NAME} n’est pas encore compatible avec les navigateurs.",
  "ERROR_IN_BROWSER": "{APP_NAME} est défini en HTML, mais il s’exécute actuellement en tant qu’application de bureau, vous pouvez donc l’utiliser afin de modifier des fichiers locaux. Utilisez l’interpréteur de commandes d’application situé dans le référentiel <b>github.com/adobe/brackets-shell</b> afin d’exécuter {APP_NAME}.",
  "ERROR_MAX_FILES_TITLE": "Erreur lors de l’indexation des fichiers",
  "ERROR_MAX_FILES": "Ce projet contient plus de 30 000 fichiers. Les fonctionnalités qui s’appliquent de manière globale à plusieurs fichiers peuvent être désactivées ou se comporter comme si le projet était vide. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>En savoir plus sur l’utilisation de projets volumineux</a>.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Erreur lors du lancement du navigateur",
  "ERROR_CANT_FIND_CHROME": "Le navigateur Google Chrome est introuvable. Assurez-vous qu’il est installé.",
  "ERROR_LAUNCHING_BROWSER": "Une erreur s’est produite lors du lancement du navigateur. (Erreur {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Erreur du module Aperçu en direct",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Connexion au navigateur",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Pour que le module Aperçu en direct puisse se connecter, vous devez relancer Chrome en activant la fonction de débogage à distance.<br /><br />Voulez-vous relancer Chrome et activer le débogage à distance ?<br /><br />",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Impossible de charger la page Aperçu en direct.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "Pour lancer l’Aperçu en direct avec un fichier de serveur, vous devez indiquer une URL de base pour ce projet.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Une erreur s’est produite au démarrage du serveur HTTP pour les fichiers d’aperçu en direct. Veuillez réessayer.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Pour plus d’informations, consultez la page <a href='{0}' title='{0}'>Résolution des erreurs de connexion à l’Aperçu en direct</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Aperçu en direct",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Aperçu en direct : Connexion…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Aperçu en direct : Initialisation…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Déconnecter le module Aperçu en direct",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Aperçu en direct",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Sélectionnez le fichier pour l'aperçu en direct",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Rafraîchir la page",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Basculer les faits saillants de l'aperçu en direct",
  "LIVE_DEV_CLICK_POPOUT": "Aperçu instantané en direct dans une nouvelle fenêtre",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Épingler sur la page d'aperçu de détachement",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Aperçu en direct (échec de la mise à jour en raison d’une erreur de syntaxe)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Aperçu en direct annulé car les outils de développement du navigateur étaient ouverts",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Aperçu en direct annulé car la page a été fermée dans le navigateur",
  "LIVE_DEV_NAVIGATED_AWAY": "Aperçu en direct annulé car le navigateur a accédé à une page qui ne fait pas partie du projet actuel",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Aperçu en direct annulé pour une raison inconnue ({0})",
  "SAVE_CLOSE_TITLE": "Enregistrer les modifications",
  "SAVE_CLOSE_MESSAGE": "Souhaitez-vous enregistrer les modifications apportées au document <span class='dialog-filename'>{0}</span> ?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Souhaitez-vous enregistrer les modifications apportées aux fichiers suivants ?",
  "EXT_MODIFIED_TITLE": "Modifications externes",
  "CONFIRM_DELETE_TITLE": "Confirmer la suppression",
  "CONFIRM_FILE_DELETE": "Souhaitez-vous vraiment supprimer le fichier <span class='dialog-filename'>{0}</span> ?",
  "CONFIRM_FOLDER_DELETE": "Voulez-vous vraiment supprimer le dossier <span class='dialog-filename'>{0}</span> ?",
  "FILE_DELETED_TITLE": "Fichier supprimé",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> a été modifié sur le disque, dans une application autre que {APP_NAME}.<br /><br />Voulez-vous enregistrer le fichier et remplacer ces modifications ?",
  "EXT_MODIFIED_MESSAGE": "Le fichier <span class='dialog-filename'>{0}</span> a été modifié sur le disque dans une autre application que {APP_NAME} mais présente également des modifications non enregistrées dans {APP_NAME}.<br /><br />Quelle version souhaitez-vous conserver ?",
  "EXT_DELETED_MESSAGE": "Le fichier <span class='dialog-filename'>{0}</span> a été supprimé du disque dans une autre application que {APP_NAME} mais présente également des modifications non enregistrées dans {APP_NAME}.<br /><br />Souhaitez-vous conserver vos modifications ?",
  "WINDOW_UNLOAD_WARNING": "Are you sure you want to navigate to a different URL and leave Brackets?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "You have unsaved changes! Are you sure you want to navigate to a different URL and leave Brackets?",
  "DONE": "Terminé",
  "OK": "OK",
  "CANCEL": "Annuler",
  "DONT_SAVE": "Ne pas enregistrer",
  "SAVE": "Enregistrer",
  "SAVE_AS": "Enregistrer sous…",
  "SAVE_AND_OVERWRITE": "Remplacer",
  "DELETE": "Supprimer",
  "BUTTON_YES": "Oui",
  "BUTTON_NO": "Non",
  "FIND_MATCH_INDEX": "{0} sur {1}",
  "FIND_NO_RESULTS": "Aucun résultat",
  "FIND_QUERY_PLACEHOLDER": "Rechercher…",
  "FIND_HISTORY_MAX_COUNT": "Nombre maximal d'éléments de recherche dans l'historique des recherches",
  "REPLACE_PLACEHOLDER": "Remplacer par…",
  "BUTTON_REPLACE_ALL": "Tout remplacer",
  "BUTTON_REPLACE_BATCH": "Traiter par lots…",
  "BUTTON_REPLACE_ALL_IN_FILES": "Remplacer…",
  "BUTTON_REPLACE": "Remplacer",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Correspondance suivante",
  "BUTTON_PREV_HINT": "Correspondance précédente",
  "BUTTON_CASESENSITIVE_HINT": "Respecter la casse",
  "BUTTON_REGEXP_HINT": "Expression régulière",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Remplacer sans possibilité d’annuler",
  "REPLACE_WITHOUT_UNDO_WARNING": "Dans la mesure où le nombre de fichiers à modifier excède {0}, {APP_NAME} va modifier des fichiers non ouverts sur le disque.<br />Vous ne pourrez pas annuler les remplacements effectués dans ces fichiers.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Remplacer sans possibilité d’annuler",
  "OPEN_FILE": "Ouvrir le fichier",
  "SAVE_FILE_AS": "Enregistrer le fichier",
  "CHOOSE_FOLDER": "Choisir un dossier",
  "RELEASE_NOTES": "Notes de mise à jour",
  "NO_UPDATE_TITLE": "Vos logiciels sont à jour !",
  "NO_UPDATE_MESSAGE": "Vous utilisez la dernière version de {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "Remplacer",
  "FIND_REPLACE_TITLE_WITH": "par",
  "FIND_TITLE_LABEL": "Occurrences trouvées pour",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} dans {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "dans <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "dans le projet",
  "FIND_IN_FILES_ZERO_FILES": "Le filtre exclut tous les fichiers {0}",
  "FIND_IN_FILES_FILE": "fichier",
  "FIND_IN_FILES_FILES": "fichiers",
  "FIND_IN_FILES_MATCH": "résultat",
  "FIND_IN_FILES_MATCHES": "résultats",
  "FIND_IN_FILES_MORE_THAN": "Plus de ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Cliquer tout en appuyant sur Ctrl/Cmd pour tout développer/tout réduire",
  "FIND_IN_FILES_INDEXING": "Indexation pour la recherche instantanée…",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Indexation de {0} fichiers sur {1} pour la recherche instantanée…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Erreurs de remplacement",
  "REPLACE_IN_FILES_ERRORS": "Les fichiers suivants n’ont pas été traités car ils ont été modifiés après l’opération de recherche ou ne sont pas accessibles en écriture.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Erreur de récupération des informations de mise à jour",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Un problème est survenu lors de la récupération des dernières informations de mise à jour sur le serveur. Vérifiez que vous êtes connecté à Internet et réessayez.",
  "NEW_FILE_FILTER": "Nouveau jeu d’exclusion…",
  "CLEAR_FILE_FILTER": "Ne pas exclure les fichiers",
  "NO_FILE_FILTER": "Aucun fichier exclu",
  "EXCLUDE_FILE_FILTER": "Exclure {0}",
  "EDIT_FILE_FILTER": "Modifier…",
  "FILE_FILTER_DIALOG": "Modifier le jeu d’exclusion",
  "FILE_FILTER_INSTRUCTIONS": "Exclure les fichiers et dossiers correspondant à l’une des chaînes/sous-chaînes ou aux <a href='{0}' title='{0}'>caractères génériques</a> suivants. Entrez chaque chaîne sur une ligne différente.",
  "FILTER_NAME_PLACEHOLDER": "Nommer ce jeu d’exclusion (facultatif)",
  "FILTER_NAME_REMAINING": "{0} caractères restants",
  "FILE_FILTER_CLIPPED_SUFFIX": "et {0} autre(s)",
  "FILTER_COUNTING_FILES": "Comptage des fichiers…",
  "FILTER_FILE_COUNT": "Autorise {0} fichier(s) sur les {1} {2}",
  "FILTER_FILE_COUNT_ALL": "Autorise les {0} fichiers {1}",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Fonction Édition rapide non disponible pour la position actuelle du curseur",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "Édition rapide CSS : placez le curseur sur un seul nom de classe",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "Édition rapide CSS : attribut de classe incomplet",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "Édition rapide CSS : attribut d’ID incomplet",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "Édition rapide CSS : placez le curseur dans la balise, la classe ou l’ID",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "Édition rapide des fonctions de temporisation CSS : syntaxe incorrecte",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "Édition rapide JS : placez le curseur dans le nom de fonction",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Fonction Documentation rapide non disponible pour la position actuelle du curseur",
  "PROJECT_LOADING": "Chargement…",
  "UNTITLED": "Sans titre",
  "WORKING_FILES": "Fichiers de travail",
  "TOP": "Haut",
  "BOTTOM": "Bas",
  "LEFT": "Gauche",
  "RIGHT": "Droite",
  "CMD_SPLITVIEW_NONE": "Pas de fractionnement",
  "CMD_SPLITVIEW_VERTICAL": "Fractionnement vertical",
  "CMD_SPLITVIEW_HORIZONTAL": "Fractionnement horizontal",
  "SPLITVIEW_MENU_TOOLTIP": "Fractionner l’éditeur horizontalement ou verticalement",
  "GEAR_MENU_TOOLTIP": "Configurer l’ensemble de travail",
  "SPLITVIEW_INFO_TITLE": "Déjà ouvert",
  "SPLITVIEW_MULTIPANE_WARNING": "Ce fichier est déjà ouvert dans un autre volet. Il sera bientôt possible d’ouvrir un même fichier dans plusieurs volets de l’application {APP_NAME}, mais en attendant, vous ne pouvez consulter le fichier que dans le volet dans lequel il est déjà ouvert.<br /><br />(Ce message ne s’affichera qu’une fois.)",
  "STATUSBAR_CURSOR_POSITION": "Ligne {0}, colonne {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — {0} colonne sélectionnée",
  "STATUSBAR_SELECTION_CH_PLURAL": " — {0} colonnes sélectionnées",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — {0} ligne sélectionnée",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — {0} lignes sélectionnées",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} sélections",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Cliquez ici pour remplacer la mise en retrait par des espaces.",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Cliquez ici pour remplacer la mise en retrait par des tabulations.",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Cliquez ici pour changer le nombre d’espaces utilisés lors de la mise en retrait.",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Cliquez ici pour modifier la largeur du caractère de tabulation.",
  "STATUSBAR_SPACES": "Espaces :",
  "STATUSBAR_TAB_SIZE": "Taille de tabulation :",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} ligne",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} lignes",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Extensions désactivées",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "RFP",
  "STATUSBAR_INSOVR_TOOLTIP": "Cliquez pour faire passer le curseur du mode Insertion (INS) au mode Remplacement (RFP) ou inversement",
  "STATUSBAR_LANG_TOOLTIP": "Cliquez pour modifier le type de fichier",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Cliquez pour afficher/masquer le panneau des rapports.",
  "STATUSBAR_DEFAULT_LANG": "(par défaut)",
  "STATUSBAR_SET_DEFAULT_LANG": "Utiliser par défaut pour les fichiers .{0}",
  "STATUSBAR_ENCODING_TOOLTIP": "Sélectionner le codage",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} problèmes",
  "SINGLE_ERROR": "1 problème {0}",
  "MULTIPLE_ERRORS": "{1} problèmes {0}",
  "NO_ERRORS": "Aucun problème {0} détecté, félicitations !",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Aucun problème détecté, félicitations !",
  "LINT_DISABLED": "L’analyse lint est désactivée",
  "NO_LINT_AVAILABLE": "Aucun programme lint disponible pour {0}",
  "NOTHING_TO_LINT": "Rien à analyser",
  "LINTER_TIMED_OUT": "Délai dépassé pour {0} après une attente de {1} ms",
  "LINTER_FAILED": "{0} arrêté avec l’erreur suivante : {1}",
  "FILE_MENU": "Fichier",
  "CMD_FILE_NEW_UNTITLED": "Nouveau",
  "CMD_FILE_NEW": "Nouveau fichier",
  "CMD_FILE_DUPLICATE": "Dupliquer",
  "CMD_FILE_DOWNLOAD_PROJECT": "Télécharger le projet",
  "CMD_FILE_DOWNLOAD": "Télécharger",
  "CMD_FILE_CUT": "Couper",
  "CMD_FILE_COPY": "Copier",
  "CMD_FILE_COPY_PATH": "Copier le chemin",
  "CMD_FILE_PASTE": "Coller",
  "CMD_PROJECT_NEW": "Nouveau projet",
  "CMD_FILE_NEW_FOLDER": "Nouveau dossier",
  "CMD_FILE_OPEN": "Ouvrir…",
  "CMD_RECENT_FILES_OPEN": "Fichiers récents…",
  "CMD_ADD_TO_WORKING_SET": "Ouvrir dans l’ensemble de travail",
  "CMD_OPEN_DROPPED_FILES": "Ouvrir les fichiers déposés",
  "CMD_OPEN_FOLDER": "Ouvrir un dossier…",
  "CMD_FILE_CLOSE": "Fermer",
  "CMD_FILE_CLOSE_ALL": "Tout fermer",
  "CMD_FILE_CLOSE_LIST": "Fermer la liste",
  "CMD_FILE_CLOSE_OTHERS": "Fermer tous les autres",
  "CMD_FILE_CLOSE_ABOVE": "Fermer les autres au-dessus",
  "CMD_FILE_CLOSE_BELOW": "Fermer les autres en dessous",
  "CMD_FILE_SAVE": "Enregistrer le fichier",
  "CMD_FILE_SAVE_ALL": "Enregistrer tout",
  "CMD_FILE_SAVE_AS": "Enregistrer sous…",
  "CMD_LIVE_FILE_PREVIEW": "Aperçu en direct",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Activer la version expérimentale de l’Aperçu en direct",
  "CMD_RELOAD_LIVE_PREVIEW": "Forcer le rechargement de l’aperçu en direct",
  "CMD_PROJECT_SETTINGS": "Paramètres du projet…",
  "CMD_FILE_RENAME": "Renommer",
  "CMD_FILE_DELETE": "Supprimer",
  "CMD_INSTALL_EXTENSION": "Installer une extension…",
  "CMD_EXTENSION_MANAGER": "Gestionnaire d'extensions…",
  "CMD_FILE_REFRESH": "Actualiser l’arborescence de fichiers",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Trier les dossiers en premier",
  "CMD_QUIT": "Quitter",
  "CMD_EXIT": "Quitter",
  "EDIT_MENU": "Modifier",
  "CMD_UNDO": "Annuler",
  "CMD_REDO": "Répéter",
  "CMD_CUT": "Couper",
  "CMD_COPY": "Copier",
  "CMD_PASTE": "Coller",
  "CMD_SELECT_ALL": "Sélectionner tout",
  "CMD_SELECT_LINE": "Sélectionner la ligne",
  "CMD_SPLIT_SEL_INTO_LINES": "Scinder la sélection en lignes",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Ajouter un curseur à la ligne suivante",
  "CMD_ADD_CUR_TO_PREV_LINE": "Ajouter un curseur à la ligne précédente",
  "CMD_INDENT": "Retrait",
  "CMD_UNINDENT": "Annuler le retrait",
  "CMD_DUPLICATE": "Dupliquer",
  "CMD_DELETE_LINES": "Supprimer la ligne",
  "CMD_COMMENT": "Activer/Désactiver le commentaire de ligne",
  "CMD_BLOCK_COMMENT": "Commenter les blocs/Annuler les commentaires",
  "CMD_LINE_UP": "Déplacer la ligne vers le haut",
  "CMD_LINE_DOWN": "Déplacer la ligne vers le bas",
  "CMD_OPEN_LINE_ABOVE": "Ouvrir une ligne au-dessus",
  "CMD_OPEN_LINE_BELOW": "Ouvrir une ligne en dessous",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Fermeture automatique des accolades",
  "CMD_SHOW_CODE_HINTS": "Afficher les indicateurs de code",
  "CMD_BEAUTIFY_CODE": "Embellir le code",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "Embellir le code après l'enregistrement",
  "FIND_MENU": "Rechercher",
  "CMD_FIND": "Rechercher",
  "CMD_FIND_NEXT": "Rechercher suivant",
  "CMD_FIND_PREVIOUS": "Rechercher précédent",
  "CMD_FIND_ALL_AND_SELECT": "Rechercher et sélectionner tout",
  "CMD_ADD_NEXT_MATCH": "Ajouter l’occurrence suivante à la sélection",
  "CMD_SKIP_CURRENT_MATCH": "Ignorer et ajouter l’occurrence suivante",
  "CMD_FIND_IN_FILES": "Rechercher dans les fichiers",
  "CMD_FIND_IN_SUBTREE": "Rechercher dans…",
  "CMD_REPLACE": "Remplacer",
  "CMD_REPLACE_IN_FILES": "Remplacer dans les fichiers",
  "CMD_REPLACE_IN_SUBTREE": "Remplacer dans…",
  "VIEW_MENU": "Affichage",
  "CMD_HIDE_SIDEBAR": "Masquer la barre latérale",
  "CMD_SHOW_SIDEBAR": "Afficher la barre latérale",
  "CMD_TOGGLE_SIDEBAR": "Afficher/Masquer la barre latérale",
  "CMD_TOGGLE_PANELS": "Afficher/Masquer les panneaux",
  "CMD_TOGGLE_PURE_CODE": "Pas de distraction",
  "CMD_INCREASE_FONT_SIZE": "Augmenter la taille de la police",
  "CMD_DECREASE_FONT_SIZE": "Diminuer la taille de la police",
  "CMD_RESTORE_FONT_SIZE": "Restaurer la taille de la police",
  "CMD_SCROLL_LINE_UP": "Faire défiler d’une ligne vers le haut",
  "CMD_SCROLL_LINE_DOWN": "Faire défiler d’une ligne vers le bas",
  "CMD_TOGGLE_LINE_NUMBERS": "Numéros de ligne",
  "CMD_TOGGLE_ACTIVE_LINE": "Surligner la ligne active",
  "CMD_TOGGLE_WORD_WRAP": "Renvoi à la ligne",
  "CMD_LIVE_HIGHLIGHT": "Surlignement dans l’Aperçu en direct",
  "CMD_VIEW_TOGGLE_INSPECTION": "Effectuer une analyse lint des fichiers à l’