/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "језик система",
  "PROJECT_BUSY": "Пројектне операције су у току",
  "DUPLICATING": "Дуплицирање {0}",
  "MOVING": "Премештање {0}",
  "COPYING": "Копирање {0}",
  "DELETING": "Брисање {0}",
  "RENAMING": "Преименовање",
  "GENERIC_ERROR": "(грешка {0})",
  "NOT_FOUND_ERR": "Непостојећа датотека.",
  "NOT_READABLE_ERR": "Датотека не може бити учитана.",
  "EXCEEDS_MAX_FILE_SIZE": "Датотеке веће од {0} MB се не могу отворити у {APP_NAME}-у.",
  "NO_MODIFICATION_ALLOWED_ERR": "Циљани директоријум не може бити измењен.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Тренутна овлашћења Вам не дозвољавају да правите измене.",
  "CONTENTS_MODIFIED_ERR": "Ова датотека је била измењена ван {APP_NAME}-а.",
  "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} тренутно подржава искључиво текстуалне датотеке које су енкодиране у UTF-8 формату.",
  "ENCODE_FILE_FAILED_ERR": "{АПП_НАМЕ} није могао да кодира садржај датотеке.",
  "DECODE_FILE_FAILED_ERR": "{АПП_НАМЕ} није могао да декодира садржај датотеке.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{АПП_НАМЕ} тренутно не подржава текстуалне датотеке кодиране УТФ-16.",
  "FILE_EXISTS_ERR": "Датотека или директоријум већ постоји.",
  "FILE": "датотеци",
  "FILE_TITLE": "Датотека",
  "DIRECTORY": "директоријум",
  "DIRECTORY_TITLE": "Директоријум",
  "DIRECTORY_NAMES_LEDE": "Имена директоријума",
  "FILENAMES_LEDE": "Имена датотека",
  "FILENAME": "Име датотеке",
  "DIRECTORY_NAME": "Име директоријума",
  "ERROR_LOADING_PROJECT": "Грешка приликом учитавања пројекта",
  "OPEN_DIALOG_ERROR": "Дошло је до грешке приликом приказивања дијалога за отварање датотеке. (грешка {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Дошло је до грешке приликом покушаја да се учита директоријум <span class='dialog-filename'>{0}</span>. (грешка {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Дошло је до грешке приликом ишчитавања садржаја директоријума <span class='dialog-filename'>{0}</span>. (грешка {1})",
  "ERROR_OPENING_FILE_TITLE": "Грешка при отварању датотеке",
  "ERROR_OPENING_FILE": "Дошло је до грешке приликом покушаја да се отвори датотека <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Дошло је до грешке приликом покушаја да се отворе следеће датотеке:",
  "ERROR_RELOADING_FILE_TITLE": "Грешка при поновном учитавању измена са диска",
  "ERROR_RELOADING_FILE": "Дошло је до грешке приликом покушаја да се поново учита датотека <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Грешка при чувању датотеке",
  "ERROR_SAVING_FILE": "Дошло је до грешке приликом покушаја да се сачува датотека <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Грешка приликом преименовања датотеке {0}",
  "ERROR_RENAMING_FILE": "Дошло је до грешке приликом покушаја да се преименује датотека {2} <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Датотека или директоријум није део тренутно отвореног пројекта. Нажалост, у овом тренутку могу се преименовати само пројектне датотеке.",
  "ERROR_MOVING_FILE_TITLE": "Грешка при премештању {0}",
  "ERROR_MOVING_FILE": "Дошло је до грешке при покушају да преместите {2} <span class='dialog-filename'>{0}</span> . {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Није могуће преместити датотеку/директоријум, јер они нису део тренутног пројекта.",
  "ERROR_DELETING_FILE_TITLE": "Грешка при брисању датотеке {0}",
  "ERROR_DELETING_FILE": "Дошло је до грешке приликом покушаја да се обрише датотека {2} <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "Име {0} није валидно",
  "CANNOT_PASTE_TITLE": "Није могуће налепити {0}",
  "CANNOT_DOWNLOAD_TITLE": "Није могуће преузети {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "Дошло је до грешке при преузимању <span class='dialog-filename'>{0}</span>",
  "ERR_TYPE_PASTE_FAILED": "Дошло је до грешке при лепљењу <span class='dialog-filename'>{0}</span> у <span class='dialog-filename'>{1}</span>",
  "CANNOT_DUPLICATE_TITLE": "Није могуће дуплирати",
  "ERR_TYPE_DUPLICATE_FAILED": "Дошло је до грешке при дуплирању <span class='dialog-filename'>{0}</span>",
  "INVALID_FILENAME_MESSAGE": "Име {0} не сме садржати системски резервисане речи, не сме се завршити тачком (.) или користити неки од следећих карактера: <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Датотека или директоријум са именом <span class='dialog-filename'>{0}</span> већ постоји.",
  "ERROR_CREATING_FILE_TITLE": "Грешка при креирању {0}",
  "ERROR_CREATING_FILE": "Дошло је до грешке приликом покушаја да се креира {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "Директоријум се не може учитавати у исто време када и остале датотеке.",
  "ERROR_KEYMAP_TITLE": "Грешка приликом ишчитавања корисничке мапе пречица на тастатури",
  "ERROR_KEYMAP_CORRUPT": "Ваша мапа пречица на тастатури није валидан JSON. Датотека ће бити отворена како бисте исправили формат.",
  "ERROR_LOADING_KEYMAP": "Ваша мапа пречица на тастатури није валидна UTF-8 енкодирана текстуална датотека и не може се учитати",
  "ERROR_RESTRICTED_COMMANDS": "Не можете поново доделити пречице овим командама: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Не можете доделити ове пречице: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Додајете више пречица на тастатури за ове команде: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Имате више комбинација за ове пречице: {0}",
  "ERROR_INVALID_SHORTCUTS": "Ове пречице нису валидне: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Додајете пречице на тастатури непостојећим командама: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Грешка приликом ишчитавања подешавања",
  "ERROR_PREFS_CORRUPT": "Ваша датотека са подешавањима није валидан JSON. Датотека ће бити отворена како бисте исправили формат. Биће неопходно да поново покренете {APP_NAME} како би измене биле примењене.",
  "ERROR_PROJ_PREFS_CORRUPT": "Датотека са подешавањима вашег пројекта није важећа ЈСОН. Датотека ће се отворити да бисте могли да исправите формат. Мораћете поново да учитате пројекат да би промене ступиле на снагу.",
  "ERROR_IN_BROWSER_TITLE": "Упс! {APP_NAME} још увек не ради у веб претраживачу.",
  "ERROR_IN_BROWSER": "Апликација {APP_NAME} је направљена помоћу HTML-а, али тренутно ради као \"desktop\" апликација па је можете користити за измену локалних датотека. Молимо Вас користите \"application shell\" на <b>github.com/adobe/brackets-shell</b> репозиторијуму за покретање {APP_NAME}-а.",
  "ERROR_MAX_FILES_TITLE": "Грешка приликом индексирања датотека",
  "ERROR_MAX_FILES": "Пројекат садржи више од 30.000 датотека. Делови апликације који врше обраду над више датотека могу постати неактивни или се понашати као да је пројекат празан. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>Прочитајте више о раду са великим пројектима</a>.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Грешка при покретању претраживача",
  "ERROR_CANT_FIND_CHROME": "Google Chrome претраживач није пронађен. Молимо потврдите да је инсталиран.",
  "ERROR_LAUNCHING_BROWSER": "Грешка приликом покретања претраживача. (error {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Грешка у живом приказу",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Повезивање са веб претраживачем",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Да би се живи приказ повезао, потребно је да поново покренете Chrome са укљученим подешавањима за \"remote debugging\".<br /><br />Да ли желите поново да покренете Chrome са укљученим подешавањима за \"remote debugging\"?<br /><br />",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Није могуће учитати страницу са живим приказом.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "За покретање живог приказа са датотеком која је \"server-side\", морате навести основну URL адресу за овај пројекат.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Грешка приликом покретања HTTP сервера за \"живе\" развојне датотеке. Молимо покушајте поново.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "За више информација, погледајте <a href='{0}' title='{0}'>Отклањање грешака у конекцији приликом развоја уживо</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Живи приказ",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Живи приказ: Успостављање конекције…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Живи приказ: Иницијализација…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Прекини конекцију са живим приказом",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Живи приказ",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Изаберите Филе То Ливе Превиев",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Поново учитај страницу",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Укључи Истакнуто у прегледу уживо",
  "LIVE_DEV_CLICK_POPOUT": "Искачући преглед уживо у новом прозору",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Закачи на страницу за преглед откачи",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Живи приказ (не освежава се због грешке у синтакси)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Живи приказ је отказан јер су развојни алати били отворени у претраживачу",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Живи приказ је отказан јер је страница затворена у претраживачу",
  "LIVE_DEV_NAVIGATED_AWAY": "Живи приказ је отказан јер је претраживач отишао на страницу која није део тренутног пројекта",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Живи приказ је отказан из непознатог разлога ({0})",
  "SAVE_CLOSE_TITLE": "Сачувај измене",
  "SAVE_CLOSE_MESSAGE": "Да ли желите да сачувате измене које сте направили у документу <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Да ли желите да сачувате Ваше измене над следећим датотекама?",
  "EXT_MODIFIED_TITLE": "Екстерне измене",
  "CONFIRM_DELETE_TITLE": "Потврди брисање",
  "CONFIRM_FILE_DELETE": "Да ли сте сигурни да желите да избришете датотеку <span class='dialog-filename'>{0}</span> ?",
  "CONFIRM_FOLDER_DELETE": "Да ли сте сигурни да желите обрисати директоријум <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "Датотека обрисана",
  "EXT_MODIFIED_WARNING": "Датотека <span class='dialog-filename'>{0}</span> је измењена на диску.<br /><br />Да ли желите да сачувате датотеку и преснимите те измене?",
  "EXT_MODIFIED_MESSAGE": "Датотека <span class='dialog-filename'>{0}</span> је измењена на диску, али садржи и измене начињене у {APP_NAME}-у.<br /><br />Коју верзију желите да сачувате?",
  "EXT_DELETED_MESSAGE": "Датотека <span class='dialog-filename'>{0}</span> је обрисана са диска, али садржи несачуване измене начињене у {APP_NAME}-у.<br /><br />Да ли желите да сачувате Ваше измене?",
  "WINDOW_UNLOAD_WARNING": "Да ли сте сигурни да желите да одете до друге УРЛ адресе и напустите заграде?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Имате несачуване промене! Да ли сте сигурни да желите да одете до друге УРЛ адресе и напустите заграде?",
  "DONE": "Завршено",
  "OK": "OK",
  "CANCEL": "Откажи",
  "DONT_SAVE": "Немој сачувати",
  "SAVE": "Сачувај",
  "SAVE_AS": "Сачувај као…",
  "SAVE_AND_OVERWRITE": "Пресними",
  "DELETE": "Обриши",
  "BUTTON_YES": "Да",
  "BUTTON_NO": "Не",
  "FIND_MATCH_INDEX": "{0} од {1}",
  "FIND_NO_RESULTS": "Нема резултата",
  "FIND_QUERY_PLACEHOLDER": "Пронађи…",
  "FIND_HISTORY_MAX_COUNT": "Максималан број ставки претраге у историји претраге",
  "REPLACE_PLACEHOLDER": "Замени са…",
  "BUTTON_REPLACE_ALL": "Комплет…",
  "BUTTON_REPLACE_BATCH": "Група…",
  "BUTTON_REPLACE_ALL_IN_FILES": "Замени…",
  "BUTTON_REPLACE": "Замени",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Следеће поклапање",
  "BUTTON_PREV_HINT": "Претходно поклапање",
  "BUTTON_CASESENSITIVE_HINT": "Иста величина",
  "BUTTON_REGEXP_HINT": "Регуларни израз",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Замени без опозива",
  "REPLACE_WITHOUT_UNDO_WARNING": "Зато што је потребно променити више од {0} датотека, {APP_NAME} ће изменити неотворене датотеке на диску.<br />Нећете бити у могућности да опозовете измене у овим датотекама.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Замени без опозива",
  "OPEN_FILE": "Отвори датотеку",
  "SAVE_FILE_AS": "Сачувај датотеку",
  "CHOOSE_FOLDER": "Изабери директоријум",
  "RELEASE_NOTES": "Белешке о тренутној верзији",
  "NO_UPDATE_TITLE": "Имате актуелну верзију!",
  "NO_UPDATE_MESSAGE": "Тренутно поседујете актуелну верзију апликације {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "Замени",
  "FIND_REPLACE_TITLE_WITH": "са",
  "FIND_TITLE_LABEL": "Пронађено",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} у {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "у <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "у пројекту",
  "FIND_IN_FILES_ZERO_FILES": "Филтер искључује све датотеке {0}",
  "FIND_IN_FILES_FILE": "датотеци",
  "FIND_IN_FILES_FILES": "датотека",
  "FIND_IN_FILES_MATCH": "поклапање",
  "FIND_IN_FILES_MATCHES": "поклапања",
  "FIND_IN_FILES_MORE_THAN": "Преко ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Притисните Ctrl/Cmd и кликните како бисте раширили/скупили све",
  "FIND_IN_FILES_INDEXING": "Индексирање за тренутну претрагу…",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Индексирање {0} од {1} фајлова за тренутну претрагу…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Замени грешке",
  "REPLACE_IN_FILES_ERRORS": "Следеће датотеке нису модификоване зато што су измењене након претраге или у њих није било могуће уписивати.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Грешка приликом учитавања информација о новој верзији",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Дошло је до проблема приликом преузимања последњих информација о новој верзији са сервера. Молимо проверите да ли сте повезани на интернет и покушајте поново.",
  "NEW_FILE_FILTER": "Нови сет искључења…",
  "CLEAR_FILE_FILTER": "Немој исључити датотеке",
  "NO_FILE_FILTER": "Ниједна датотека није искључена",
  "EXCLUDE_FILE_FILTER": "Искључи {0}",
  "EDIT_FILE_FILTER": "Измени…",
  "FILE_FILTER_DIALOG": "Измени сет искључења",
  "FILE_FILTER_INSTRUCTIONS": "Искључи све датотеке и директоријуме који се поклапају са било којим од следећих низова / поднизова или <a href='{0}' title='{0}'>џокер знакова</a>. Enter each string on a new line.",
  "FILTER_NAME_PLACEHOLDER": "Дај име овом сету искључења (опционо)",
  "FILTER_NAME_REMAINING": "Преостало знакова: {0}",
  "FILE_FILTER_CLIPPED_SUFFIX": "и још {0}",
  "FILTER_COUNTING_FILES": "Пребројавам датотеке…",
  "FILTER_FILE_COUNT": "Дозвољава {0} од {1} датотека {2}",
  "FILTER_FILE_COUNT_ALL": "Дозвољава свих {0} датотека {1}",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Брза измена није доступна на тренутној позицији курсора",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "CSS Брза измена: позиционирајте курсор на једно име класе",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "CSS Брза измена: непотпун атрибут класе",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "CSS Брза измена: непотпун атрибут идентификатора",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "CSS Брза измена: позиционирајте курсор на таг, класу, или идентификатор",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "CSS Времендска функција Брза измена: синтакса није валидна",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "JS Брза измена: позиционирајте курсор на име функције",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Брзи документи нису доступни за тренутну позицију курсора",
  "PROJECT_LOADING": "Учитавам…",
  "UNTITLED": "Неименовано",
  "WORKING_FILES": "Радне датотеке",
  "TOP": "Горе",
  "BOTTOM": "Доле",
  "LEFT": "Лево",
  "RIGHT": "Десно",
  "CMD_SPLITVIEW_NONE": "Без поделе",
  "CMD_SPLITVIEW_VERTICAL": "Вертикална подела",
  "CMD_SPLITVIEW_HORIZONTAL": "Хоризонтална подела",
  "SPLITVIEW_MENU_TOOLTIP": "Подели едитор вертикално или хоризонтално",
  "GEAR_MENU_TOOLTIP": "Конфигуриши радни сет",
  "SPLITVIEW_INFO_TITLE": "Већ отворена",
  "SPLITVIEW_MULTIPANE_WARNING": "Датотека је већ отворена у другом панелу. {APP_NAME} ће ускоро подржавати отварање исте датотеке у више панела. До тада, датотека ће бити приказана у панелу у коме је већ отворена.<br /><br />(Ова порука ће се приказати само једном.)",
  "STATUSBAR_CURSOR_POSITION": "Линија {0}, колона {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — Изабрана {0} колона",
  "STATUSBAR_SELECTION_CH_PLURAL": " — Изабрано {0} колона",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — Изабрана {0} линија",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — Изабрано {0} линија",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} селекција",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Кликни за коришћење размака приликом увлачења кôда",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Кликни за коришћење таб-ова приликом увлачења кôда",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Кликни за промену броја размака приликом увлачења кôда",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Кликни за промену величине таб-а приликом увлачења кôда",
  "STATUSBAR_SPACES": "Размаци:",
  "STATUSBAR_TAB_SIZE": "Величина таб-а:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} линија",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} линија",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Екстензије деактивиране",
  "STATUSBAR_INSERT": "УБ",
  "STATUSBAR_OVERWRITE": "ПРЕ",
  "STATUSBAR_INSOVR_TOOLTIP": "Кликни да промениш мôд курсора из Убаци (УБ) у Препиши (ПРЕ) и обрнуто",
  "STATUSBAR_LANG_TOOLTIP": "Кликни за измену типа датотеке",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Кликни за приказ/скривање панела са извештајима.",
  "STATUSBAR_DEFAULT_LANG": "(подразумевано)",
  "STATUSBAR_SET_DEFAULT_LANG": "Подеси као \"подразумевано\" за .{0} датотеке",
  "STATUSBAR_ENCODING_TOOLTIP": "Изаберите кодирање",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} грешака",
  "SINGLE_ERROR": "1 {0} грешка",
  "MULTIPLE_ERRORS": "{1} {0} грешака",
  "NO_ERRORS": "Нема {0} грешака - свака част!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Нема пронађених грешака - свака част!",
  "LINT_DISABLED": "Детектовање сумњивог кôда искључено",
  "NO_LINT_AVAILABLE": "Ниједан детектор сумњивог кôда није доступан за {0}",
  "NOTHING_TO_LINT": "Није пронађен сумњив кôд",
  "LINTER_TIMED_OUT": "Прекинуто је извршавање {0} након чекања од {1} ms",
  "LINTER_FAILED": "Прекинуто је извршавање {0} уз грешку: {1}",
  "FILE_MENU": "Датотека",
  "CMD_FILE_NEW_UNTITLED": "Нова",
  "CMD_FILE_NEW": "Нова датотека",
  "CMD_FILE_DUPLICATE": "Удвостручи",
  "CMD_FILE_DOWNLOAD_PROJECT": "Преузмите пројекат",
  "CMD_FILE_DOWNLOAD": "Преузимање",
  "CMD_FILE_CUT": "Исеци",
  "CMD_FILE_COPY": "Копирај",
  "CMD_FILE_COPY_PATH": "Копирај путању",
  "CMD_FILE_PASTE": "Налепи",
  "CMD_PROJECT_NEW": "Нови пројекат",
  "CMD_FILE_NEW_FOLDER": "Нови директоријум",
  "CMD_FILE_OPEN": "Отвори…",
  "CMD_RECENT_FILES_OPEN": "Недавни фајлови…",
  "CMD_ADD_TO_WORKING_SET": "Додај у радни сет",
  "CMD_OPEN_DROPPED_FILES": "Open Dropped Files",
  "CMD_OPEN_FOLDER": "Отвори директоријум…",
  "CMD_FILE_CLOSE": "Затвори",
  "CMD_FILE_CLOSE_ALL": "Затвори све",
  "CMD_FILE_CLOSE_LIST": "Затвори листу",
  "CMD_FILE_CLOSE_OTHERS": "Затвори остале",
  "CMD_FILE_CLOSE_ABOVE": "Затвори остале изнад",
  "CMD_FILE_CLOSE_BELOW": "Затвори остале испод",
  "CMD_FILE_SAVE": "Сачувај датотеку",
  "CMD_FILE_SAVE_ALL": "Сачувај све",
  "CMD_FILE_SAVE_AS": "Сачувај као…",
  "CMD_LIVE_FILE_PREVIEW": "Живи приказ",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Омогућите експериментални преглед уживо",
  "CMD_RELOAD_LIVE_PREVIEW": "На силу обнови Живи приказ",
  "CMD_PROJECT_SETTINGS": "Подешавање пројекта…",
  "CMD_FILE_RENAME": "Преименуј",
  "CMD_FILE_DELETE": "Обриши",
  "CMD_INSTALL_EXTENSION": "Инсталирај екстензију…",
  "CMD_EXTENSION_MANAGER": "Менаџер екстензија…",
  "CMD_FILE_REFRESH": "Освежи стабло датотека",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Прво сортирајте фасцикле",
  "CMD_QUIT": "Прекини",
  "CMD_EXIT": "Излаз",
  "EDIT_MENU": "Уреди",
  "CMD_UNDO": "Опозови",
  "CMD_REDO": "Понови",
  "CMD_CUT": "Исеци",
  "CMD_COPY": "Копирај",
  "CMD_PASTE": "Налепи",
  "CMD_SELECT_ALL": "Изабери све",
  "CMD_SELECT_LINE": "Изабери линију",
  "CMD_SPLIT_SEL_INTO_LINES": "Подели селекцију на линије",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Додај курсор следећој линији",
  "CMD_ADD_CUR_TO_PREV_LINE": "Додај курсор претходној линији",
  "CMD_INDENT": "Помери удесно",
  "CMD_UNINDENT": "Помери улево",
  "CMD_DUPLICATE": "Удвостручи",
  "CMD_DELETE_LINES": "Обриши линију",
  "CMD_COMMENT": "Додај/уклони линијски коментар",
  "CMD_BLOCK_COMMENT": "Додај/уклони блок коментар",
  "CMD_LINE_UP": "Помери линију горе",
  "CMD_LINE_DOWN": "Помери линију доле",
  "CMD_OPEN_LINE_ABOVE": "Отвори линију изнад",
  "CMD_OPEN_LINE_BELOW": "Отвори линију испод",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Аутоматски затвори заграде",
  "CMD_SHOW_CODE_HINTS": "Пружи малу помоћ око кôда",
  "CMD_BEAUTIFY_CODE": "Беаутифи Цоде",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "Улепшавање кода након чувања",
  "FIND_MENU": "Пронађи",
  "CMD_FIND": "Пронађи",
  "CMD_FIND_NEXT": "Пронађи следеће",
  "CMD_FIND_PREVIOUS": "Пронађи претходно",
  "CMD_FIND_ALL_AND_SELECT": "Пронађи све и изабери",
  "CMD_ADD_NEXT_MATCH": "Додај следеће поклапање у селекцију",
  "CMD_SKIP_CURRENT_MATCH": "Прескочи и додај следеће поклапање",
  "CMD_FIND_IN_FILES": "Пронађи међу датотекама",
  "CMD_FIND_IN_SUBTREE": "Пронађи у…",
  "CMD_REPLACE": "Замени",
  "CMD_REPLACE_IN_FILES": "Замени у датотекама",
  "CMD_REPLACE_IN_SUBTREE": "Замени у…",
  "VIEW_MENU": "Приказ",
  "CMD_HIDE_SIDEBAR": "Сакриј споредну траку",
  "CMD_SHOW_SIDEBAR": "Прикажи споредну траку",
  "CMD_TOGGLE_SIDEBAR": "Укључите бочну траку",
  "CMD_TOGGLE_PANELS": "Пребаци панеле",
  "CMD_TOGGLE_PURE_CODE": "Без ометања",
  "CMD_INCREASE_FONT_SIZE": "Повећај величину фонта",
  "CMD_DECREASE_FONT_SIZE": "Смањи величину фонта",
  "CMD_RESTORE_FONT_SIZE": "Поврати величину фонта",
  "CMD_SCROLL_LINE_UP": "Помакни једну линију горе",
  "CMD_SCROLL_LINE_DOWN": "Помакни једну линију доле",
  "CMD_TOGGLE_LINE_NUMBERS": "Бројеви редова",
  "CMD_TOGGLE_ACTIVE_LINE": "Означи активну линију",
  "CMD_TOGGLE_WORD_WRAP": "Прелом текста",
  "CMD_LIVE_HIGHLIGHT": "Обележи живи приказ",
  "CMD_VIEW_TOGGLE_INSPECTION": "Преконтролиши датотеке приликом чувања",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Сортирај 