/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "प्रणालीगत चूक",
  "PROJECT_BUSY": "परियोजना संचालन प्रगति पर",
  "DUPLICATING": "डुप्लीकेटिंग {0}",
  "MOVING": "चल रहा है {0}",
  "COPYING": "{0} कॉपी किया जा रहा है",
  "DELETING": "{0} को हटाया जा रहा है",
  "RENAMING": "नाम",
  "GENERIC_ERROR": "(त्रुटि {0})",
  "NOT_FOUND_ERR": "फ़ाइल/निर्देशिका नहीं मिली।",
  "NOT_READABLE_ERR": "फ़ाइल/निर्देशिका को पढ़ा नहीं जा सका।",
  "EXCEEDS_MAX_FILE_SIZE": "{APP_NAME} में {0}MB से बड़ी फ़ाइलें नहीं खोली जा सकतीं।",
  "NO_MODIFICATION_ALLOWED_ERR": "लक्ष्य निर्देशिका को संशोधित नहीं किया जा सकता है।",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "अनुमतियाँ आपको संशोधन करने की अनुमति नहीं देती हैं।",
  "CONTENTS_MODIFIED_ERR": "फ़ाइल को {APP_NAME} के बाहर संशोधित किया गया है।",
  "UNSUPPORTED_ENCODING_ERR": "अज्ञात एन्कोडिंग प्रारूप",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} फ़ाइल की सामग्री को एन्कोड करने में सक्षम नहीं था।",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} फ़ाइल की सामग्री को डीकोड करने में सक्षम नहीं था।",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} वर्तमान में UTF-16 एन्कोडेड टेक्स्ट फ़ाइलों का समर्थन नहीं करता है।",
  "FILE_EXISTS_ERR": "फ़ाइल या निर्देशिका पहले से मौजूद है।",
  "FILE": "फ़ाइल",
  "FILE_TITLE": "फ़ाइल",
  "DIRECTORY": "निर्देशिका",
  "DIRECTORY_TITLE": "निर्देशिका",
  "DIRECTORY_NAMES_LEDE": "निर्देशिका नाम",
  "FILENAMES_LEDE": "फ़ाइल नाम",
  "FILENAME": "फ़ाइल का नाम",
  "DIRECTORY_NAME": "निर्देशिका का नाम",
  "ERROR_LOADING_PROJECT": "प्रोजेक्ट लोड करने में त्रुटि",
  "OPEN_DIALOG_ERROR": "फ़ाइल खोलें संवाद दिखाते समय कोई त्रुटि उत्पन्न हुई। (त्रुटि {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "निर्देशिका <span class='dialog-filename'>{0}</span> को लोड करने का प्रयास करते समय एक त्रुटि उत्पन्न हुई। (त्रुटि {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "निर्देशिका <span class='dialog-filename'>{0}</span> की सामग्री को पढ़ते समय एक त्रुटि उत्पन्न हुई। (त्रुटि {1})",
  "ERROR_OPENING_FILE_TITLE": "फ़ाइल खोलने में त्रुटि",
  "ERROR_OPENING_FILE": "फ़ाइल को खोलने का प्रयास करते समय एक त्रुटि हुई <span class='dialog-filename'>{0}</span> . {1}",
  "ERROR_OPENING_FILES": "निम्न फ़ाइलें खोलने का प्रयास करते समय कोई त्रुटि उत्पन्न हुई:",
  "ERROR_RELOADING_FILE_TITLE": "डिस्क से परिवर्तन पुनः लोड करने में त्रुटि",
  "ERROR_RELOADING_FILE": "फ़ाइल <span class='dialog-filename'>{0}</span> को पुनः लोड करने का प्रयास करते समय एक त्रुटि उत्पन्न हुई। {1}",
  "ERROR_SAVING_FILE_TITLE": "फ़ाइल सहेजने में त्रुटि",
  "ERROR_SAVING_FILE": "फ़ाइल को सहेजने का प्रयास करते समय एक त्रुटि हुई <span class='dialog-filename'>{0}</span> . {1}",
  "ERROR_RENAMING_FILE_TITLE": "नाम बदलने में त्रुटि {0}",
  "ERROR_RENAMING_FILE": "{2} <span class='dialog-filename'>{0}</span> का नाम बदलने का प्रयास करते समय एक त्रुटि उत्पन्न हुई। {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "फ़ाइल या निर्देशिका वर्तमान में खोले गए प्रोजेक्ट का हिस्सा नहीं है। दुर्भाग्य से, इस बिंदु पर केवल प्रोजेक्ट फ़ाइलों का नाम बदला जा सकता है।",
  "ERROR_MOVING_FILE_TITLE": "स्थानांतरित करने में त्रुटि {0}",
  "ERROR_MOVING_FILE": "{2} <span class='dialog-filename'>{0}</span> को स्थानांतरित करने का प्रयास करते समय एक त्रुटि उत्पन्न हुई। {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "फ़ाइल/फ़ोल्डर को स्थानांतरित नहीं किया जा सकता, क्योंकि वे वर्तमान प्रोजेक्ट का हिस्सा नहीं हैं।",
  "ERROR_DELETING_FILE_TITLE": "{0} को हटाने में त्रुटि",
  "ERROR_DELETING_FILE": "{2} <span class='dialog-filename'>{0}</span> को हटाने का प्रयास करते समय एक त्रुटि उत्पन्न हुई। {1}",
  "INVALID_FILENAME_TITLE": "अमान्य {0}",
  "CANNOT_PASTE_TITLE": "चिपकाया नहीं जा सकता {0}",
  "CANNOT_DOWNLOAD_TITLE": "{0} डाउनलोड नहीं कर सकता",
  "ERR_TYPE_DOWNLOAD_FAILED": "<span class='dialog-filename'>{0}</span> को डाउनलोड करते समय एक त्रुटि हुई",
  "ERR_TYPE_PASTE_FAILED": "<span class='dialog-filename'>{0}</span> से <span class='dialog-filename'>{1}</span> को चिपकाते समय एक त्रुटि हुई",
  "CANNOT_DUPLICATE_TITLE": "नकल नहीं कर सकते",
  "ERR_TYPE_DUPLICATE_FAILED": "<span class='dialog-filename'>{0}</span> की नकल करते समय एक त्रुटि हुई",
  "INVALID_FILENAME_MESSAGE": "{0} किसी भी सिस्टम आरक्षित शब्दों का उपयोग नहीं कर सकता, बिंदुओं (.) के साथ समाप्त हो सकता है या निम्न में से किसी भी वर्ण का उपयोग नहीं कर सकता: <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "<span class='dialog-filename'>{0}</span> नाम की फ़ाइल या निर्देशिका पहले से मौजूद है।",
  "ERROR_CREATING_FILE_TITLE": "बनाने में त्रुटि {0}",
  "ERROR_CREATING_FILE": "{0} <span class='dialog-filename'>{1}</span> बनाने का प्रयास करते समय एक त्रुटि उत्पन्न हुई। {2}",
  "ERROR_MIXED_DRAGDROP": "एक ही समय में अन्य फाइलों को खोलने के रूप में एक फ़ोल्डर नहीं खोल सकता।",
  "ERROR_KEYMAP_TITLE": "उपयोगकर्ता कुंजी मानचित्र पढ़ने में त्रुटि",
  "ERROR_KEYMAP_CORRUPT": "आपकी मुख्य मानचित्र फ़ाइल मान्य JSON नहीं है। फ़ाइल खोली जाएगी ताकि आप प्रारूप को सही कर सकें।",
  "ERROR_LOADING_KEYMAP": "आपकी मुख्य मानचित्र फ़ाइल एक मान्य UTF-8 एन्कोडेड टेक्स्ट फ़ाइल नहीं है और इसे लोड नहीं किया जा सकता",
  "ERROR_RESTRICTED_COMMANDS": "आप इन आदेशों के लिए शॉर्टकट पुन: असाइन नहीं कर सकते: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "आप इन शॉर्टकट को पुन: असाइन नहीं कर सकते: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "आप इन आदेशों के लिए अनेक शॉर्टकट पुन: असाइन कर रहे हैं: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "आपके पास इन शॉर्टकट्स की अनेक बाइंडिंग हैं: {0}",
  "ERROR_INVALID_SHORTCUTS": "ये शॉर्टकट अमान्य हैं: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "आप गैर-मौजूद आदेशों के लिए शॉर्टकट निर्दिष्ट कर रहे हैं: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "वरीयताएँ पढ़ने में त्रुटि",
  "ERROR_PREFS_CORRUPT": "आपकी वरीयता फ़ाइल मान्य JSON नहीं है। फ़ाइल खोली जाएगी ताकि आप प्रारूप को सही कर सकें। परिवर्तनों को प्रभावी करने के लिए आपको {APP_NAME} को फिर से शुरू करना होगा।",
  "ERROR_PROJ_PREFS_CORRUPT": "आपकी परियोजना वरीयता फ़ाइल मान्य JSON नहीं है। फ़ाइल खोली जाएगी ताकि आप प्रारूप को सही कर सकें। परिवर्तनों को प्रभावी करने के लिए आपको प्रोजेक्ट को फिर से लोड करना होगा।",
  "ERROR_IN_BROWSER_TITLE": "उफ़! {APP_NAME} अभी तक ब्राउज़र में नहीं चलता है।",
  "ERROR_IN_BROWSER": "{APP_NAME} HTML में बनाया गया है, लेकिन अभी यह एक डेस्कटॉप ऐप के रूप में चलता है ताकि आप इसका उपयोग स्थानीय फ़ाइलों को संपादित करने के लिए कर सकें। {APP_NAME} को चलाने के लिए कृपया <b>github.com/adobe/brackets-shell</b> रेपो में एप्लिकेशन शेल का उपयोग करें।",
  "ERROR_MAX_FILES_TITLE": "फ़ाइलों को अनुक्रमित करने में त्रुटि",
  "ERROR_MAX_FILES": "इस परियोजना में 30,000 से अधिक फाइलें हैं। कई फाइलों में काम करने वाली सुविधाओं को अक्षम किया जा सकता है या ऐसा व्यवहार किया जा सकता है जैसे कि प्रोजेक्ट खाली है। <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>बड़ी परियोजनाओं के साथ काम करने के बारे में और पढ़ें</a> ।",
  "ERROR_LAUNCHING_BROWSER_TITLE": "ब्राउज़र लॉन्च करने में त्रुटि",
  "ERROR_CANT_FIND_CHROME": "गूगल क्रोम ब्राउज़र नहीं मिला। कृपया सुनिश्चित करें कि यह स्थापित है।",
  "ERROR_LAUNCHING_BROWSER": "ब्राउज़र लॉन्च करते समय एक त्रुटि हुई। (त्रुटि {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "लाइव पूर्वावलोकन त्रुटि",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "ब्राउज़र से जुड़ना",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "कनेक्ट करने के लिए लाइव पूर्वावलोकन के लिए, क्रोम को दूरस्थ डिबगिंग सक्षम के साथ फिर से लॉन्च करने की आवश्यकता है।<br /><br /> क्‍या आप Chrome को पुन: लॉन्‍च करना और दूरस्थ डीबगिंग सक्षम करना चाहते हैं?<br /><br />",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "लाइव पूर्वावलोकन पृष्ठ लोड करने में असमर्थ.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "सर्वर-साइड फ़ाइल के साथ लाइव पूर्वावलोकन लॉन्च करने के लिए, आपको इस प्रोजेक्ट के लिए एक आधार URL निर्दिष्ट करना होगा।",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "लाइव पूर्वावलोकन फ़ाइलों के लिए HTTP सर्वर प्रारंभ करने में त्रुटि. कृपया पुन: प्रयास करें।",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "अधिक जानकारी के लिए, <a href='{0}' title=\"{0}\">लाइव पूर्वावलोकन कनेक्शन त्रुटियों का समस्या निवारण</a> देखें।",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "सजीव पूर्वावलोकन",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "लाइव पूर्वावलोकन: कनेक्ट हो रहा है…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "लाइव पूर्वावलोकन: प्रारंभ किया जा रहा है...",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "लाइव पूर्वावलोकन डिस्कनेक्ट करें",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "सजीव पूर्वावलोकन",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "लाइव पूर्वावलोकन के लिए फ़ाइल का चयन करें",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "पृष्ठ पुनः लोड करें",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "लाइव पूर्वावलोकन हाइलाइट्स को टॉगल करें",
  "LIVE_DEV_CLICK_POPOUT": "नई विंडो में पॉपआउट लाइव पूर्वावलोकन",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "पूर्वावलोकन पृष्ठ को अनपिन करें पर पिन करें",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "लाइव पूर्वावलोकन (सिंटैक्स त्रुटि के कारण अपडेट नहीं हो रहा है)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "लाइव पूर्वावलोकन रद्द कर दिया गया क्योंकि ब्राउज़र के डेवलपर टूल खोले गए थे",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "लाइव पूर्वावलोकन रद्द कर दिया गया क्योंकि पृष्ठ ब्राउज़र में बंद था",
  "LIVE_DEV_NAVIGATED_AWAY": "लाइव पूर्वावलोकन रद्द कर दिया गया था क्योंकि ब्राउज़र एक ऐसे पृष्ठ पर नेविगेट करता है जो वर्तमान प्रोजेक्ट का हिस्सा नहीं है",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "किसी अज्ञात कारण से लाइव पूर्वावलोकन रद्द कर दिया गया था ({0})",
  "SAVE_CLOSE_TITLE": "परिवर्तनों को सुरक्षित करें",
  "SAVE_CLOSE_MESSAGE": "क्या आप दस्तावेज़ में किए गए परिवर्तनों को सहेजना चाहते हैं <span class='dialog-filename'>{0}</span> ?",
  "SAVE_CLOSE_MULTI_MESSAGE": "क्या आप अपने परिवर्तनों को निम्न फाइलों में सहेजना चाहते हैं?",
  "EXT_MODIFIED_TITLE": "बाहरी परिवर्तन",
  "CONFIRM_DELETE_TITLE": "हटाने की पुष्टि करें",
  "CONFIRM_FILE_DELETE": "क्या आप वाकई फ़ाइल <span class='dialog-filename'>{0}</span> को हटाना चाहते हैं?",
  "CONFIRM_FOLDER_DELETE": "क्या आप वाकई <span class='dialog-filename'>{0}</span> फ़ोल्डर को हटाना चाहते हैं?",
  "FILE_DELETED_TITLE": "फ़ाइल हटाई गई",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> को {APP_NAME} के बाहर डिस्क पर संशोधित किया गया है।<br /><br /> क्या आप फ़ाइल को सहेजना और उन परिवर्तनों को अधिलेखित करना चाहते हैं?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> को {APP_NAME} के बाहर डिस्क पर संशोधित किया गया है, लेकिन {APP_NAME} में भी सहेजे नहीं गए परिवर्तन हैं।<br /><br /> आप कौन सा संस्करण रखना चाहते हैं?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> को {APP_NAME} के बाहर डिस्क पर हटा दिया गया है, लेकिन {APP_NAME} में सहेजे नहीं गए परिवर्तन हैं।<br /><br /> क्या आप अपने परिवर्तन रखना चाहते हैं?",
  "WINDOW_UNLOAD_WARNING": "क्या आप वाकई किसी भिन्न URL पर नेविगेट करना चाहते हैं और ब्रैकेट छोड़ना चाहते हैं?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "आपके पास सहेजे नहीं गए परिवर्तन हैं! क्या आप वाकई किसी भिन्न URL पर नेविगेट करना चाहते हैं और ब्रैकेट छोड़ना चाहते हैं?",
  "DONE": "पूर्ण",
  "OK": "ठीक है",
  "CANCEL": "रद्द करना",
  "DONT_SAVE": "सेव न करें",
  "SAVE": "बचाना",
  "SAVE_AS": "के रूप रक्षित करें…",
  "SAVE_AND_OVERWRITE": "ओवरराइट",
  "DELETE": "मिटाना",
  "BUTTON_YES": "हाँ",
  "BUTTON_NO": "नहीं",
  "FIND_MATCH_INDEX": "{1} में से {0}",
  "FIND_NO_RESULTS": "कोई परिणाम नहीं",
  "FIND_QUERY_PLACEHOLDER": "पाना…",
  "FIND_HISTORY_MAX_COUNT": "खोज इतिहास में खोज मदों की अधिकतम संख्या",
  "REPLACE_PLACEHOLDER": "के साथ बदलें…",
  "BUTTON_REPLACE_ALL": "सबको बदली करें",
  "BUTTON_REPLACE_BATCH": "बैच…",
  "BUTTON_REPLACE_ALL_IN_FILES": "बदलने के…",
  "BUTTON_REPLACE": "बदलने के",
  "BUTTON_NEXT": "मैं",
  "BUTTON_PREV": "मैं",
  "BUTTON_NEXT_HINT": "अगला मिलान",
  "BUTTON_PREV_HINT": "पिछला मैच",
  "BUTTON_CASESENSITIVE_HINT": "माचिस की डिबिया",
  "BUTTON_REGEXP_HINT": "नियमित अभिव्यक्ति",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "पूर्ववत किए बिना बदलें",
  "REPLACE_WITHOUT_UNDO_WARNING": "क्योंकि {0} से अधिक फ़ाइलों को बदलने की आवश्यकता है, {APP_NAME} डिस्क पर न खोली गई फ़ाइलों को संशोधित करेगा।<br /> आप उन फ़ाइलों में प्रतिस्थापन पूर्ववत नहीं कर पाएंगे।",
  "BUTTON_REPLACE_WITHOUT_UNDO": "पूर्ववत किए बिना बदलें",
  "OPEN_FILE": "खुली फाइल",
  "SAVE_FILE_AS": "फाइल सुरक्षित करें",
  "CHOOSE_FOLDER": "एक फ़ोल्डर चुनें",
  "RELEASE_NOTES": "रिलीज नोट्स",
  "NO_UPDATE_TITLE": "आप अप टू डेट हैं!",
  "NO_UPDATE_MESSAGE": "आप {APP_NAME} का नवीनतम संस्करण चला रहे हैं।",
  "FIND_REPLACE_TITLE_LABEL": "बदलने के",
  "FIND_REPLACE_TITLE_WITH": "साथ",
  "FIND_TITLE_LABEL": "मिल गया",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} {3} में",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "में <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "परियोजना में",
  "FIND_IN_FILES_ZERO_FILES": "फ़िल्टर में सभी फ़ाइलें शामिल नहीं हैं {0}",
  "FIND_IN_FILES_FILE": "फ़ाइल",
  "FIND_IN_FILES_FILES": "फ़ाइलें",
  "FIND_IN_FILES_MATCH": "मिलान",
  "FIND_IN_FILES_MATCHES": "माचिस",
  "FIND_IN_FILES_MORE_THAN": "ऊपर",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Ctrl/Cmd सभी को विस्तृत/संक्षिप्त करने के लिए क्लिक करें",
  "FIND_IN_FILES_INDEXING": "त्वरित खोज के लिए अनुक्रमणित किया जा रहा है…",
  "FIND_IN_FILES_INDEXING_PROGRESS": "तत्काल खोज के लिए {1} फाइलों में से {0} को अनुक्रमित किया जा रहा है…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "त्रुटियों को बदलें",
  "REPLACE_IN_FILES_ERRORS": "निम्न फ़ाइलें संशोधित नहीं की गईं क्योंकि वे खोज के बाद बदल गईं या लिखी नहीं जा सकीं।",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "अद्यतन जानकारी प्राप्त करने में त्रुटि",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "सर्वर से नवीनतम अद्यतन जानकारी प्राप्त करने में एक समस्या थी। कृपया सुनिश्चित करें कि आप इंटरनेट से कनेक्ट हैं और पुनः प्रयास करें।",
  "NEW_FILE_FILTER": "नया बहिष्करण सेट…",
  "CLEAR_FILE_FILTER": "फ़ाइलें बहिष्कृत न करें",
  "NO_FILE_FILTER": "कोई फ़ाइल बहिष्कृत नहीं",
  "EXCLUDE_FILE_FILTER": "बहिष्कृत करें {0}",
  "EDIT_FILE_FILTER": "संपादन करना…",
  "FILE_FILTER_DIALOG": "बहिष्करण सेट संपादित करें",
  "FILE_FILTER_INSTRUCTIONS": "निम्नलिखित में से किसी भी स्ट्रिंग / सबस्ट्रिंग या <a href='{0}' title=\"{0}\">वाइल्डकार्ड</a> से मेल खाने वाली फ़ाइलों और फ़ोल्डरों को बाहर करें। प्रत्येक स्ट्रिंग को एक नई लाइन पर दर्ज करें।",
  "FILTER_NAME_PLACEHOLDER": "इस बहिष्करण सेट को नाम दें (वैकल्पिक)",
  "FILTER_NAME_REMAINING": "{0} वर्ण शेष",
  "FILE_FILTER_CLIPPED_SUFFIX": "और {0} और",
  "FILTER_COUNTING_FILES": "फ़ाइलों की गणना की जा रही है…",
  "FILTER_FILE_COUNT": "{1} में से {0} फ़ाइलों को {2} की अनुमति देता है",
  "FILTER_FILE_COUNT_ALL": "सभी {0} फ़ाइलों को {1} की अनुमति देता है",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "वर्तमान कर्सर स्थिति के लिए कोई त्वरित संपादन उपलब्ध नहीं है",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "CSS क्विक एडिट: कर्सर को सिंगल क्लास के नाम पर रखें",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "सीएसएस त्वरित संपादन: अपूर्ण वर्ग विशेषता",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "सीएसएस त्वरित संपादन: अपूर्ण आईडी विशेषता",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "CSS क्विक एडिट: कर्सर को टैग, क्लास या आईडी में रखें",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "CSS टाइमिंग फ़ंक्शन त्वरित संपादन: अमान्य सिंटैक्स",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "जेएस त्वरित संपादन: कर्सर को फ़ंक्शन नाम में रखें",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "वर्तमान कर्सर स्थिति के लिए कोई त्वरित दस्तावेज़ उपलब्ध नहीं है",
  "PROJECT_LOADING": "लोड हो रहा है…",
  "UNTITLED": "शीर्षकहीन",
  "WORKING_FILES": "कार्य फ़ाइलें",
  "TOP": "ऊपर",
  "BOTTOM": "नीचे",
  "LEFT": "बाएं",
  "RIGHT": "सही",
  "CMD_SPLITVIEW_NONE": "विभाजित नहीं",
  "CMD_SPLITVIEW_VERTICAL": "लंबवत विभाजन",
  "CMD_SPLITVIEW_HORIZONTAL": "क्षैतिज विभाजन",
  "SPLITVIEW_MENU_TOOLTIP": "संपादक को लंबवत या क्षैतिज रूप से विभाजित करें",
  "GEAR_MENU_TOOLTIP": "कार्य सेट कॉन्फ़िगर करें",
  "SPLITVIEW_INFO_TITLE": "पहले से ही खुला",
  "SPLITVIEW_MULTIPANE_WARNING": "फ़ाइल पहले से ही दूसरे फलक में खुली है। {APP_NAME} जल्द ही एक ही फ़ाइल को एक से अधिक फलकों में खोलने का समर्थन करेगा। तब तक, फ़ाइल उस फलक में दिखाई देगी जिसमें वह पहले से खुली है।<br /><br /> (आप इस संदेश को केवल एक बार देखेंगे।)",
  "STATUSBAR_CURSOR_POSITION": "लाइन {0}, कॉलम {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — चयनित {0} कॉलम",
  "STATUSBAR_SELECTION_CH_PLURAL": " — चयनित {0} कॉलम",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — चयनित {0} लाइन",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — चयनित {0} पंक्तियाँ",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} चयन",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "इंडेंटेशन को रिक्त स्थान पर स्विच करने के लिए क्लिक करें",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "इंडेंटेशन को टैब में बदलने के लिए क्लिक करें",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "इंडेंट करते समय उपयोग किए गए रिक्त स्थान की संख्या बदलने के लिए क्लिक करें",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "टैब वर्ण चौड़ाई बदलने के लिए क्लिक करें",
  "STATUSBAR_SPACES": "रिक्त स्थान:",
  "STATUSBAR_TAB_SIZE": "टैब आकार:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} रेखा",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} पंक्तियाँ",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "एक्सटेंशन अक्षम",
  "STATUSBAR_INSERT": "इन की",
  "STATUSBAR_OVERWRITE": "ओवीआर",
  "STATUSBAR_INSOVR_TOOLTIP": "इंसर्ट (INS) और ओवरराइट (OVR) मोड के बीच कर्सर को टॉगल करने के लिए क्लिक करें",
  "STATUSBAR_LANG_TOOLTIP": "फ़ाइल प्रकार बदलने के लिए क्लिक करें",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. रिपोर्ट पैनल टॉगल करने के लिए क्लिक करें।",
  "STATUSBAR_DEFAULT_LANG": "(चूक)",
  "STATUSBAR_SET_DEFAULT_LANG": ".{0} फ़ाइलें . के लिए डिफ़ॉल्ट के रूप में सेट करें",
  "STATUSBAR_ENCODING_TOOLTIP": "एन्कोडिंग का चयन करें",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} समस्याएं",
  "SINGLE_ERROR": "1 {0} समस्या",
  "MULTIPLE_ERRORS": "{1} {0} समस्याएं",
  "NO_ERRORS": "कोई {0} समस्या नहीं मिली - अच्छा काम!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "कोई समस्या नहीं मिली - अच्छा काम!",
  "LINT_DISABLED": "अस्तर अक्षम है",
  "NO_LINT_AVAILABLE": "{0} के लिए कोई लिंटर उपलब्ध नहीं है",
  "NOTHING_TO_LINT": "लिंट करने के लिए कुछ भी नहीं",
  "LINTER_TIMED_OUT": "{1} ms . की प्रतीक्षा के बाद {0} का समय समाप्त हो गया है",
  "LINTER_FAILED": "{0} त्रुटि के साथ समाप्त: {1}",
  "FILE_MENU": "फ़ाइल",
  "CMD_FILE_NEW_UNTITLED": "नया",
  "CMD_FILE_NEW": "नई फ़ाइल",
  "CMD_FILE_DUPLICATE": "डुप्लिकेट",
  "CMD_FILE_DOWNLOAD_PROJECT": "प्रोजेक्ट डाउनलोड करें",
  "CMD_FILE_DOWNLOAD": "डाउनलोड",
  "CMD_FILE_CUT": "कट गया",
  "CMD_FILE_COPY": "प्रतिलिपि",
  "CMD_FILE_COPY_PATH": "कॉपी पथ",
  "CMD_FILE_PASTE": "पेस्ट करें",
  "CMD_PROJECT_NEW": "नया काम",
  "CMD_FILE_NEW_FOLDER": "नया फोल्डर",
  "CMD_FILE_OPEN": "खुला हुआ…",
  "CMD_RECENT_FILES_OPEN": "हाल हीं के फाइल…",
  "CMD_ADD_TO_WORKING_SET": "कार्य सेट के लिए खुला",
  "CMD_OPEN_DROPPED_FILES": "छोड़ी गई फ़ाइलें खोलें",
  "CMD_OPEN_FOLDER": "फोल्डर खोलें…",
  "CMD_FILE_CLOSE": "बंद करना",
  "CMD_FILE_CLOSE_ALL": "सब बंद करें",
  "CMD_FILE_CLOSE_LIST": "बंद सूची",
  "CMD_FILE_CLOSE_OTHERS": "दूसरों को बंद करें",
  "CMD_FILE_CLOSE_ABOVE": "ऊपर दूसरों को बंद करें",
  "CMD_FILE_CLOSE_BELOW": "दूसरों को नीचे बंद करें",
  "CMD_FILE_SAVE": "फाइल सुरक्षित करें",
  "CMD_FILE_SAVE_ALL": "सभी को सुरक्षित करें",
  "CMD_FILE_SAVE_AS": "के रूप रक्षित करें…",
  "CMD_LIVE_FILE_PREVIEW": "सजीव पूर्वावलोकन",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "प्रायोगिक लाइव पूर्वावलोकन सक्षम करें",
  "CMD_RELOAD_LIVE_PREVIEW": "फोर्स रीलोड लाइव पूर्वावलोकन",
  "CMD_PROJECT_SETTINGS": "प्रोजेक्ट सेटिंग…",
  "CMD_FILE_RENAME": "नाम बदलें",
  "CMD_FILE_DELETE": "मिटाना",
  "CMD_INSTALL_EXTENSION": "एक्सटेंशन इंस्टॉल करें…",
  "CMD_EXTENSION_MANAGER": "विस्तार प्रबंधक…",
  "CMD_FILE_REFRESH": "फ़ाइल ट्री ताज़ा करें",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "पहले फ़ोल्डरों को क्रमबद्ध करें",
  "CMD_QUIT": "छोड़ना",
  "CMD_EXIT": "बाहर निकलना",
  "EDIT_MENU": "संपादन करना",
  "CMD_UNDO": "पूर्ववत",
  "CMD_REDO": "फिर से करें",
  "CMD_CUT": "कट गया",
  "CMD_COPY": "प्रतिलिपि",
  "CMD_PASTE": "पेस्ट करें",
  "CMD_SELECT_ALL": "सभी का चयन करे",
  "CMD_SELECT_LINE": "लाइन का चयन करें",
  "CMD_SPLIT_SEL_INTO_LINES": "चयन को पंक्तियों में विभाजित करें",
  "CMD_ADD_CUR_TO_NEXT_LINE": "अगली पंक्ति में कर्सर जोड़ें",
  "CMD_ADD_CUR_TO_PREV_LINE": "पिछली पंक्ति में कर्सर जोड़ें",
  "CMD_INDENT": "मांगपत्र",
  "CMD_UNINDENT": "अज्ञात",
  "CMD_DUPLICATE": "डुप्लिकेट",
  "CMD_DELETE_LINES": "लाइन हटाएं",
  "CMD_COMMENT": "टॉगल लाइन टिप्पणी",
  "CMD_BLOCK_COMMENT": "टॉगल ब्लॉक टिप्पणी",
  "CMD_LINE_UP": "लाइन ऊपर ले जाएँ",
  "CMD_LINE_DOWN": "रेखा नीचे ले जाएँ",
  "CMD_OPEN_LINE_ABOVE": "ऊपर की रेखा खोलें",
  "CMD_OPEN_LINE_BELOW": "ओपन लाइन नीचे",
  "CMD_TOGGLE_CLOSE_BRACKETS": "ऑटो बंद ब्रेसिज़",
  "CMD_SHOW_CODE_HINTS": "कोड संकेत दिखाएं",
  "CMD_BEAUTIFY_CODE": "कोड सुशोभित करें",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "सहेजें के बाद कोड सुशोभित करें",
  "FIND_MENU": "पाना",
  "CMD_FIND": "पाना",
  "CMD_FIND_NEXT": "अगला ढूंढो",
  "CMD_FIND_PREVIOUS": "पिछला खोजें",
  "CMD_FIND_ALL_AND_SELECT": "सभी खोजें और चुनें",
  "CMD_ADD_NEXT_MATCH": "चयन में अगला मैच जोड़ें",
  "CMD_SKIP_CURRENT_MATCH": "छोड़ें और अगला मैच जोड़ें",
  "CMD_FIND_IN_FILES": "फाइलों में खोजें",
  "CMD_FIND_IN_SUBTREE": "में देखो…",
  "CMD_REPLACE": "बदलने के",
  "CMD_REPLACE_IN_FILES": "फाइलों में बदलें",
  "CMD_REPLACE_IN_SUBTREE": "में बदलें…",
  "VIEW_MENU": "राय",
  "CMD_HIDE_SIDEBAR": "किनारे की बाधा को हटाएं",
  "CMD_SHOW_SIDEBAR": "साइडबार दिखाएं",
  "CMD_TOGGLE_SIDEBAR": "साइडबार टॉगल करें",
  "CMD_TOGGLE_PANELS": "पैनल टॉगल करें",
  "CMD_TOGGLE_PURE_CODE": "कोई विकर्षण नहीं",
  "CMD_INCREASE_FONT_SIZE": "फ़ॉन्ट आकार बढ़ाएँ",
  "CMD_DECREASE_FONT_SIZE": "फ़ॉन्ट आकार घटाएं",
  "CMD_RESTORE_FONT_SIZE": "फ़ॉन्ट आकार पुनर्स्थापित करें",
  "CMD_SCROLL_LINE_UP": "स्क्रॉल लाइन अप",
  "CMD_SCROLL_LINE_DOWN": "स्क्रॉल लाइन डाउन",
  "CMD_TOGGLE_LINE_NUMBERS": "पंक्ति संख्याएँ",
  "CMD_TOGGLE_ACTIVE_LINE": "सक्रिय रेखा को हाइलाइट करें",
  "CMD_TOGGLE_WORD_WRAP": "वर्ड रैप",
  "CMD_LIVE_HIGHLIGHT": "लाइव पूर्वावलोकन हाइलाइट",
  "CMD_VIEW_TOGGLE_INSPECTION": "सहेजें पर लिंट फ़ाइलें",
  "CMD_WORKINGSET_SORT_BY_ADDED": "जोड़े गए के आधार पर छाँटें",
  "CMD_WORKINGSET_SORT_BY_NAME": "नाम द्वारा क्रमबद्ध करें",
  "CMD_WORKINGSET_SORT_BY_TYPE": "प्रकार के अनुसार छाँटें",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "स्वचालित सॉर्ट",
  "CMD_THEMES": "थीम…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "स्वचालित रूप से खोज बंद करें",
  "NAVIGATE_MENU": "नेविगेट",
  "CMD_QUICK_OPEN": "त्वरित खुला",
  "CMD_GOTO_LINE": "लाइन पर जाएं",
  "CMD_GOTO_DEFINITION": "त्वरित खोज परिभाषा",
  "CMD_GOTO_DEFINITION_PROJECT": "परियोजना में त्वरित खोज परिभाषा",
  "CMD_GOTO_FIRST_PROBLEM": "पहली समस्या पर जाएँ",
  "CMD_TOGGLE_QUICK_EDIT": "शीघ्र संपादित",
  "CMD_TOGGLE_QUICK_DOCS": "त्वरित डॉक्स",
  "CMD_QUICK_EDIT_PREV_MATCH": "पिछला मैच",
  "CMD_QUICK_EDIT_NEXT_MATCH": "अगला मिलान",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "नए नियम",
  "CMD_NEXT_DOC": "अगला दस्तावेज़",
  "CMD_PREV_DOC": "पिछला दस्तावेज़",
  "CMD_NAVIGATE_BACKWARD": "पीछे की ओर नेविगेट करें",
  "CMD_NAVIGATE_FORWARD": "आगे नेविगेट करें",
  "CMD_NEXT_DOC_LIST_ORDER": "सूची में अगला दस्तावेज़",
  "CMD_PREV_DOC_LIST_ORDER": "सूची में पिछला दस्तावेज़",
  "CMD_SHOW_IN_TREE": "फ़ाइल ट्री में दिखाएँ",
  "CMD_SHOW_IN_EXPLORER": "एक्सप्लोरर में शो",
  "CMD_SHOW_IN_FINDER": "फ़ाइंडर में दिखाएँ",
  "CMD_SHOW_IN_OS": "ओएस में दिखाएं",
  "CMD_SWITCH_PANE_FOCUS": "फलक फोकस स्विच करें",
  "CMD_OPEN_VFS": "वर्चुअल फाइल सिस्टम खोलें",
  "CMD_OPEN_VIRTUAL_SERVER": "वर्चुअल सर्वर खोलें",
  "HELP_MENU": "मदद करना",
  "CMD_CHECK_FOR_UPDATE": "अद्यतन के लिए जाँच",
  "CMD_HOW_TO_USE_BRACKETS": "{APP_NAME} का उपयोग कैसे करें",
  "CMD_SUPPORT": "{APP_NAME} सहायता",
  "CMD_SUGGEST": "एक विशेषता सुझाएं",
  "CMD_RELEASE_NOTES": "रिलीज नोट्स",
  "CMD_GET_INVOLVED": "उलझना",
  "CMD_SHOW_EXTENSIONS_FOLDER": "एक्सटेंशन फोल्डर दिखाएं",
  "CMD_HEALTH_DATA_STATISTICS": "स्वास्थ्य रपट",
  "CMD_HOMEPAGE": "{APP_NAME} होमपेज",
  "CMD_TWITTER": "{TWITTER_NAME} ट्विटर पर",
  "CMD_ABOUT": "{APP_TITLE} के बारे में",
  "CMD_OPEN_PREFERENCES": "वरीयताएँ फ़ाइल खोलें",
  "CMD_OPEN_KEYMAP": "उपयोगकर्ता कुंजी मानचित्र खोलें",
  "EXPERIMENTAL_BUILD": "प्रायोगिक निर्माण",
  "RELEASE_BUILD": "बनाना",
  "DEVELOPMENT_BUILD": "विकास का निर्माण",
  "PRERELEASE_BUILD": "पूर्व-रिलीज़ बिल्ड",
  "RELOAD_FROM_DISK": "डिस्क से पुनः लोड करें",
  "KEEP_CHANGES_IN_EDITOR": "संपादक में परिवर्तन रखें",
  "CLOSE_DONT_SAVE": "बंद करें (सहेजें नहीं)",
  "RELAUNCH_CHROME": "क्रोम को फिर से लॉन्च करें",
  "ABOUT": "के बारे में",
  "CLOSE": "बंद करना",
  "ABOUT_TEXT_LINE1": "रिलीज़ {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "टाइमस्टैम्प बनाएं:",
  "ABOUT_TEXT_LINE3": "तृतीय पक्ष पुस्तकालय जिनका हम उपयोग करते हैं - <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>लाइसेंस और विशेषताएँ</a> ।",
  "ABOUT_TEXT_LINE4": "दस्तावेज़ीकरण और स्रोत <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a> पर",
  "ABOUT_TEXT_LINE5": "द्वारा ❤ और जावास्क्रिप्ट के साथ बनाया गया:",
  "ABOUT_TEXT_LINE6": "बहुत से लोग (लेकिन हमें अभी उस डेटा को लोड करने में समस्या हो रही है)।",
  "ABOUT_TEXT_MDN_DOCS": "MDN डॉक्स और MDN ग्राफिकल लोगो को Creative Commons एट्रिब्यूशन लाइसेंस, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a> के तहत लाइसेंस दिया गया है।",
  "UPDATE_NOTIFICATION_TOOLTIP": "{APP_NAME} का एक नया निर्माण उपलब्ध है! जानकारी के लिए यहाँ क्लिक करें।",
  "UPDATE_AVAILABLE_TITLE": "उपलब्ध अद्यतन",
  "UPDATE_RELOAD_APP": "नवीनतम संस्करण प्राप्त करने के लिए कृपया सभी {APP_NAME} विंडो/टैब बंद करें और {APP_NAME} को फिर से खोलें।",
  "UPDATE_MESSAGE": "अरे, {APP_NAME} का एक नया निर्माण उपलब्ध है। यहां कुछ नई विशेषताएं दी गई हैं:",
  "GET_IT_NOW": "अब समझे!",
  "PROJECT_SETTINGS_TITLE": "इसके लिए प्रोजेक्ट सेटिंग: {0}",
  "PROJECT_SETTING_BASE_URL": "लाइव पूर्वावलोकन आधार URL",
  "PROJECT_SETTING_BASE_URL_HINT": "स्थानीय सर्वर का उपयोग करने के लिए, http://localhost:8000/ जैसे URL दर्ज करें।",
  "BASEURL_ERROR_INVALID_PROTOCOL": "{0} प्रोटोकॉल लाइव पूर्वावलोकन द्वारा समर्थित नहीं है&mdash;कृपया http: या https: का उपयोग करें।",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "आधार URL में \"{0}\" जैसे खोज पैरामीटर नहीं हो सकते.",
  "BASEURL_ERROR_HASH_DISALLOWED": "आधार URL में \"{0}\" जैसे हैश नहीं हो सकते।",
  "BASEURL_ERROR_INVALID_CHAR": "'{0}' जैसे विशेष वर्ण %-एन्कोडेड होने चाहिए।",
  "BASEURL_ERROR_UNKNOWN_ERROR": "आधार URL को पार्स करने में अज्ञात त्रुटि",
  "EMPTY_VIEW_HEADER": "<em>इस फलक में फ़ोकस होने पर फ़ाइल खोलें</em>",
  "FLIPVIEW_BTN_TOOLTIP": "इस दृश्य को {0} फलक . पर फ़्लिप करें",
  "CURRENT_THEME": "वर्तमान थीम",
  "USE_THEME_SCROLLBARS": "थीम स्क्रॉलबार का उपयोग करें",
  "FONT_SIZE": "फ़ॉन्ट आकार",
  "FONT_FAMILY": "फ़ॉन्ट परिवार",
  "THEMES_SETTINGS": "थीम सेटिंग्स",
  "THEMES_ERROR": "विषय-वस्तु त्रुटि",
  "THEMES_ERROR_CANNOT_APPLY": "किसी त्रुटि के कारण थीम लागू नहीं की जा सकी.",
  "BUTTON_NEW_RULE": "नए नियम",
  "INSTALL": "स्थापित करना",
  "APPLY": "आवेदन करना",
  "UPDATE": "अद्यतन",
  "REMOVE": "हटाना",
  "DISABLE": "बंद करना",
  "ENABLE": "सक्षम करना",
  "OVERWRITE": "ओवरराइट",
  "CANT_DROP_ZIP": "ज़िप फ़ाइलों को छोड़ने का समर्थन जल्द ही किया जाएगा...",
  "CANT_REMOVE_DEV": "\"देव\" फ़ोल्डर के एक्सटेंशन मैन्युअल रूप से हटाए जाने चाहिए।",
  "CANT_UPDATE": "अपडेट {APP_NAME} के इस वर्शन के साथ संगत नहीं है।",
  "CANT_UPDATE_DEV": "\"देव\" फ़ोल्डर में एक्सटेंशन स्वचालित रूप से अपडेट नहीं किए जा सकते।",
  "INSTALL_EXTENSION_TITLE": "एक्सटेंशन स्थापित करें",
  "UPDATE_EXTENSION_TITLE": "एक्सटेंशन अपडेट करें",
  "INSTALL_EXTENSION_LABEL": "एक्सटेंशन यूआरएल",
  "INSTALL_EXTENSION_HINT": "एक्सटेंशन की ज़िप फ़ाइल या GitHub रेपो का URL",
  "INSTALLING_FROM": "{0} से एक्सटेंशन इंस्टॉल किया जा रहा है…",
  "INSTALL_SUCCEEDED": "इंस्टॉलेशन सफल रहा!",
  "INSTALL_FAILED": "स्थापना विफल रही।",
  "CANCELING_INSTALL": "रद्द किया जा रहा है…",
  "CANCELING_HUNG": "इंस्टॉल को रद्द करने में लंबा समय लग रहा है। हो सकता है कि कोई आंतरिक त्रुटि हुई हो।",
  "INSTALL_CANCELED": "स्थापना रद्द।",
  "VIEW_COMPLETE_DESCRIPTION": "पूरा विवरण देखें",
  "VIEW_TRUNCATED_DESCRIPTION": "छोटा विवरण देखें",
  "SORT_EXTENSION_METHOD": "डाउनलोडकाउंट या पब्लिश्डडेट का उपयोग करके एक्सटेंशन को सॉर्ट करें",
  "INVALID_ZIP_FILE": "डाउनलोड की गई सामग्री एक मान्य ज़िप फ़ाइल नहीं है।",
  "MISSING_PACKAGE_JSON": "पैकेज में कोई package.json फ़ाइल नहीं है।",
  "INVALID_PACKAGE_JSON": "package.json फ़ाइल मान्य नहीं है (त्रुटि थी: {0})।",
  "MISSING_PACKAGE_NAME": "package.json फ़ाइल पैकेज नाम निर्दिष्ट नहीं करती है।",
  "BAD_PACKAGE_NAME": "{0} एक अमान्य पैकेज नाम है।",
  "MISSING_PACKAGE_VERSION": "package.json फ़ाइल पैकेज संस्करण निर्दिष्ट नहीं करती है।",
  "INVALID_VERSION_NUMBER": "पैकेज संस्करण संख्या ({0}) अमान्य है।",
  "INVALID_BRACKETS_VERSION": "{APP_NAME} संगतता स्ट्रिंग ({0}) अमान्य है।",
  "DISALLOWED_WORDS": "{0} फ़ील्ड में ({1}) शब्दों की अनुमति नहीं है।",
  "NPM_INSTALL_FAILED": "npm इंस्टाल कमांड विफल: {0}",
  "API_NOT_COMPATIBLE": "एक्सटेंशन {APP_NAME} के इस संस्करण के साथ संगत नहीं है। यह आपके अक्षम एक्सटेंशन फ़ोल्डर में स्थापित है।",
  "MISSING_MAIN": "पैकेज में कोई main.js फ़ाइल नहीं है।",
  "EXTENSION_ALREADY_INSTALLED": "इस पैकेज को स्थापित करने से पहले से इंस्टॉल किए गए एक्सटेंशन को अधिलेखित कर दिया जाएगा। पुराने एक्सटेंशन को ओवरराइट करें?",
  "EXTENSION_SAME_VERSION": "यह पैकेज वही संस्करण है जो वर्तमान में स्थापित है। मौजूदा स्थापना को अधिलेखित करें?",
  "EXTENSION_OLDER_VERSION": "यह पैकेज संस्करण {0} है जो वर्तमान में स्थापित ({1}) से पुराना है। मौजूदा स्थापना को अधिलेखित करें?",
  "DOWNLOAD_ID_IN_USE": "आंतरिक त्रुटि: डाउनलोड आईडी पहले से उपयोग में है।",
  "NO_SERVER_RESPONSE": "सर्वर से कनेक्ट नहीं हो पा रहा।",
  "BAD_HTTP_STATUS": "फ़ाइल सर्वर पर नहीं मिली (HTTP {0})।",
  "CANNOT_WRITE_TEMP": "डाउनलोड को अस्थायी फ़ाइल में सहेजने में असमर्थ।",
  "ERROR_LOADING": "एक्सटेंशन को प्रारंभ करते समय एक त्रुटि का सामना करना पड़ा।",
  "MALFORMED_URL": "यूआरएल अमान्य है। कृपया जांचें कि आपने इसे सही ढंग से दर्ज किया है।",
  "UNSUPPORTED_PROTOCOL": "URL एक http या https URL होना चाहिए।",
  "UNKNOWN_ERROR": "अज्ञात आंतरिक त्रुटि।",
  "EXTENSION_VERIFIED_PUBLISHER": "इस प्रकाशक ने {0} का स्वामित्व सत्यापित किया है",
  "EXTENSION_VERIFIED_SORT": "सत्यापित",
  "EXTENSION_STAR": "सितारा",
  "EXTENSION_STAR_SORT": "सितारा रेटिंग",
  "EXTENSION_MANAGER_TITLE": "विस्तार प्रबंधक",
  "EXTENSION_MANAGER_ERROR_LOAD": "एक्सटेंशन रजिस्ट्री तक पहुंचने में असमर्थ। बाद में पुन: प्रयास करें।",
  "INSTALL_EXTENSION_DRAG": ".zip को यहां खींचें या",
  "INSTALL_EXTENSION_DROP": "स्थापित करने के लिए .zip ड्रॉप करें",
  "INSTALL_EXTENSION_DROP_ERROR": "निम्नलिखित त्रुटियों के कारण स्थापित/अद्यतन निरस्त किया गया:",
  "INSTALL_FROM_URL": "URL से इंस्टॉल करें…",
  "INSTALL_EXTENSION_VALIDATING": "मान्य किया जा रहा है…",
  "EXTENSION_AUTHOR": "लेखक",
  "EXTENSION_DATE": "दिनांक",
  "EXTENSION_INCOMPATIBLE_NEWER": "इस एक्सटेंशन के लिए {APP_NAME} के नए संस्करण की आवश्यकता है।",
  "EXTENSION_INCOMPATIBLE_OLDER": "यह एक्सटेंशन वर्तमान में केवल {APP_NAME} के पुराने संस्करणों के साथ काम करता है।",
  "EXTENSION_DEFAULT_FEATURE_PRESENT": "आपको इस एक्सटेंशन की आवश्यकता नहीं हो सकती है। {APP_NAME} के पास यह सुविधा पहले से है.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "इस एक्सटेंशन के संस्करण {0} के लिए {APP_NAME} के नए संस्करण की आवश्यकता है। लेकिन आप पुराने संस्करण {1} को स्थापित कर सकते हैं।",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "इस एक्सटेंशन का संस्करण {0} केवल {APP_NAME} के पुराने संस्करणों के साथ काम करता है। लेकिन आप पुराने संस्करण {1} को स्थापित कर सकते हैं।",
  "EXTENSION_NO_DESCRIPTION": "कोई विवरण नहीं",
  "EXTENSION_MORE_INFO": "और जानकारी…",
  "EXTENSION_ERROR": "एक्सटेंशन त्रुटि",
  "EXTENSION_KEYWORDS": "कीवर्ड",
  "EXTENSION_TRANSLATED_USER_LANG": "आपकी सहित {0} भाषाओं में अनुवादित",
  "EXTENSION_TRANSLATED_GENERAL": "{0} भाषाओं में अनुवादित",
  "EXTENSION_TRANSLATED_LANGS": "इस एक्सटेंशन का इन भाषाओं में अनुवाद किया गया है: {0}",
  "EXTENSION_INSTALLED": "स्थापित",
  "EXTENSION_UPDATE_INSTALLED": "यह एक्सटेंशन अपडेट डाउनलोड कर लिया गया है और {APP_NAME} के पुनः लोड होने के बाद इंस्टॉल किया जाएगा।",
  "EXTENSION_SEARCH_PLACEHOLDER": "खोज",
  "EXTENSION_MORE_INFO_LINK": "अधिक",
  "EXTENSION_MANAGER_CREATE_EXTENSION": "+ एक्सटेंशन बनाएँ",
  "EXTENSION_MANAGER_CREATE_THEME": "+ थीम बनाएं",
  "BROWSE_EXTENSIONS": "एक्सटेंशन ब्राउज़ करें",
  "EXTENSION_MANAGER_REMOVE": "एक्सटेंशन हटाएं",
  "EXTENSION_MANAGER_REMOVE_ERROR": "एक या अधिक एक्सटेंशन निकालने में असमर्थ: {0}. {APP_NAME} अब भी पुनः लोड होगा।",
  "EXTENSION_MANAGER_UPDATE": "एक्सटेंशन अपडेट करें",
  "EXTENSION_MANAGER_UPDATE_ERROR": "एक या अधिक एक्सटेंशन अपडेट करने में असमर्थ: {0}. {APP_NAME} अब भी पुनः लोड होगा।",
  "EXTENSION_MANAGER_DISABLE": "एक्सटेंशन अक्षम करें",
  "EXTENSION_MANAGER_DISABLE_ERROR": "एक या अधिक एक्सटेंशन अक्षम करने में असमर्थ: {0}. {APP_NAME} अब भी पुनः लोड होगा।",
  "EXTENSION_MANAGER_THEMES_INFO": "<a class=\"theme_settings\">डिफ़ॉल्ट थीम चुनने</a> या अन्य थीम सेटिंग संशोधित करने के लिए, <a class=\"theme_settings\">यहां क्लिक करें</a> ।",
  "EXTENSION_MANAGER_THEMES_UNDO": "पिछली थीम पर वापस लौटें",
  "MARKED_FOR_REMOVAL": "हटाने के लिए चिह्नित",
  "UNDO_REMOVE": "पूर्ववत",
  "MARKED_FOR_UPDATE": "अद्यतन के लिए चिह्नित",
  "UNDO_UPDATE": "पूर्ववत",
  "MARKED_FOR_DISABLING": "अक्षम करने के लिए चिह्नित",
  "UNDO_DISABLE": "पूर्ववत",
  "CHANGE_AND_RELOAD_TITLE": "एक्सटेंशन बदलें",
  "CHANGE_AND_RELOAD_MESSAGE": "चिह्नित एक्सटेंशन को अपडेट करने, निकालने या अक्षम करने के लिए, {APP_NAME} को पुनः लोड करना होगा। आपको न सहेजे गए परिवर्तनों को सहेजने के लिए प्रेरित किया जाएगा।",
  "REMOVE_AND_RELOAD": "एक्सटेंशन निकालें और पुनः लोड करें",
  "CHANGE_AND_RELOAD": "एक्सटेंशन बदलें और पुनः लोड करें",
  "UPDATE_AND_RELOAD": "एक्सटेंशन अपडेट करें और पुनः लोड करें",
  "DISABLE_AND_RELOAD": "एक्सटेंशन अक्षम करें और पुनः लोड करें",
  "PROCESSING_EXTENSIONS": "संसाधन एक्सटेंशन परिवर्तन…",
  "EXTENSION_NOT_INSTALLED": "एक्सटेंशन {0} को हटाया नहीं जा सका क्योंकि यह इंस्टॉल नहीं किया गया था।",
  "NO_EXTENSIONS": "अभी तक कोई एक्सटेंशन इंस्टॉल नहीं किया गया है।<br> आरंभ करने के लिए ऊपर उपलब्ध टैब पर क्लिक करें।",
  "NO_EXTENSION_MATCHES": "कोई भी एक्सटेंशन आपकी खोज से मेल नहीं खाता.",
  "REGISTRY_SANITY_CHECK_WARNING": "नोट: ये एक्सटेंशन स्वयं {APP_NAME} के अलावा अन्य लेखकों से आ सकते हैं। एक्सटेंशन की समीक्षा नहीं की जाती है और उनके पास पूर्ण स्थानीय विशेषाधिकार होते हैं। किसी अज्ञात स्रोत से एक्सटेंशन इंस्टॉल करते समय सावधान रहें।",
  "EXTENSIONS_INSTALLED_TITLE": "स्थापित",
  "EXTENSIONS_DEFAULT_TITLE": "चूक",
  "EXTENSIONS_AVAILABLE_TITLE": "उपलब्ध",
  "EXTENSIONS_THEMES_TITLE": "विषयों",
  "EXTENSIONS_UPDATES_TITLE": "अपडेट",
  "EXTENSIONS_LAST_UPDATED": "आखरी अपडेट",
  "EXTENSIONS_DOWNLOADS": "डाउनलोड",
  "INLINE_EDITOR_NO_MATCHES": "कोई मैच उपलब्ध नहीं है।",
  "INLINE_EDITOR_HIDDEN_MATCHES": "सभी मैच ध्वस्त हो गए हैं। मैच देखने के लिए दाईं ओर सूचीबद्ध फाइलों का विस्तार करें।",
  "CSS_QUICK_EDIT_NO_MATCHES": "आपके चयन से मेल खाने वाला कोई मौजूदा CSS नियम नहीं है।<br> एक बनाने के लिए &quot;नया नियम&quot; पर क्लिक करें।",
  "CSS_QUICK_EDIT_NO_STYLESHEETS": "आपके प्रोजेक्ट में कोई स्टाइलशीट नहीं है।<br> CSS नियम जोड़ने के लिए एक बनाएँ।",
  "IMAGE_VIEWER_LARGEST_ICON": "विशालतम",
  "UNIT_PIXELS": "पिक्सल",
  "DEBUG_MENU": "डिबग",
  "ERRORS": "त्रुटियाँ",
  "CMD_SHOW_DEV_TOOLS": "डेवलपर टूल दिखाएं",
  "CMD_REFRESH_WINDOW": "एक्सटेंशन के साथ पुनः लोड करें",
  "CMD_LOAD_CURRENT_EXTENSION": "एक्सटेंशन के रूप में प्रोजेक्ट लोड करें",
  "CMD_RELOAD_CURRENT_EXTENSION": "एक्सटेंशन के रूप में प्रोजेक्ट को रीलोड करें",
  "CMD_UNLOAD_CURRENT_EXTENSION": "एक्सटेंशन के रूप में प्रोजेक्ट को अनलोड करें",
  "CMD_RELOAD_WITHOUT_USER_EXTS": "एक्सटेंशन के बिना पुनः लोड करें",
  "CMD_NEW_BRACKETS_WINDOW": "नई {APP_NAME} विंडो",
  "CMD_LAUNCH_SCRIPT_MAC": "कमांड लाइन शॉर्टकट स्थापित करें",
  "CMD_SWITCH_LANGUAGE": "भाषा बदलें",
  "CMD_RUN_UNIT_TESTS": "परीक्षण चलाएं",
  "CMD_SHOW_PERF_DATA": "प्रदर्शन डेटा दिखाएं",
  "CMD_ENABLE_LOGGING": "विस्तृत लॉग सक्षम करें",
  "CMD_ENABLE_LIVE_PREVIEW_LOGS": "लाइव पूर्वावलोकन लॉग",
  "CMD_OPEN_BRACKETS_SOURCE": "{APP_NAME} स्रोत खोलें",
  "CREATING_LAUNCH_SCRIPT_TITLE": "{APP_NAME} कमांड लाइन शॉर्टकट",
  "ERROR_CREATING_LAUNCH_SCRIPT": "कमांड लाइन शॉर्टकट स्थापित करते समय एक त्रुटि हुई। कृपया <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>इन समस्या निवारण सुझावों</a> का प्रयास करें।<br/><br/> कारण: {0}",
  "ERROR_CLTOOLS_RMFAILED": "मौजूदा <code>/usr/local/bin/brackets</code> सिमलिंक को हटाने में असमर्थ।",
  "ERROR_CLTOOLS_MKDIRFAILED": "<code>/usr/local/bin</code> निर्देशिका बनाने में असमर्थ।",
  "ERROR_CLTOOLS_LNFAILED": "<code>/usr/local/bin/brackets</code> सिमलिंक बनाने में असमर्थ।",
  "ERROR_CLTOOLS_SERVFAILED": "आंतरिक त्रुटि।",
  "ERROR_CLTOOLS_NOTSUPPORTED": "इस OS पर कमांड लाइन शॉर्टकट समर्थित नहीं है।",
  "LAUNCH_SCRIPT_CREATE_SUCCESS": "सफलता! अब आप कमांड लाइन से {APP_NAME} को आसानी से लॉन्च कर सकते हैं: किसी फ़ाइल को खोलने के लिए <code>brackets myFile.txt</code> <code>brackets myFolder</code> या प्रोजेक्ट स्विच करने के लिए myFolder को ब्रैकेट करें।<br/><br/> कमांड लाइन से {APP_NAME} का उपयोग करने के बारे में <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>और जानें</a> ।",
  "ERROR_LOADING_EXTENSION": "एक्सटेंशन लोड करने में त्रुटि",
  "ERROR_NO_EXTENSION_PACKAGE": "<code>package.json</code> फ़ाइल वर्तमान प्रोजेक्ट में नहीं मिली। क्या मौजूदा प्रोजेक्ट एक मान्य {APP_NAME} एक्सटेंशन है?</br> अधिक विवरण के लिए <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>यह लिंक</a> देखें।",
  "ERROR_INVALID_EXTENSION_PACKAGE": "<code>package.json</code> फ़ाइल अमान्य JSON है।</br> अधिक विवरण के लिए <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>यह लिंक</a> देखें।",
  "ERROR_INVALID_EXTENSION_PACKAGE_FIELDS": "आवश्यक फ़ील्ड <code>package.json</code> में गायब हैं: [{0}]</br> अधिक विवरण के लिए <a href='https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes'>यह लिंक</a> देखें।",
  "LANGUAGE_TITLE": "भाषा बदलें",
  "LANGUAGE_MESSAGE": "भाषा:",
  "LANGUAGE_SUBMIT": "{APP_NAME} को फिर से लोड करें",
  "LANGUAGE_CANCEL": "रद्द करना",
  "LANGUAGE_SYSTEM_DEFAULT": "प्रणालीगत चूक",
  "HEALTH_DATA_NOTIFICATION": "स्वास्थ्य रिपोर्ट वरीयताएँ",
  "HEALTH_FIRST_POPUP_TITLE": "{APP_NAME} स्वास्थ्य रिपोर्ट",
  "HEALTH_DATA_DO_TRACK": "मैं {APP_NAME} का उपयोग कैसे करता हूं, इस बारे में छद्म नाम से जानकारी साझा करें",
  "HEALTH_DATA_NOTIFICATION_MESSAGE": "{APP_NAME} को बेहतर बनाने के लिए, हम समय-समय पर सीमित नाम वाले आंकड़े और त्रुटि रिपोर्ट <strong>phcode.dev</strong> को भेजते हैं कि आप {APP_NAME} का उपयोग कैसे करते हैं। यह जा