/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "Zadani jezik",
  "PROJECT_BUSY": "Projektne operacije u tijeku",
  "DUPLICATING": "Umnožavanje {0}",
  "MOVING": "Premještanje {0}",
  "COPYING": "Kopiranje {0}",
  "DELETING": "Brisanje {0}",
  "RENAMING": "Preimenovanje",
  "GENERIC_ERROR": "(greška {0})",
  "NOT_FOUND_ERR": "Nepostojeća datoteka.",
  "NOT_READABLE_ERR": "Datoteka ne može biti učitana.",
  "EXCEEDS_MAX_FILE_SIZE": "Datoteke veće od {0} MB ne mogu se otvoriti u {APP_NAME}.",
  "NO_MODIFICATION_ALLOWED_ERR": "Ciljana mapa ne može biti izmijenjena.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Trenutne ovlasti vam ne dozvoljavaju kreiranje izmjena.",
  "CONTENTS_MODIFIED_ERR": "Datoteka je bila izmjenjena izvan {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "Nepoznati format kodiranja",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} nije uspjela kodirati sadržaj datoteke.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} nije uspjela dekodirati sadržaj datoteke.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} trenutno ne podržava tekstualne datoteke kodirane UTF-16.",
  "FILE_EXISTS_ERR": "Datoteka ili mapa već postoji.",
  "FILE": "datoteci",
  "FILE_TITLE": "Datoteka",
  "DIRECTORY": "Direktorij",
  "DIRECTORY_TITLE": "Imenik",
  "DIRECTORY_NAMES_LEDE": "Imena imenika",
  "FILENAMES_LEDE": "Nazivi datoteka",
  "FILENAME": "Naziv datoteke",
  "DIRECTORY_NAME": "Naziv imenika",
  "ERROR_LOADING_PROJECT": "Greška pri učitavanju projekta",
  "OPEN_DIALOG_ERROR": "Došlo je do greške prilikom prikazivanja dijaloga za otvaranje datoteke. (error {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Došlo je do greške prilikom pokušaja da se učita direktorij <span class='dialog-filename'>{0}</span>. (error {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Došlo je do greške prilikom iščitavanja sadržaja direktorija <span class='dialog-filename'>{0}</span>. (error {1})",
  "ERROR_OPENING_FILE_TITLE": "Greška pri otvaranju datoteke",
  "ERROR_OPENING_FILE": "Došlo je do greške prilikom pokušaja da se otvori datoteka <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Došlo je do greške prilikom pokušaja da se otvore sljedeće datoteke:",
  "ERROR_RELOADING_FILE_TITLE": "Greška pri ponovom učitavanju izmjena sa diska",
  "ERROR_RELOADING_FILE": "Došlo je do greške prilikom pokušaja da se ponovo učita datoteka <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Greška pri spremanju datoteke",
  "ERROR_SAVING_FILE": "Došlo je do greške prilikom pokušaja da se sačuva datoteka <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Greška pri preimenovanju datoteke",
  "ERROR_RENAMING_FILE": "Došlo je do greške prilikom pokušaja da se preimenuje datoteka <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Datoteka ili direktorij nije dio trenutno otvorenog projekta. Nažalost, u ovom trenutku mogu se preimenovati samo datoteke projekta.",
  "ERROR_MOVING_FILE_TITLE": "Pogreška pri premještanju {0}",
  "ERROR_MOVING_FILE": "Došlo je do pogreške prilikom pokušaja premještanja {2} <span class='dialog-filename'>{0}</span> . {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Nije moguće premjestiti datoteku/mapu jer nisu dio trenutnog projekta.",
  "ERROR_DELETING_FILE_TITLE": "Greška pri brisanju datoteke",
  "ERROR_DELETING_FILE": "Došlo je do greške prilikom pokušaja da se obriše datoteka <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "Ime {0} nije valjano",
  "CANNOT_PASTE_TITLE": "Nije moguće zalijepiti {0}",
  "CANNOT_DOWNLOAD_TITLE": "Nije moguće preuzeti {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "Došlo je do pogreške prilikom preuzimanja <span class='dialog-filename'>{0}</span>",
  "ERR_TYPE_PASTE_FAILED": "Došlo je do pogreške prilikom lijepljenja <span class='dialog-filename'>{0}</span> u <span class='dialog-filename'>{1}</span>",
  "CANNOT_DUPLICATE_TITLE": "Nije moguće umnožiti",
  "ERR_TYPE_DUPLICATE_FAILED": "Došlo je do pogreške prilikom dupliciranja <span class='dialog-filename'>{0}</span>",
  "INVALID_FILENAME_MESSAGE": "Imena datoteka ne smiju sadržavati sljedeće znakove: {0} ili riječi rezervirane za sistem.",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Datoteka ili direktorij s imenom <span class='dialog-filename'>{0}</span> već postoji.",
  "ERROR_CREATING_FILE_TITLE": "Greška pri kreiranju {0}",
  "ERROR_CREATING_FILE": "Došlo je do greške prilikom pokušaja da se kreira {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "Nije moguće otvoriti mapu u isto vrijeme kada otvarate druge datoteke.",
  "ERROR_KEYMAP_TITLE": "Pogreška pri čitanju karte korisničkih ključeva",
  "ERROR_KEYMAP_CORRUPT": "Vaša datoteka mape ključeva nije važeća JSON. Datoteka će se otvoriti kako biste mogli ispraviti format.",
  "ERROR_LOADING_KEYMAP": "Vaša datoteka mape ključeva nije valjana tekstualna datoteka kodirana UTF-8 i ne može se učitati",
  "ERROR_RESTRICTED_COMMANDS": "Ne možete ponovno dodijeliti prečace ovim naredbama: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Ne možete ponovno dodijeliti ove prečace: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Ponovno dodjeljujete više prečaca ovim naredbama: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Imate više veza ovih prečaca: {0}",
  "ERROR_INVALID_SHORTCUTS": "Ovi prečaci nisu valjani: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Dodjeljujete prečace nepostojećim naredbama: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Greška prilikom učitavanja preferencija",
  "ERROR_PREFS_CORRUPT": "Vaša datoteka preferencije nije valjana u JSON. Datoteka će biti otvorena tako da možete ispraviti format. Da biste vidjeli promjene, ponovo pokrenite {APP_NAME}.",
  "ERROR_PROJ_PREFS_CORRUPT": "Vaša datoteka s postavkama projekta nije važeća JSON. Datoteka će se otvoriti kako biste mogli ispraviti format. Morat ćete ponovno učitati projekt kako bi promjene stupile na snagu.",
  "ERROR_IN_BROWSER_TITLE": "Ups! {APP_NAME} još uvijek ne radi u pregledniku.",
  "ERROR_IN_BROWSER": "Aplikacija \"{APP_NAME}\" je napravljena pomoću HTML-a, ali trenutno radi kao \"desktop\" aplikacija pa je možete koristiti za izmjenu lokalnih datoteka. Molimo Vas koristite \"application shell\" na <b>github.com/adobe/brackets-shell</b> repozitorij za pokretanje \"{APP_NAME}\" aplikacije.",
  "ERROR_MAX_FILES_TITLE": "Greška prilikom indeksiranja datoteka",
  "ERROR_MAX_FILES": "Indeksiran je maksimalni broj datoteka. Akcije koje pretražuju datoteke u indeksu mogu pogrešno funkcionirati.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Greška prilikom pokretanja web preglednika",
  "ERROR_CANT_FIND_CHROME": "Google Chrome preglednik nije pronađen. Molimo potvrdite da je instaliran.",
  "ERROR_LAUNCHING_BROWSER": "Greška prilikom pokretanja web preglednika. (error {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Greška u živom prikazivanju",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Povezivanje sa preglednikom",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Da bi se Prikaz Uživo povezao, potrebno je ponovo pokrenuti Chrome sa uključenim podešavanjima za remote debugging.<br /><br />Da li želite ponovo pokrenuti Chrome i omogućiti remote debugging?",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Nije moguće učitati živi prikaz stranice",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "Za pokretanje prikaza uživo sa datotekom koja je na serveru, morate navesti osnovnu URL adresu za ovaj projekt.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Greška prilikom pokretanja HTTP servera za prikaz datoteka uživo. Pokušajte ponovo.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Za više informacija, pogledajte <a href='{0}' title='{0}'>Rješavanje grešaka u povezivanju prilikom Prikaza uživo.</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Prikaz uživo",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Prikaz uživo: Povezivanje…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Prikaz uživo: Inicijalizacija…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Napusti prikaz uživo",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Prikaz uživo",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Odaberite datoteku za pregled uživo",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Ponovno učitaj stranicu",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Uključi/isključi istaknute preglede uživo",
  "LIVE_DEV_CLICK_POPOUT": "Skočni pregled uživo u novi prozor",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Prikvači na Otkvači stranicu pregleda",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Prikaz uživo (ne osvježava se zbog greške u sintaksi)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Prikaz uživo je otkazan jer su u pregledniku bili otvoreni razvojni alati",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Prikaz uživo je otkazan jer je stranica zatvorena u pregledniku",
  "LIVE_DEV_NAVIGATED_AWAY": "Prikaz uživo je otkazan jer je preglednik otišao na stranicu koja nije dio trenutnog projekta.",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Prikaz uživo je otkazan iz nepoznatog razloga ({0})",
  "SAVE_CLOSE_TITLE": "Sačuvaj promjene",
  "SAVE_CLOSE_MESSAGE": "Želite li sačuvati izmjene koje ste napravili u dokumentu <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Želite li sačuvati izmjene sljedećih datoteka?",
  "EXT_MODIFIED_TITLE": "Vanjske izmjene",
  "CONFIRM_DELETE_TITLE": "Potvrdi brisanje",
  "CONFIRM_FILE_DELETE": "Jeste li sigurni da želite izbrisati datoteku <span class='dialog-filename'>{0}</span> ?",
  "CONFIRM_FOLDER_DELETE": "Da li ste sigurni da želite obrisati mapu <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "Datoteka obrisana",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> je bio izmjenjen na disku.<br /><br />Da li želite sačuvati datoteku i spremiti preko tih izmjena?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> je bila izmjenjena na disku, ali isto tako sadrži nesačuvane promjene u {APP_NAME}.<br /><br />Koju verziju želite sačuvati?",
  "EXT_DELETED_MESSAGE": "Datoteka <span class='dialog-filename'>{0}</span> je izbrisana na disku, ali postoje njene nesačuvane promjene u {APP_NAME}.<br /><br />Želite li sačuvati te promjene?",
  "WINDOW_UNLOAD_WARNING": "Jeste li sigurni da želite prijeći na drugi URL i ostaviti zagrade?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Imate nespremljene promjene! Jeste li sigurni da želite prijeći na drugi URL i ostaviti zagrade?",
  "DONE": "Može",
  "OK": "OK",
  "CANCEL": "Otkaži",
  "DONT_SAVE": "Nemoj sačuvati",
  "SAVE": "Sačuvaj",
  "SAVE_AS": "Sačuvaj kao…",
  "SAVE_AND_OVERWRITE": "Piši preko",
  "DELETE": "Obriši",
  "BUTTON_YES": "Da",
  "BUTTON_NO": "Ne",
  "FIND_MATCH_INDEX": "{0} od {1}",
  "FIND_NO_RESULTS": "Nema rezultata",
  "FIND_QUERY_PLACEHOLDER": "Nađi…",
  "FIND_HISTORY_MAX_COUNT": "Maksimalni broj stavki pretraživanja u povijesti pretraživanja",
  "REPLACE_PLACEHOLDER": "Zamijeni sa…",
  "BUTTON_REPLACE_ALL": "Sve…",
  "BUTTON_REPLACE_BATCH": "Serija...",
  "BUTTON_REPLACE_ALL_IN_FILES": "Zamijeniti…",
  "BUTTON_REPLACE": "Zamijeni",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Sljedeće poklapanje",
  "BUTTON_PREV_HINT": "Prethodno poklapanje",
  "BUTTON_CASESENSITIVE_HINT": "Poklapanje samo sa specificiranim/određenim velikim ili malim slovom",
  "BUTTON_REGEXP_HINT": "Regularni izraz",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Zamijeni bez poništavanja",
  "REPLACE_WITHOUT_UNDO_WARNING": "Budući da je potrebno promijeniti više od {0} datoteka, {APP_NAME} će izmijeniti neotvorene datoteke na disku.<br /> Nećete moći poništiti zamjene u tim datotekama.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Zamijeni bez poništavanja",
  "OPEN_FILE": "Otvori datoteku",
  "SAVE_FILE_AS": "Sačuvaj datoteku",
  "CHOOSE_FOLDER": "Izaberi mapu",
  "RELEASE_NOTES": "Bilješke o trenutnoj verziji",
  "NO_UPDATE_TITLE": "Imate aktualnu verziju!",
  "NO_UPDATE_MESSAGE": "Trenutno koristite aktualnu verziju aplikacije {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "Zamijeni",
  "FIND_REPLACE_TITLE_WITH": "s",
  "FIND_TITLE_LABEL": "Pronađeno",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} u {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "u <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "u projektu",
  "FIND_IN_FILES_ZERO_FILES": "Filtar isključuje sve datoteke {0}",
  "FIND_IN_FILES_FILE": "datoteci",
  "FIND_IN_FILES_FILES": "datoteka",
  "FIND_IN_FILES_MATCH": "poklapanje",
  "FIND_IN_FILES_MATCHES": "poklapanja",
  "FIND_IN_FILES_MORE_THAN": "Preko ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Ctrl/Cmd klikni da proširiš/skupiš sve",
  "FIND_IN_FILES_INDEXING": "Indeksiranje za Instant Search...",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Indeksiranje {0} od {1} datoteka za Instant pretraživanje…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Zamijeni pogreške",
  "REPLACE_IN_FILES_ERRORS": "Sljedeće datoteke nisu izmijenjene jer su se promijenile nakon pretraživanja ili ih nije bilo moguće napisati.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Greška prilikom učitavanja informacija o novoj verziji",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Došlo je do problema prilikom preuzimanja posljednjih informacija o novoj verziji sa servera. Molimo provjerite da li ste povezani na internet i pokušajte ponovo",
  "NEW_FILE_FILTER": "Novi skup izuzimanja…",
  "CLEAR_FILE_FILTER": "Ne izuzimajte datoteke",
  "NO_FILE_FILTER": "Isključi datoteke…",
  "EXCLUDE_FILE_FILTER": "Isključi {0}",
  "EDIT_FILE_FILTER": "Uredi…",
  "FILE_FILTER_DIALOG": "Uređivački filter",
  "FILE_FILTER_INSTRUCTIONS": "Isključi datoteke i direktorije koji se slažu sa ijednom od sljedećih nizova / podnizova riječi ili <a href='{0}' title='{0}'>globs</a>. Unesi svaki niz u novi red.",
  "FILTER_NAME_PLACEHOLDER": "Dodijelite naziv ovom skupu izuzimanja (neobavezno)",
  "FILTER_NAME_REMAINING": "Preostalo znakova: {0}",
  "FILE_FILTER_CLIPPED_SUFFIX": "i {0} više",
  "FILTER_COUNTING_FILES": "Brojanje datoteka…",
  "FILTER_FILE_COUNT": "Dopušta {0} od {1} datoteka {2}",
  "FILTER_FILE_COUNT_ALL": "Dopušta sve {0} datoteke {1}",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Brzo uređivanje nije dostupno za trenutnu poziciju kursora",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "Brzo CSS uređivanje: postavi kursor na pojedinačno ime klase",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "Brzo CSS uređivanje: nepotpuno svojstvo klase",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "Brzo CSS uređivanje: nepotpuno id svojstvo",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "Brzo CSS uređivanje: postavi kursor na tag, klasu(class), ili id",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "Brzo CSS uređivanje vremenskog raspoređivanja: nevažeća sintaksa",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "Brzo JS uređivanje: postavi kursor na ime funkcije",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Nema dostupnih brzih dokumenata za trenutnu poziciju kursora",
  "PROJECT_LOADING": "Učitavanje…",
  "UNTITLED": "Neimenovan",
  "WORKING_FILES": "Radne datoteke",
  "TOP": "Vrh",
  "BOTTOM": "Dno",
  "LEFT": "Lijevo",
  "RIGHT": "Desno",
  "CMD_SPLITVIEW_NONE": "Bez prepolavljanja",
  "CMD_SPLITVIEW_VERTICAL": "Prepolovi okomito",
  "CMD_SPLITVIEW_HORIZONTAL": "Prepolovi vodoravno",
  "SPLITVIEW_MENU_TOOLTIP": "Prepolovi editor okomito ili vodoravno",
  "GEAR_MENU_TOOLTIP": "Definiraj radni skup",
  "SPLITVIEW_INFO_TITLE": "Već otvoreno",
  "SPLITVIEW_MULTIPANE_WARNING": "Datoteka je već otvorena u drugom panelu. {APP_NAME} će uskoro podržavati otvaranje iste datoteke u više od jednog panela. Do tada, datoteka će biti prikazana u panelu u kojem je već otvorena.<br /><br />(Ovu ćeš poruku vidjeti samo jednom.)",
  "STATUSBAR_CURSOR_POSITION": "Red {0}, Stupac {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — izabran {0} stupac",
  "STATUSBAR_SELECTION_CH_PLURAL": " — izabrano {0} stupaca",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — izabrano {0} redova",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — izabrano {0} redova",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} odabira",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Klikni za korištenje razmaka prilikom uvlačenja kôda",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Klikni za korištenje tabova prilikom uvlačenja kôda*",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Klikni da promjeniš broj razmaka prilikom uvlačenja kôda",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Klikni da promjeniš širinu karaktera na kartici",
  "STATUSBAR_SPACES": "Razmaci:",
  "STATUSBAR_TAB_SIZE": "Veličina kartice:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} red",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} redova",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Extenzije onemogućene",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "OVR",
  "STATUSBAR_INSOVR_TOOLTIP": "Pritisnite za prebacivanje kursora između načina rada Umetni (INS) i Prebriši (OVR).",
  "STATUSBAR_LANG_TOOLTIP": "Kliknite za promjenu vrste datoteke",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Kliknite za prebacivanje ploče izvješća.",
  "STATUSBAR_DEFAULT_LANG": "(zadano)",
  "STATUSBAR_SET_DEFAULT_LANG": "Postavi kao zadano za .{0} datoteke",
  "STATUSBAR_ENCODING_TOOLTIP": "Odaberite kodiranje",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} grešaka",
  "SINGLE_ERROR": "1 {0} greška",
  "MULTIPLE_ERRORS": "{1} {0} grešaka",
  "NO_ERRORS": "Nema {0} nađenih grešaka - svaka čast!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Nema nađenih grešaka - bravo!",
  "LINT_DISABLED": "Detektiranje sumnjivog kôda isključeno",
  "NO_LINT_AVAILABLE": "Nijedan detektor sumnjivog kôda nije dostupan za {0}",
  "NOTHING_TO_LINT": "Nije pronađen sumnjivi kôd",
  "LINTER_TIMED_OUT": "{0} je isteklo nakon čekanja od {1} ms",
  "LINTER_FAILED": "{0} prekinuto s pogreškom: {1}",
  "FILE_MENU": "Datoteka",
  "CMD_FILE_NEW_UNTITLED": "Nova",
  "CMD_FILE_NEW": "Nova datoteka",
  "CMD_FILE_DUPLICATE": "Udvostruči",
  "CMD_FILE_DOWNLOAD_PROJECT": "Preuzmite projekt",
  "CMD_FILE_DOWNLOAD": "preuzimanje datoteka",
  "CMD_FILE_CUT": "Izreži",
  "CMD_FILE_COPY": "Kopiraj",
  "CMD_FILE_COPY_PATH": "Kopiraj put",
  "CMD_FILE_PASTE": "Zalijepi",
  "CMD_PROJECT_NEW": "Novi projekt",
  "CMD_FILE_NEW_FOLDER": "Nova mapa",
  "CMD_FILE_OPEN": "Otvori…",
  "CMD_RECENT_FILES_OPEN": "Nedavne datoteke…",
  "CMD_ADD_TO_WORKING_SET": "Dodaj u radni set",
  "CMD_OPEN_DROPPED_FILES": "Otvori umetnune datoteke",
  "CMD_OPEN_FOLDER": "Otvori mapu…",
  "CMD_FILE_CLOSE": "Zatvori",
  "CMD_FILE_CLOSE_ALL": "Zatvori sve",
  "CMD_FILE_CLOSE_LIST": "Zatvori listu",
  "CMD_FILE_CLOSE_OTHERS": "Zatvori druge",
  "CMD_FILE_CLOSE_ABOVE": "Zatvori druge iznad",
  "CMD_FILE_CLOSE_BELOW": "Zatvori druge ispod",
  "CMD_FILE_SAVE": "Sačuvaj datoteku",
  "CMD_FILE_SAVE_ALL": "Sačuvaj sve",
  "CMD_FILE_SAVE_AS": "Sačuvaj kao…",
  "CMD_LIVE_FILE_PREVIEW": "Prikaz uživo",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Omogući Experimentalni Prikaz Uživo",
  "CMD_RELOAD_LIVE_PREVIEW": "Prisilno ponovno učitavanje uživo",
  "CMD_PROJECT_SETTINGS": "Postavke projekta…",
  "CMD_FILE_RENAME": "Preimenuj",
  "CMD_FILE_DELETE": "Obriši",
  "CMD_INSTALL_EXTENSION": "Instaliraj ekstenziju…",
  "CMD_EXTENSION_MANAGER": "Manager ekstenzija…",
  "CMD_FILE_REFRESH": "Osvježi stablo datoteka",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Prvo sortiraj mape",
  "CMD_QUIT": "Prekini",
  "CMD_EXIT": "Izađi",
  "EDIT_MENU": "Uredi",
  "CMD_UNDO": "Poništi",
  "CMD_REDO": "Ponovi",
  "CMD_CUT": "Izreži",
  "CMD_COPY": "Kopiraj",
  "CMD_PASTE": "Zalijepi",
  "CMD_SELECT_ALL": "Odaberi sve",
  "CMD_SELECT_LINE": "Odaberi red",
  "CMD_SPLIT_SEL_INTO_LINES": "Razdvoji odabrano u redove",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Dodaj kursor u sljedeći red",
  "CMD_ADD_CUR_TO_PREV_LINE": "Dodaj kursor u prošli red",
  "CMD_INDENT": "Pomakni udesno",
  "CMD_UNINDENT": "Pomakni ulijevo",
  "CMD_DUPLICATE": "Udvostruči",
  "CMD_DELETE_LINES": "Obriši red",
  "CMD_COMMENT": "// Komentar reda",
  "CMD_BLOCK_COMMENT": "Blok komentar /*..*/",
  "CMD_LINE_UP": "Pomakni red gore",
  "CMD_LINE_DOWN": "Pomakni red dolje",
  "CMD_OPEN_LINE_ABOVE": "Otvori red iznad",
  "CMD_OPEN_LINE_BELOW": "Otvori red ispod",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Automatski zatvori zagrade",
  "CMD_SHOW_CODE_HINTS": "Prikaži naznake (hintove) kôda",
  "CMD_BEAUTIFY_CODE": "Uljepšaj kod",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "Uljepšajte kod nakon spremanja",
  "FIND_MENU": "Pronađi",
  "CMD_FIND": "Pronađi",
  "CMD_FIND_NEXT": "Pronađi sljedeće",
  "CMD_FIND_PREVIOUS": "Pronađi prethodno",
  "CMD_FIND_ALL_AND_SELECT": "Pronađi sve i odaberi",
  "CMD_ADD_NEXT_MATCH": "Dodaj sljedeće slaganje u odabir",
  "CMD_SKIP_CURRENT_MATCH": "Preskoči i dodaj sljedeće slaganje",
  "CMD_FIND_IN_FILES": "Pronađi u datotekama",
  "CMD_FIND_IN_SUBTREE": "Pronađi u…",
  "CMD_REPLACE": "Zamijeni",
  "CMD_REPLACE_IN_FILES": "Zamijeni u datotekama",
  "CMD_REPLACE_IN_SUBTREE": "Zamijeni u…",
  "VIEW_MENU": "Prikaz",
  "CMD_HIDE_SIDEBAR": "Sakrij bočnu traku",
  "CMD_SHOW_SIDEBAR": "Prikaži bočnu traku",
  "CMD_TOGGLE_SIDEBAR": "Toggle bočnu traku",
  "CMD_TOGGLE_PANELS": "Toggle panele",
  "CMD_TOGGLE_PURE_CODE": "Bez odvraćanja pažnje",
  "CMD_INCREASE_FONT_SIZE": "Povećaj veličinu fonta",
  "CMD_DECREASE_FONT_SIZE": "Smanji veličinu fonta",
  "CMD_RESTORE_FONT_SIZE": "Vrati veličinu fonta",
  "CMD_SCROLL_LINE_UP": "Pomakni red gore",
  "CMD_SCROLL_LINE_DOWN": "Pomakni red dolje",
  "CMD_TOGGLE_LINE_NUMBERS": "Brojevi redova",
  "CMD_TOGGLE_ACTIVE_LINE": "Označi aktivni red",
  "CMD_TOGGLE_WORD_WRAP": "Prijelom teksta",
  "CMD_LIVE_HIGHLIGHT": "Obilježi prikaz uživo",
  "CMD_VIEW_TOGGLE_INSPECTION": "Prekontroliraj datoteke prilikom spremanja",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Sortiraj po datumu",
  "CMD_WORKINGSET_SORT_BY_NAME": "Sortiraj po imenu",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Sortiraj po tipu",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Automatsko sortiranje",
  "CMD_THEMES": "Teme…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Automatski zatvori pretragu",
  "NAVIGATE_MENU": "Navigacija",
  "CMD_QUICK_OPEN": "Brzo otvori",
  "CMD_GOTO_LINE": "Idi na red",
  "CMD_GOTO_DEFINITION": "Brzo nađi definiciju",
  "CMD_GOTO_DEFINITION_PROJECT": "Definicija brzog traženja u projektu",
  "CMD_GOTO_FIRST_PROBLEM": "Idi na prvu grešku/upozorenje",
  "CMD_TOGGLE_QUICK_EDIT": "Brzo izmjeni",
  "CMD_TOGGLE_QUICK_DOCS": "Brzi dokumenti",
  "CMD_QUICK_EDIT_PREV_MATCH": "Prethodno poklapanje",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Sljedeće poklapanje",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Novo pravilo",
  "CMD_NEXT_DOC": "Sljedeći dokument",
  "CMD_PREV_DOC": "Prethodni dokument",
  "CMD_NAVIGATE_BACKWARD": "Navigacija unatrag",
  "CMD_NAVIGATE_FORWARD": "Navigacija naprijed",
  "CMD_NEXT_DOC_LIST_ORDER": "Sljedeći dokument u listi",
  "CMD_PREV_DOC_LIST_ORDER": "Prethodni dokument u listi",
  "CMD_SHOW_IN_TREE": "Prikaži u stablu datoteka",
  "CMD_SHOW_IN_EXPLORER": "Prikaži u pregledniku",
  "CMD_SHOW_IN_FINDER": "Prikaži u pretraživaču",
  "CMD_SHOW_IN_OS": "Prikaži u OS-u",
  "CMD_SWITCH_PANE_FOCUS": "Promjena fokusa okna",
  "CMD_OPEN_VFS": "Otvorite virtualni datotečni sustav",
  "CMD_OPEN_VIRTUAL_SERVER": "Otvorite virtualni poslužitelj",
  "HELP_MENU": "Pomoć",
  "CMD_CHECK_FOR_UPDATE": "Provjeri postoji li novija verzija",
  "CMD_HOW_TO_USE_BRACKETS": "Kako koristiti {APP_NAME}",
  "CMD_SUPPORT": "{APP_NAME} Podrška (na engleskom)",
  "CMD_SUGGEST": "Predloži mogućnost / značajku",
  "CMD_RELEASE_NOTES": "Bilješke o trenutnoj verziji",
  "CMD_GET_INVOLVED": "Uključi se",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Prikaži direktorij sa ekstenzijama",
  "CMD_HEALTH_DATA_STATISTICS": "Zdravstveni izvještaj",
  "CMD_HOMEPAGE": "Početna stranica {APP_NAME}",
  "CMD_TWITTER": "{TWITTER_NAME} na Twitteru",
  "CMD_ABOUT": "O programu {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "Otvori preferencije",
  "CMD_OPEN_KEYMAP": "Otvori svoje postavke tipki*",
  "EXPERIMENTAL_BUILD": "experimentalna verzija",
  "RELEASE_BUILD": "izgraditi",
  "DEVELOPMENT_BUILD": "razvojna verzija",
  "PRERELEASE_BUILD": "verzija prije izdanja",
  "RELOAD_FROM_DISK": "Ponovo učitaj sa diska",
  "KEEP_CHANGES_IN_EDITOR": "Sačuvaj izmjene u Editoru",
  "CLOSE_DONT_SAVE": "Zatvori (Nemoj sačuvati)",
  "RELAUNCH_CHROME": "Ponovo pokreni Chrome",
  "ABOUT": "O aplikaciji",
  "CLOSE": "Zatvori",
  "ABOUT_TEXT_LINE1": "Izdanje {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "vremenska oznaka izrade:",
  "ABOUT_TEXT_LINE3": "Biblioteke trećih strana koje koristimo - <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>licence i atribucije</a> .",
  "ABOUT_TEXT_LINE4": "Dokumentacija i izvor na <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "Napravio pomoću ❤ i JavaScripta:",
  "ABOUT_TEXT_LINE6": "Puno ljudi (ali trenutno imamo problema s učitavanjem tih podataka).",
  "ABOUT_TEXT_MDN_DOCS": "MDN Docs i MDN graphical logo su zaštićeni pod Creative Commons Attribution licencom, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "Dostupna je nova verzija aplikacije {APP_NAME}! Kliknite ovdje za detalje.",
  "UPDATE_AVAILABLE_TITLE": "Novija verzija je dostupna",
  "UPDATE_RELOAD_APP": "Zatvorite sve prozore/kartice aplikacije {APP_NAME} i ponovno otvorite aplikaciju {APP_NAME} da biste dobili najnoviju verziju.",
  "UPDATE_MESSAGE": "Nova verzija aplikacije {APP_NAME} je dostupna. Ovo su neke od najnovijih izmjena:",
  "GET_IT_NOW": "Preuzmi sada!",
  "PROJECT_SETTINGS_TITLE": "Postavke projekta za: {0}",
  "PROJECT_SETTING_BASE_URL": "Osnovna URL adresa za prikaz uživo",
  "PROJECT_SETTING_BASE_URL_HINT": "Da biste koristili lokalni server unesite adresu (url) kao http://localhost:8000/",
  "BASEURL_ERROR_INVALID_PROTOCOL": "Prikaz uživo ne podržava protokol {0} &mdash; koristite http: or https: .",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "Osnovna URL adresa ne smije sadržavati parametre za traženje poput \"{0}\".",
  "BASEURL_ERROR_HASH_DISALLOWED": "Osnovna URL adresa ne smije sadržavati hasheve (hashes) poput \"{0}\".",
  "BASEURL_ERROR_INVALID_CHAR": "Posebni znakovi kao '{0}' moraju biti %-enkodirani.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "Nepoznata greška prilikom parsiranja osnovne URL adrese",
  "EMPTY_VIEW_HEADER": "<em>Otvori datoteku dok je ovaj panel u fokusu</em>",
  "FLIPVIEW_BTN_TOOLTIP": "Okrenite ovaj prikaz na {0} okno",
  "CURRENT_THEME": "Trenutna tema",
  "USE_THEME_SCROLLBARS": "Koristi scrollbarove teme",
  "FONT_SIZE": "Veličina fonta",
  "FONT_FAMILY": "Obitelj fonta",
  "THEMES_SETTINGS": "Postavke teme",
  "THEMES_ERROR": "Pogreška teme",
  "THEMES_ERROR_CANNOT_APPLY": "Nije moguće primijeniti temu zbog pogreške.",
  "BUTTON_NEW_RULE": "Novo pravilo",
  "INSTALL": "Instaliraj",
  "APPLY": "primijeniti",
  "UPDATE": "Ažuriraj",
  "REMOVE": "Ukloni",
  "DISABLE": "Onemogući",
  "ENABLE": "Omogući",
  "OVERWRITE": "Piši preko",
  "CANT_DROP_ZIP": "Uskoro će biti podržano ispuštanje zip datoteka...",
  "CANT_REMOVE_DEV": "Extenzije u \"dev\" mapi moraju biti ručno obrisane.",
  "CANT_UPDATE": "Novija verzija nije kompatibilna sa trenutnom verzijom aplikacije {APP_NAME}.",
  "CANT_UPDATE_DEV": "Extenzije u \"dev\" mapi ne mogu biti automatski ažurirane.",
  "INSTALL_EXTENSION_TITLE": "Instaliraj ekstenziju",
  "UPDATE_EXTENSION_TITLE": "Obnovi ekstenziju",
  "INSTALL_EXTENSION_LABEL": "Link ekstenzije",
  "INSTALL_EXTENSION_HINT": "Link zip arhive ekstenzije ili GitHub repozitorija",
  "INSTALLING_FROM": "Instaliranje ekstenzije sa {0}…",
  "INSTALL_SUCCEEDED": "Instalacija je uspjela!",
  "INSTALL_FAILED": "Instalacija nije uspjela.",
  "CANCELING_INSTALL": "Otkazivanje…",
  "CANCELING_HUNG": "Otkazivanje instalacije traje predugo. Vjerojatno je došlo do unutarnje greške.",
  "INSTALL_CANCELED": "Instalacija je otkazana.",
  "VIEW_COMPLETE_DESCRIPTION": "Pogledajte kompletan opis",
  "VIEW_TRUNCATED_DESCRIPTION": "Pogledajte skraćeni opis",
  "SORT_EXTENSION_METHOD": "Sortirajte proširenja pomoću downloadCount ili publishedDate",
  "INVALID_ZIP_FILE": "Preuzeti sadržaj nije valjana zip arhiva.",
  "MISSING_PACKAGE_JSON": "Paket nema datoteku package.json.",
  "INVALID_PACKAGE_JSON": "package.json datoteka nije valjana (greška je bila: {0}).",
  "MISSING_PACKAGE_NAME": "package.json datoteka nije navela ime paketa.",
  "BAD_PACKAGE_NAME": "{0} nije valjano ime za paket.",
  "MISSING_PACKAGE_VERSION": "package.json datoteka nije navela verziju paketa.",
  "INVALID_VERSION_NUMBER": "Verzija paketa broj ({0}) nije valjana.",
  "INVALID_BRACKETS_VERSION": "Niz o kompatibilnosti ({0}) aplikacije {APP_NAME} nije valjan.",
  "DISALLOWED_WORDS": "Riječi ({1}) nisu dozvoljene u polju {0}.",
  "NPM_INSTALL_FAILED": "npm instalacijska naredba nije uspjela: {0}",
  "API_NOT_COMPATIBLE": "Ova ekstenzija nije kompatibilna sa ovom verzijom aplikacije {APP_NAME}. Instalirana je u vašu mapu onemogućenih extenzija.",
  "MISSING_MAIN": "Paket nema main.js datoteku.",
  "EXTENSION_ALREADY_INSTALLED": "Instaliranjem ovog paketa ćete presnimiti prethodno instaliranu verziju. Da li želite presnimiti staru ekstenziju?",
  "EXTENSION_SAME_VERSION": "Verzija ovog paketa je ista kao verzija koja je trenutno instalirana. Da li želite presnimiti postojeću instalaciju?",
  "EXTENSION_OLDER_VERSION": "Ovaj paket je verzija {0} što je starije od trenutno instalirane verzije ({1}). Želite li presnimiti postojeću instalaciju?",
  "DOWNLOAD_ID_IN_USE": "Unutarnja greška: ID preuzimanja je već u upotrebi.",
  "NO_SERVER_RESPONSE": "Povezivanje sa serverom nije moguće.",
  "BAD_HTTP_STATUS": "Datoteka nije pronađena na serveru (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "Nije moguće sačuvati preuzete podatke u privremenu datoteku.",
  "ERROR_LOADING": "Extenzija je naišla na grešku prilikom pokretanja.",
  "MALFORMED_URL": "URL nije valjan. Molimo provjerite da li ste ga unjeli točno.",
  "UNSUPPORTED_PROTOCOL": "URL mora biti http ili https URL.",
  "UNKNOWN_ERROR": "Nepoznata unutarnja greška.",
  "EXTENSION_VERIFIED_PUBLISHER": "Ovaj izdavač je potvrdio vlasništvo nad {0}",
  "EXTENSION_VERIFIED_SORT": "Provjereno",
  "EXTENSION_STAR": "Zvijezda",
  "EXTENSION_STAR_SORT": "Ocjena zvjezdicama",
  "EXTENSION_MANAGER_TITLE": "Manager ekstenzija",
  "EXTENSION_MANAGER_ERROR_LOAD": "Pristupanje registru ekstenzije nije moguće. Pokušajte kasnije.",
  "INSTALL_EXTENSION_DRAG": "Dovuci .zip ovdje ili",
  "INSTALL_EXTENSION_DROP": "ispusti .zip da instaliraš",
  "INSTALL_EXTENSION_DROP_ERROR": "Instalacija/ažuriranje prekinuto zbog sljedećih grešaka:",
  "INSTALL_FROM_URL": "Instaliraj sa URL linka…",
  "INSTALL_EXTENSION_VALIDATING": "Provjera...",
  "EXTENSION_AUTHOR": "Autor",
  "EXTENSION_DATE": "Datum",
  "EXTENSION_INCOMPATIBLE_NEWER": "Ova extenzija zahtjeva noviju verziju aplikacije {APP_NAME}.",
  "EXTENSION_INCOMPATIBLE_OLDER": "Ova extenzija trenutno radi samo sa starijom verzijom aplikacije {APP_NAME}.",
  "EXTENSION_DEFAULT_FEATURE_PRESENT": "Možda vam ovo proširenje neće trebati. {APP_NAME} već ima ovu značajku.",
  "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "Verzija {0} ove ekstenzije traži noviju verziju aplikacije {APP_NAME}. Ali možete instalirati raniju verziju {1}.",
  "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "Verzija {0} ove ekstenzije radi samo sa starijim verzijama aplikacije {APP_NAME}. Ali možete instalirati raniju verziju {1}.",
  "EXTENSION_NO_DESCRIPTION": "Nema opisa",
  "EXTENSION_MORE_INFO": "Više informacija...",
  "EXTENSION_ERROR": "Greška u ekstenziji",
  "EXTENSION_KEYWORDS": "Ključne riječi",
  "EXTENSION_TRANSLATED_USER_LANG": "Prevedeno na {0} jezika, uključujući vaš",
  "EXTENSION_TRANSLATED_GENERAL": "Prevedeno na {0} jezika",
  "EXTENSION_TRANSLATED_LANGS": "Ovo proširenje je prevedeno na ove jezike: {0}",
  "EXTENSION_INSTALLED": "Instalirano",
  "EXTENSION_UPDATE_INSTALLED": "Ova verzija ekstenzije već je preuzeta i bit će instalirana nakon što se {APP_NAME} ponovo učita.",
  "EXTENSION_SEARCH_PLACEHOLDER": "Traži",
  "EXTENSION_MORE_INFO_LINK": "Više",
  "EXTENSION_MANAGER_CREATE_EXTENSION": "+ Stvori proširenje",
  "EXTENSION_MANAGER_CREATE_THEME": "+ Izradite temu",
  "BROWSE_EXTENSIONS": "Pretraži ekstenzije",
  "EXTENSION_MANAGER_REMOVE": "Ukloni ekstenziju",
  "EXTENSION_MANAGER_REMOVE_ERROR": "Nemoguće je ukloniti jednu ili više ekstenzija: {0}. {APP_NAME} će se svejedno ponovo učitati.",
  "EXTENSION_MANAGER_UPDATE": "Obnovi ekstenziju",
  "EXTENSION_MANAGER_UPDATE_ERROR": "Nije moguće obnoviti jednu ili više ekstenzija: {0}. {APP_NAME} će se svejedno ponovno učitati.",
  "EXTENSION_MANAGER_DISABLE": "Onemogući proširenje",
  "EXTENSION_MANAGER_DISABLE_ERROR": "Nije moguće onemogućiti jedno ili više proširenja: {0}. {APP_NAME} će se ipak ponovno učitati.",
  "EXTENSION_MANAGER_THEMES_INFO": "Za <a class=\"theme_settings\">odabir zadanih tema</a> ili izmjenu drugih postavki teme <a class=\"theme_settings\">kliknite ovdje</a> .",
  "EXTENSIO