/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "Zadani jezik",
  "PROJECT_BUSY": "Projektne operacije u tijeku",
  "DUPLICATING": "Umnožavanje {0}",
  "MOVING": "Premještanje {0}",
  "COPYING": "Kopiranje {0}",
  "DELETING": "Brisanje {0}",
  "RENAMING": "Preimenovanje",
  "GENERIC_ERROR": "(greška {0})",
  "NOT_FOUND_ERR": "Nepostojeća datoteka.",
  "NOT_READABLE_ERR": "Datoteka ne može biti učitana.",
  "EXCEEDS_MAX_FILE_SIZE": "Datoteke veće od {0} MB ne mogu se otvoriti u {APP_NAME}.",
  "NO_MODIFICATION_ALLOWED_ERR": "Ciljana mapa ne može biti izmijenjena.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Trenutne ovlasti vam ne dozvoljavaju kreiranje izmjena.",
  "CONTENTS_MODIFIED_ERR": "Datoteka je bila izmjenjena izvan {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "Nepoznati format kodiranja",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} nije uspjela kodirati sadržaj datoteke.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} nije uspjela dekodirati sadržaj datoteke.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} trenutno ne podržava tekstualne datoteke kodirane UTF-16.",
  "FILE_EXISTS_ERR": "Datoteka ili mapa već postoji.",
  "FILE": "datoteci",
  "FILE_TITLE": "Datoteka",
  "DIRECTORY": "Direktorij",
  "DIRECTORY_TITLE": "Imenik",
  "DIRECTORY_NAMES_LEDE": "Imena imenika",
  "FILENAMES_LEDE": "Nazivi datoteka",
  "FILENAME": "Naziv datoteke",
  "DIRECTORY_NAME": "Naziv imenika",
  "ERROR_LOADING_PROJECT": "Greška pri učitavanju projekta",
  "OPEN_DIALOG_ERROR": "Došlo je do greške prilikom prikazivanja dijaloga za otvaranje datoteke. (error {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Došlo je do greške prilikom pokušaja da se učita direktorij <span class='dialog-filename'>{0}</span>. (error {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Došlo je do greške prilikom iščitavanja sadržaja direktorija <span class='dialog-filename'>{0}</span>. (error {1})",
  "ERROR_OPENING_FILE_TITLE": "Greška pri otvaranju datoteke",
  "ERROR_OPENING_FILE": "Došlo je do greške prilikom pokušaja da se otvori datoteka <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Došlo je do greške prilikom pokušaja da se otvore sljedeće datoteke:",
  "ERROR_RELOADING_FILE_TITLE": "Greška pri ponovom učitavanju izmjena sa diska",
  "ERROR_RELOADING_FILE": "Došlo je do greške prilikom pokušaja da se ponovo učita datoteka <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Greška pri spremanju datoteke",
  "ERROR_SAVING_FILE": "Došlo je do greške prilikom pokušaja da se sačuva datoteka <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Greška pri preimenovanju datoteke",
  "ERROR_RENAMING_FILE": "Došlo je do greške prilikom pokušaja da se preimenuje datoteka <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Datoteka ili direktorij nije dio trenutno otvorenog projekta. Nažalost, u ovom trenutku mogu se preimenovati samo datoteke projekta.",
  "ERROR_MOVING_FILE_TITLE": "Pogreška pri premještanju {0}",
  "ERROR_MOVING_FILE": "Došlo je do pogreške prilikom pokušaja premještanja {2} <span class='dialog-filename'>{0}</span> . {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Nije moguće premjestiti datoteku/mapu jer nisu dio trenutnog projekta.",
  "ERROR_DELETING_FILE_TITLE": "Greška pri brisanju datoteke",
  "ERROR_DELETING_FILE": "Došlo je do greške prilikom pokušaja da se obriše datoteka <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "Ime {0} nije valjano",
  "CANNOT_PASTE_TITLE": "Nije moguće zalijepiti {0}",
  "CANNOT_DOWNLOAD_TITLE": "Nije moguće preuzeti {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "Došlo je do pogreške prilikom preuzimanja <span class='dialog-filename'>{0}</span>",
  "ERR_TYPE_PASTE_FAILED": "Došlo je do pogreške prilikom lijepljenja <span class='dialog-filename'>{0}</span> u <span class='dialog-filename'>{1}</span>",
  "CANNOT_DUPLICATE_TITLE": "Nije moguće umnožiti",
  "ERR_TYPE_DUPLICATE_FAILED": "Došlo je do pogreške prilikom dupliciranja <span class='dialog-filename'>{0}</span>",
  "INVALID_FILENAME_MESSAGE": "Imena datoteka ne smiju sadržavati sljedeće znakove: {0} ili riječi rezervirane za sistem.",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Datoteka ili direktorij s imenom <span class='dialog-filename'>{0}</span> već postoji.",
  "ERROR_CREATING_FILE_TITLE": "Greška pri kreiranju {0}",
  "ERROR_CREATING_FILE": "Došlo je do greške prilikom pokušaja da se kreira {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "Nije moguće otvoriti mapu u isto vrijeme kada otvarate druge datoteke.",
  "ERROR_KEYMAP_TITLE": "Pogreška pri čitanju karte korisničkih ključeva",
  "ERROR_KEYMAP_CORRUPT": "Vaša datoteka mape ključeva nije važeća JSON. Datoteka će se otvoriti kako biste mogli ispraviti format.",
  "ERROR_LOADING_KEYMAP": "Vaša datoteka mape ključeva nije valjana tekstualna datoteka kodirana UTF-8 i ne može se učitati",
  "ERROR_RESTRICTED_COMMANDS": "Ne možete ponovno dodijeliti prečace ovim naredbama: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Ne možete ponovno dodijeliti ove prečace: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Ponovno dodjeljujete više prečaca ovim naredbama: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Imate više veza ovih prečaca: {0}",
  "ERROR_INVALID_SHORTCUTS": "Ovi prečaci nisu valjani: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Dodjeljujete prečace nepostojećim naredbama: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Greška prilikom učitavanja preferencija",
  "ERROR_PREFS_CORRUPT": "Vaša datoteka preferencije nije valjana u JSON. Datoteka će biti otvorena tako da možete ispraviti format. Da biste vidjeli promjene, ponovo pokrenite {APP_NAME}.",
  "ERROR_PROJ_PREFS_CORRUPT": "Vaša datoteka s postavkama projekta nije važeća JSON. Datoteka će se otvoriti kako biste mogli ispraviti format. Morat ćete ponovno učitati projekt kako bi promjene stupile na snagu.",
  "ERROR_IN_BROWSER_TITLE": "Ups! {APP_NAME} još uvijek ne radi u pregledniku.",
  "ERROR_IN_BROWSER": "Aplikacija \"{APP_NAME}\" je napravljena pomoću HTML-a, ali trenutno radi kao \"desktop\" aplikacija pa je možete koristiti za izmjenu lokalnih datoteka. Molimo Vas koristite \"application shell\" na <b>github.com/adobe/brackets-shell</b> repozitorij za pokretanje \"{APP_NAME}\" aplikacije.",
  "ERROR_MAX_FILES_TITLE": "Greška prilikom indeksiranja datoteka",
  "ERROR_MAX_FILES": "Indeksiran je maksimalni broj datoteka. Akcije koje pretražuju datoteke u indeksu mogu pogrešno funkcionirati.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Greška prilikom pokretanja web preglednika",
  "ERROR_CANT_FIND_CHROME": "Google Chrome preglednik nije pronađen. Molimo potvrdite da je instaliran.",
  "ERROR_LAUNCHING_BROWSER": "Greška prilikom pokretanja web preglednika. (error {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Greška u živom prikazivanju",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Povezivanje sa preglednikom",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Da bi se Prikaz Uživo povezao, potrebno je ponovo pokrenuti Chrome sa uključenim podešavanjima za remote debugging.<br /><br />Da li želite ponovo pokrenuti Chrome i omogućiti remote debugging?",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Nije moguće učitati živi prikaz stranice",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "Za pokretanje prikaza uživo sa datotekom koja je na serveru, morate navesti osnovnu URL adresu za ovaj projekt.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Greška prilikom pokretanja HTTP servera za prikaz datoteka uživo. Pokušajte ponovo.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Za više informacija, pogledajte <a href='{0}' title='{0}'>Rješavanje grešaka u povezivanju prilikom Prikaza uživo.</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Prikaz uživo",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Prikaz uživo: Povezivanje…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Prikaz uživo: Inicijalizacija…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Napusti prikaz uživo",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Prikaz uživo",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Odaberite datoteku za pregled uživo",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Ponovno učitaj stranicu",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Uključi/isključi istaknute preglede uživo",
  "LIVE_DEV_CLICK_POPOUT": "Skočni pregled uživo u novi prozor",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Prikvači na Otkvači stranicu pregleda",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Prikaz uživo (ne osvježava se zbog greške u sintaksi)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Prikaz uživo je otkazan jer su u pregledniku bili otvoreni razvojni alati",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Prikaz uživo je otkazan jer je stranica zatvorena u pregledniku",
  "LIVE_DEV_NAVIGATED_AWAY": "Prikaz uživo je otkazan jer je preglednik otišao na stranicu koja nije dio trenutnog projekta.",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Prikaz uživo je otkazan iz nepoznatog razloga ({0})",
  "SAVE_CLOSE_TITLE": "Sačuvaj promjene",
  "SAVE_CLOSE_MESSAGE": "Želite li sačuvati izmjene koje ste napravili u dokumentu <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Želite li sačuvati izmjene sljedećih datoteka?",
  "EXT_MODIFIED_TITLE": "Vanjske izmjene",
  "CONFIRM_DELETE_TITLE": "Potvrdi brisanje",
  "CONFIRM_FILE_DELETE": "Jeste li sigurni da želite izbrisati datoteku <span class='dialog-filename'>{0}</span> ?",
  "CONFIRM_FOLDER_DELETE": "Da li ste sigurni da želite obrisati mapu <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "Datoteka obrisana",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> je bio izmjenjen na disku.<br /><br />Da li želite sačuvati datoteku i spremiti preko tih izmjena?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> je bila izmjenjena na disku, ali isto tako sadrži nesačuvane promjene u {APP_NAME}.<br /><br />Koju verziju želite sačuvati?",
  "EXT_DELETED_MESSAGE": "Datoteka <span class='dialog-filename'>{0}</span> je izbrisana na disku, ali postoje njene nesačuvane promjene u {APP_NAME}.<br /><br />Želite li sačuvati te promjene?",
  "WINDOW_UNLOAD_WARNING": "Jeste li sigurni da želite prijeći na drugi URL i ostaviti zagrade?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Imate nespremljene promjene! Jeste li sigurni da želite prijeći na drugi URL i ostaviti zagrade?",
  "DONE": "Može",
  "OK": "OK",
  "CANCEL": "Otkaži",
  "DONT_SAVE": "Nemoj sačuvati",
  "SAVE": "Sačuvaj",
  "SAVE_AS": "Sačuvaj kao…",
  "SAVE_AND_OVERWRITE": "Piši preko",
  "DELETE": "Obriši",
  "BUTTON_YES": "Da",
  "BUTTON_NO": "Ne",
  "FIND_MATCH_INDEX": "{0} od {1}",
  "FIND_NO_RESULTS": "Nema rezultata",
  "FIND_QUERY_PLACEHOLDER": "Nađi…",
  "FIND_HISTORY_MAX_COUNT": "Maksimalni broj stavki pretraživanja u povijesti pretraživanja",
  "REPLACE_PLACEHOLDER": "Zamijeni sa…",
  "BUTTON_REPLACE_ALL": "Sve…",
  "BUTTON_REPLACE_BATCH": "Serija...",
  "BUTTON_REPLACE_ALL_IN_FILES": "Zamijeniti…",
  "BUTTON_REPLACE": "Zamijeni",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Sljedeće poklapanje",
  "BUTTON_PREV_HINT": "Prethodno poklapanje",
  "BUTTON_CASESENSITIVE_HINT": "Poklapanje samo sa specificiranim/određenim velikim ili malim slovom",
  "BUTTON_REGEXP_HINT": "Regularni izraz",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Zamijeni bez poništavanja",
  "REPLACE_WITHOUT_UNDO_WARNING": "Budući da je potrebno promijeniti više od {0} datoteka, {APP_NAME} će izmijeniti neotvorene datoteke na disku.<br /> Nećete moći poništiti zamjene u tim datotekama.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Zamijeni bez poništavanja",
  "OPEN_FILE": "Otvori datoteku",
  "SAVE_FILE_AS": "Sačuvaj datoteku",
  "CHOOSE_FOLDER": "Izaberi mapu",
  "RELEASE_NOTES": "Bilješke o trenutnoj verziji",
  "NO_UPDATE_TITLE": "Imate aktualnu verziju!",
  "NO_UPDATE_MESSAGE": "Trenutno koristite aktualnu verziju aplikacije {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "Zamijeni",
  "FIND_REPLACE_TITLE_WITH": "s",
  "FIND_TITLE_LABEL": "Pronađeno",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} u {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "u <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "u projektu",
  "FIND_IN_FILES_ZERO_FILES": "Filtar isključuje sve datoteke {0}",
  "FIND_IN_FILES_FILE": "datoteci",
  "FIND_IN_FILES_FILES": "datoteka",
  "FIND_IN_FILES_MATCH": "poklapanje",
  "FIND_IN_FILES_MATCHES": "poklapanja",
  "FIND_IN_FILES_MORE_THAN": "Preko ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Ctrl/Cmd klikni da proširiš/skupiš sve",
  "FIND_IN_FILES_INDEXING": "Indeksiranje za Instant Search...",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Indeksiranje {0} od {1} datoteka za Instant pretraživanje…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Zamijeni pogreške",
  "REPLACE_IN_FILES_ERRORS": "Sljedeće datoteke nisu izmijenjene jer su se promijenile nakon pretraživanja ili ih nije bilo moguće napisati.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Greška prilikom učitavanja informacija o novoj verziji",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Došlo je do problema prilikom preu