/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "Systemstandard",
  "PROJECT_BUSY": "Projektverksamhet pågår",
  "DUPLICATING": "Duplicerar {0}",
  "MOVING": "Flyttar {0}",
  "COPYING": "Kopierar {0}",
  "DELETING": "Raderar {0}",
  "RENAMING": "Byter namn",
  "GENERIC_ERROR": "(fel {0})",
  "NOT_FOUND_ERR": "Filen/mappen kunde inte hittas.",
  "NOT_READABLE_ERR": "Filen/mappen kunde inte läsas.",
  "EXCEEDS_MAX_FILE_SIZE": "Filer större än {0} MB kan inte öppnas i {APP_NAME}.",
  "NO_MODIFICATION_ALLOWED_ERR": "Målmappen kunde inte ändras.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Du har inte behörighet att modifiera filen.",
  "CONTENTS_MODIFIED_ERR": "Filen har ändrats utanför {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} stöder just nu bara textfiler kodade i UTF-8.",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} kunde inte koda innehållet i filen.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} kunde inte avkoda innehållet i filen.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} stöder för närvarande inte UTF-16-kodade textfiler.",
  "FILE_EXISTS_ERR": "Filen eller mappen existerar redan.",
  "FILE": "fil",
  "FILE_TITLE": "Arkiv",
  "DIRECTORY": "mapp",
  "DIRECTORY_TITLE": "Mapp",
  "DIRECTORY_NAMES_LEDE": "Mappnamn",
  "FILENAMES_LEDE": "Filnamn",
  "FILENAME": "filnamn",
  "DIRECTORY_NAME": "mappnamn",
  "ERROR_LOADING_PROJECT": "Projektet kunde inte öppnas",
  "OPEN_DIALOG_ERROR": "Ett fel inträffade när öppningsdialogen skulle visas. (fel {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Ett fel inträffade när mappen skulle öppnas <span class='dialog-filename'>{0}</span>. (fel {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Ett fel inträffade när mappens innehåll skulle läsas <span class='dialog-filename'>{0}</span>. (fel {1})",
  "ERROR_OPENING_FILE_TITLE": "Filen kunde inte öppnas",
  "ERROR_OPENING_FILE": "Ett fel inträffade när filen <span class='dialog-filename'>{0}</span> skulle öppnas. {1}",
  "ERROR_OPENING_FILES": "Ett fel inträffade när följande filer skulle öppnas:",
  "ERROR_RELOADING_FILE_TITLE": "Filen kunde inte laddas om",
  "ERROR_RELOADING_FILE": "Ett fel inträffade när filen <span class='dialog-filename'>{0}</span> skulle läsas om. {1}",
  "ERROR_SAVING_FILE_TITLE": "Filen kunde inte sparas",
  "ERROR_SAVING_FILE": "Ett fel inträffade när filen <span class='dialog-filename'>{0}</span> skulle sparas. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Filen kunde inte döpas om",
  "ERROR_RENAMING_FILE": "Ett fel uppstod när {2}-filen <span class='dialog-filename'>{0}</span> skulle döpas om. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Filen eller mappen är inte del av det öppna projektet. Tyvärr kan bara projektfiler döpas om för närvarande.",
  "ERROR_MOVING_FILE_TITLE": "Det gick inte att flytta {0}",
  "ERROR_MOVING_FILE": "Ett fel uppstod när du försökte flytta {2} <span class='dialog-filename'>{0}</span> . {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Kan inte flytta filen/mappen, eftersom de inte är en del av det aktuella projektet.",
  "ERROR_DELETING_FILE_TITLE": "Filen kunde inte raderas",
  "ERROR_DELETING_FILE": "Ett fel uppstod när {2}-filen <span class='dialog-filename'>{0}</span> skulle tas bort. {1}",
  "INVALID_FILENAME_TITLE": "Ogiltigt {0}",
  "CANNOT_PASTE_TITLE": "Kan inte klistra in {0}",
  "CANNOT_DOWNLOAD_TITLE": "Kan inte ladda ned {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "Ett fel uppstod vid nedladdning av <span class='dialog-filename'>{0}</span>",
  "ERR_TYPE_PASTE_FAILED": "Ett fel uppstod när <span class='dialog-filename'>{0}</span> skulle klistras in i <span class='dialog-filename'>{1}</span>",
  "CANNOT_DUPLICATE_TITLE": "Kan inte duplicera",
  "ERR_TYPE_DUPLICATE_FAILED": "Ett fel uppstod vid duplicering av <span class='dialog-filename'>{0}</span>",
  "INVALID_FILENAME_MESSAGE": "{0} får inte innehålla ord som reserverats av systemet, sluta med punkt (.) eller använda något av följande tecken: <code class='emphasized'>{1}</code>.",
  "ENTRY_WITH_SAME_NAME_EXISTS": "En fil eller mapp med namnet <span class='dialog-filename'>{0}</span> existerar redan.",
  "ERROR_CREATING_FILE_TITLE": "Kunde inte skapa {0}",
  "ERROR_CREATING_FILE": "Ett fel uppstod när en {0} med namnet <span class='dialog-filename'>{1}</span> skulle skapas. {2}",
  "ERROR_MIXED_DRAGDROP": "Kan inte öppna en mapp samtidigt som andra filer öppnas.",
  "ERROR_KEYMAP_TITLE": "Fel uppstod när användarens tangentuppsättning lästes in",
  "ERROR_KEYMAP_CORRUPT": "Din tangentuppsättningsfil är inte korrekt formaterad JSON. Filen kommer att öppnas så att du kan åtgärda formateringsfelet.",
  "ERROR_LOADING_KEYMAP": "Din tangentuppsättningsfil är inte en UTF-8-kodad textfil och kan inte läsas",
  "ERROR_RESTRICTED_COMMANDS": "Du kan inte ändra kortkommandot för följande kommandon: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Du kan inte ändra följande kortkommandon: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Du håller på att koppla flera kortkommandon till följande kommandon: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Du har flera kopplingar till följande kommandon: {0}",
  "ERROR_INVALID_SHORTCUTS": "Följande kortkommandon är felaktiga: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Du håller på att skapa kortkommandon till följande icke-existerande kommandon: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Kunde inte läsa inställningar",
  "ERROR_PREFS_CORRUPT": "Din inställningsfil är inte korrekt formaterad JSON. Filen kommer att öppnas så att du kan korrigera felet. Du kommer att behöva starta om {APP_NAME} för att ändringarna ska träda i kraft.",
  "ERROR_PROJ_PREFS_CORRUPT": "Dina projektinställningar är inte giltig JSON. Filen kommer att öppnas så att du kan rätta till formatet. Du behöver ladda om projektet för att ändringarna ska träda i kraft.",
  "ERROR_IN_BROWSER_TITLE": "Ajdå! {APP_NAME} körs inte i webbläsaren ännu.",
  "ERROR_IN_BROWSER": "{APP_NAME} är byggd i HTML, men körs just nu som en skrivbordsapplikation så att du kan använda den för att redigera lokala filer. Vänligen använd skalapplikationen <b>github.com/adobe/brackets-shell</b> för att köra {APP_NAME}.",
  "ERROR_MAX_FILES_TITLE": "Fel vid indexering av filer",
  "ERROR_MAX_FILES": "Det maximala antalet filer har indexerats. Funktioner som använder sig av indexet kanske inte kommer att fungera som förväntat.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Webbläsaren kunde inte öppnas.",
  "ERROR_CANT_FIND_CHROME": "Google Chrome kunde inte hittas. Kontrollera att den är installerad.",
  "ERROR_LAUNCHING_BROWSER": "Ett fel inträffade då webbläsaren skulle startas. (fel {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Förhandsvisning misslyckades",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Ansluter till webbläsaren",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "För att förhandsvisningen ska lyckas måste Chrome startas om med fjärrfelsökning aktiverad.<br /><br />Vill du starta om Chrome och aktivera fjärrfelsökning?",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Lyckades inte ladda förhandsvisningssidan.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "För att starta förhandsvisningen med en fil innehållande serverkod måste du ange en bas-URL för detta projekt.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Ett fel uppstod när webbsevern för förhandsvisningen skulle startas. Vänligen försök igen.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "För mer information se <a href='{0}' title='{0}'>Troubleshooting Live Development connection errors</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Förhandsvisning",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Förhandsvisning: Ansluter…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Förhandsvisning: Initierar…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Koppla från förhandsvisningen",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Förhandsvisning",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Välj File To Live Preview",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Ladda om sidan",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Växla Live Preview Highlights",
  "LIVE_DEV_CLICK_POPOUT": "Popout Live Preview till nytt fönster",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Fäst på Unpin Preview Page",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Förhandsvisning (uppdateras inte på grund av syntaxfel)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Förhandsvisningen avbröts eftersom webbläsarens utvecklarverktyg öppnades.",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Förhandsvisningen avbröts eftersom sidan stängdes i webbläsaren.",
  "LIVE_DEV_NAVIGATED_AWAY": "Förhandsvisningen avbröts eftersom webbläsaren navigerades till en sida som inte är del av det nuvarande projektet.",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Förhandsvisningen avbröts på grund av ett okänt fel. ({0})",
  "SAVE_CLOSE_TITLE": "Spara ändringar?",
  "SAVE_CLOSE_MESSAGE": "Vill du spara de ändringar i dokumentet <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Vill du spara ändringarna du gjort följande filer?",
  "EXT_MODIFIED_TITLE": "Externa ändringar",
  "CONFIRM_DELETE_TITLE": "Bekräfta borttagning",
  "CONFIRM_FILE_DELETE": "Är du säker att du vill radera filen <span class='dialog-filename'>{0}</span>?",
  "CONFIRM_FOLDER_DELETE": "Är du säker att du vill radera mappen <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "Filen raderades",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> har ändrats.<br /><br />Vill du spara filen och skriva över dessa ändringar?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> har ändrats men har också osparade ändringar i {APP_NAME}.<br /><br />Vilken version vill du behålla?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> har raderats man har också osparade ändringar i {APP_NAME}.<br /><br />Vill du behålla dina ändringar?",
  "WINDOW_UNLOAD_WARNING": "Är du säker på att du vill navigera till en annan URL och lämna parenteser?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Du har osparade ändringar! Är du säker på att du vill navigera till en annan URL och lämna parenteser?",
  "DONE": "Klar",
  "OK": "OK",
  "CANCEL": "Avbryt",
  "DONT_SAVE": "Spara inte",
  "SAVE": "Spara",
  "SAVE_AS": "Spara som…",
  "SAVE_AND_OVERWRITE": "Skriv över",
  "DELETE": "Radera",
  "BUTTON_YES": "Ja",
  "BUTTON_NO": "Nej",
  "FIND_MATCH_INDEX": "{0} av {1}",
  "FIND_NO_RESULTS": "Inga träffar",
  "FIND_QUERY_PLACEHOLDER": "Sök…",
  "FIND_HISTORY_MAX_COUNT": "Maximalt antal poster i sökhistoriken",
  "REPLACE_PLACEHOLDER": "Ersätt med…",
  "BUTTON_REPLACE_ALL": "Alla…",
  "BUTTON_REPLACE_BATCH": "Omgång…",
  "BUTTON_REPLACE_ALL_IN_FILES": "Ersätt…",
  "BUTTON_REPLACE": "Ersätt",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Nästa träff",
  "BUTTON_PREV_HINT": "Föregående träff",
  "BUTTON_CASESENSITIVE_HINT": "Skiftlägeskänslig",
  "BUTTON_REGEXP_HINT": "Regular Expression",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Ersätt utan att ångra",
  "REPLACE_WITHOUT_UNDO_WARNING": "Eftersom mer än {0} filer ändras kommer {APP_NAME} ändra dessa utan att de öppnas.<br />Du kommer inte att kunna ånga ändringarna i dessa filer.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Ersätt utan att ångra",
  "OPEN_FILE": "Öppna fil",
  "SAVE_FILE_AS": "Spara fil som",
  "CHOOSE_FOLDER": "Välj mapp",
  "RELEASE_NOTES": "Versionsinformation",
  "NO_UPDATE_TITLE": "Du är uppdaterad!",
  "NO_UPDATE_MESSAGE": "Du använder den senaste versionen av {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "Ersätt",
  "FIND_REPLACE_TITLE_WITH": "med",
  "FIND_TITLE_LABEL": "Hittades",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} i {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "i <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "i projekt",
  "FIND_IN_FILES_ZERO_FILES": "Filter exkluderar alla filer {0}",
  "FIND_IN_FILES_FILE": "fil",
  "FIND_IN_FILES_FILES": "filer",
  "FIND_IN_FILES_MATCH": "träff",
  "FIND_IN_FILES_MATCHES": "träffar",
  "FIND_IN_FILES_MORE_THAN": "Mer än ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Ctrl/Cmd-klicka för att expandera/minimera alla",
  "FIND_IN_FILES_INDEXING": "Indexerar för Instan