/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "Idioma predeterminado",
  "PROJECT_BUSY": "Proyecto Operaciones En Progreso",
  "DUPLICATING": "Duplicando {0}",
  "MOVING": "Moviendo {0}",
  "COPYING": "Copiando {0}",
  "DELETING": "Eliminando {0}",
  "RENAMING": "Renombrar",
  "GENERIC_ERROR": "(error {0})",
  "NOT_FOUND_ERR": "No se pudo encontrar el archivo/directorio.",
  "NOT_READABLE_ERR": "No se pudo leer el archivo/directorio.",
  "EXCEEDS_MAX_FILE_SIZE": "Los archivos de más de {0} MB no se pueden abrir en {APP_NAME}.",
  "NO_MODIFICATION_ALLOWED_ERR": "El directorio de destino no se puede modificar.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Los permisos no permiten hacer modificaciones.",
  "CONTENTS_MODIFIED_ERR": "El archivo fue modificado fuera de {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} actualmente solo soporta archivos codificados como UTF-8.",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} no pudo codificar el contenido del archivo.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} no pudo descodificar el contenido del archivo.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} actualmente no admite archivos de texto codificados en UTF-16.",
  "FILE_EXISTS_ERR": "El archivo ya existe.",
  "FILE": "archivo",
  "FILE_TITLE": "Archivo",
  "DIRECTORY": "directorio",
  "DIRECTORY_TITLE": "directorio",
  "DIRECTORY_NAMES_LEDE": "nombres de directorios",
  "FILENAMES_LEDE": "nombres de archivos",
  "FILENAME": "nombre de archivo",
  "DIRECTORY_NAME": "nombre de directorio",
  "ERROR_LOADING_PROJECT": "Error abriendo el proyecto",
  "OPEN_DIALOG_ERROR": "Ha ocurrido un error al mostrar el aviso de apertura de archivo. (error {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Ha ocurrido un error al intentar abrir el directorio <span class='dialog-filename'>{0}</span>. (error {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Ha ocurrido un error al leer los contenidos del directorio <span class='dialog-filename'>{0}</span>. (error {1})",
  "ERROR_OPENING_FILE_TITLE": "Error abriendo el archivo",
  "ERROR_OPENING_FILE": "Ha ocurrido un error al intentar abrir el archivo <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Ha ocurrido un error al intentar abrir los siguientes archivos:",
  "ERROR_RELOADING_FILE_TITLE": "Error recargando cambios desde disco",
  "ERROR_RELOADING_FILE": "Ha ocurrido un error al intentar recargar el archivo <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Error guardando el archivo",
  "ERROR_SAVING_FILE": "Ha ocurrido un error al intentar guardar el archivo <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Error renombrando el {0}",
  "ERROR_RENAMING_FILE": "Ha ocurrido un error al intentar renombrar el {2} <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "El archivo o directorio no forma parte del proyecto abierto actualmente. Desafortunadamente, solo los archivos de proyecto se pueden renombrar en este punto.",
  "ERROR_MOVING_FILE_TITLE": "Error al mover {0}",
  "ERROR_MOVING_FILE": "Ocurrió un error al intentar mover el {2} <span class='dialog-filename'>{0}</span> . {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "No se puede mover el archivo o la carpeta, ya que no forman parte del proyecto actual.",
  "ERROR_DELETING_FILE_TITLE": "Error eliminando el {0}",
  "ERROR_DELETING_FILE": "Ha ocurrido un error al intentar eliminar el {2} <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "{0} inválido",
  "CANNOT_PASTE_TITLE": "No se puede pegar {0}",
  "CANNOT_DOWNLOAD_TITLE": "No se puede descargar {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "Ocurrió un error al descargar <span class='dialog-filename'>{0}</span>",
  "ERR_TYPE_PASTE_FAILED": "Ocurrió un error al pegar <span class='dialog-filename'>{0}</span> a <span class='dialog-filename'>{1}</span>",
  "CANNOT_DUPLICATE_TITLE": "no se puede duplicar",
  "ERR_TYPE_DUPLICATE_FAILED": "Ocurrió un error al duplicar <span class='dialog-filename'>{0}</span>",
  "INVALID_FILENAME_MESSAGE": "Los {0} no pueden utilizar ninguna palabra reservada por el sistema, terminar con puntos (.) o utilizar cualquiera de los siguientes caracteres: <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Ya existe un archivo o directorio con el nombre <span class='dialog-filename'>{0}</span>.",
  "ERROR_CREATING_FILE_TITLE": "Error creando {0}",
  "ERROR_CREATING_FILE": "Ha ocurrido un error al intentar crear el {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "No es posible abrir una carpeta y otros archivos al mismo tiempo.",
  "ERROR_KEYMAP_TITLE": "Ocurrió un error leyendo los atajos de teclado",
  "ERROR_KEYMAP_CORRUPT": "El archivo de atajos de teclado no tiene un formato JSON válido. El archivo se abrirá para que puedas corregir el formato.",
  "ERROR_LOADING_KEYMAP": "El archivo de atajos de teclado no está codificado como UTF-8 y no puede ser cargado.",
  "ERROR_RESTRICTED_COMMANDS": "No puedes reasignar atajos de teclado a los siguientes comandos: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "No puedes reasignar los siguientes atajos de teclado: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Estas reasignando múltiples atajos de teclado a los siguientes comandos: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Hay múltiples apariciones de los siguientes atajos de teclado: {0}",
  "ERROR_INVALID_SHORTCUTS": "Los siguientes atajos de teclado son inválidos: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Estas asignando atajos de teclado a commandos inexistentes: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Error leyendo las preferencias",
  "ERROR_PREFS_CORRUPT": "El archivo de preferencias no tiene un formato JSON válido. El archivo se abrirá para que puedas corregir el formato. Luego deberás reiniciar {APP_NAME} para que los cambios surtan efecto.",
  "ERROR_PROJ_PREFS_CORRUPT": "El archivo de preferencias para el proyecto no tiene un formato JSON válido. El archivo se abrirá para que puedas corregir el formato. Luego deberás recargar el proyecto para que los cambios surtan efecto.",
  "ERROR_IN_BROWSER_TITLE": "Vaya... parece que {APP_NAME} todavía no funciona en navegadores.",
  "ERROR_IN_BROWSER": "{APP_NAME} está desarrollado en HTML, pero por ahora funciona como una aplicación de escritorio para que puedas editar archivos localmente. Por favor, utiliza la aplicación del repositorio <b>github.com/adobe/brackets-shell</b> para ejecutar {APP_NAME}.",
  "ERROR_MAX_FILES_TITLE": "Error indexando archivos",
  "ERROR_MAX_FILES": "Este proyecto contiene más de 30.000 archivos. Funciones que operan sobre múltiples archivos pueden estar deshabilitadas o funcionar igual que si el proyecto estuviese vacío. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>Leer más acerca de cómo trabajar con proyectos grandes</a>.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Error iniciando el navegador",
  "ERROR_CANT_FIND_CHROME": "No se pudo encontrar el navegador Google Chrome. Por favor, asegúrate que esté instalado correctamente.",
  "ERROR_LAUNCHING_BROWSER": "Ha ocurrido un error al iniciar el navegador. (error {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Error en la Vista previa dinámica",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Conectando con el navegador",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Para poder iniciar el modo de Vista previa dinámica, Chrome debe ser iniciado habilitando la depuración remota.<br><br>¿Quieres reiniciar Chrome y habilitar la depuración remota?<br><br>",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "No se pudo cargar la página para la Vista previa dinámica.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "Necesitas especificar una URL base en este proyecto para poder iniciar la Vista previa dinámica con archivos de servidor.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Error iniciando el servidor HTTP para la Vista previa dinámica. Vuelve a intentarlo, por favor.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Para más información, consulta <a href='{0}' title='{0}'>Resolución de Problemas de conexión en Vista previa dinámica</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Vista previa dinámica",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Vista previa dinámica: Conectando…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Vista previa dinámica: Inicializando…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Terminar la Vista previa dinámica",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Vista previa dinámica",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Seleccionar archivo para vista previa en vivo",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Recargar página",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Toggle Destacados de vista previa en vivo",
  "LIVE_DEV_CLICK_POPOUT": "Vista previa emergente en vivo a una nueva ventana",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Pin en Unpin Preview Page",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Vista previa dinámica (no se está actualizando debido a un error de sintaxis)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Vista previa dinámica se ha detenido porque se han abierto las herramientas de desarrollo",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Vista previa dinámica se ha detenido porque se ha cerrado la página en el navegador",
  "LIVE_DEV_NAVIGATED_AWAY": "Vista previa dinámica se ha detenido porque se ha accedido a una página que no es parte del proyecto actual",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Vista previa dinámica se ha detenido por motivos desconocidos ({0})",
  "SAVE_CLOSE_TITLE": "Guardar cambios",
  "SAVE_CLOSE_MESSAGE": "¿Quieres guardar los cambios existentes en el documento <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "¿Quieres guardar tus cambios en los siguientes documentos?",
  "EXT_MODIFIED_TITLE": "Cambios externos",
  "CONFIRM_DELETE_TITLE": "Confirmar eliminación",
  "CONFIRM_FILE_DELETE": "¿Está seguro de que desea eliminar el archivo <span class='dialog-filename'>{0}</span> ?",
  "CONFIRM_FOLDER_DELETE": "¿Estás seguro que deseas eliminar el directorio <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "Archivo eliminado",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> ha sido modificado en el disco fuera de {APP_NAME}.<br><br>¿Deseas guardar el archivo y sobrescribir esos cambios?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> ha sido modificado en el disco fuera de {APP_NAME}, pero también tiene cambios en {APP_NAME}.<br><br>¿Qué versión quieres conservar?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> ha sido eliminado en el disco fuera de {APP_NAME}, pero tiene cambios sin guardar en {APP_NAME}.<br><br>¿Quieres conservar tus cambios?",
  "WINDOW_UNLOAD_WARNING": "¿Está seguro de que desea navegar a una URL diferente y salir de Brackets?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "¡Usted tiene cambios no guardados! ¿Está seguro de que desea navegar a una URL diferente y salir de Brackets?",
  "DONE": "Aceptar",
  "OK": "Aceptar",
  "CANCEL": "Cancelar",
  "DONT_SAVE": "No guardar",
  "SAVE": "Guardar",
  "SAVE_AS": "Guardar como…",
  "SAVE_AND_OVERWRITE": "Sobrescribir",
  "DELETE": "Eliminar",
  "BUTTON_YES": "Sí",
  "BUTTON_NO