/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "Preferita dal sistema",
  "PROJECT_BUSY": "Operazioni di progetto in corso",
  "DUPLICATING": "Duplicazione {0}",
  "MOVING": "Spostamento {0}",
  "COPYING": "Copia {0}",
  "DELETING": "Eliminazione di {0}",
  "RENAMING": "Rinominare",
  "GENERIC_ERROR": "(errore {0})",
  "NOT_FOUND_ERR": "Impossibile trovare il file o la cartella.",
  "NOT_READABLE_ERR": "Impossibile leggere il file o la cartella.",
  "EXCEEDS_MAX_FILE_SIZE": "File oltre {0} MB non possono essere aperti con {APP_NAME}.",
  "NO_MODIFICATION_ALLOWED_ERR": "La cartella selezionata non può essere modificata.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Non hai i permessi necessari per effettuare la modifica.",
  "CONTENTS_MODIFIED_ERR": "Il file è stato modificato fuori {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "Attualmente {APP_NAME} supporta solo testo codificato in UTF-8",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} non è stato in grado di codificare il contenuto del file.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} non è stato in grado di decodificare il contenuto del file.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "{APP_NAME} attualmente non supporta i file di testo con codifica UTF-16.",
  "FILE_EXISTS_ERR": "Il file o la cartella è già presente.",
  "FILE": "file",
  "FILE_TITLE": "File",
  "DIRECTORY": "cartella",
  "DIRECTORY_TITLE": "Cartella",
  "DIRECTORY_NAMES_LEDE": "nomi delle cartelle",
  "FILENAMES_LEDE": "nomi dei file",
  "FILENAME": "nome del file",
  "DIRECTORY_NAME": "nome della cartella",
  "ERROR_LOADING_PROJECT": "Errore durante il caricamento del progetto",
  "OPEN_DIALOG_ERROR": "Errore durante il caricamento della finestra di dialogo per l’apertura del file. (errore {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Errore durante il tentativo di caricare la cartella <span class='dialog-filename'>{0}</span>. (errore {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Errore durante la lettura del contenuto della cartella <span class='dialog-filename'>{0}</span>. (errore {1})",
  "ERROR_OPENING_FILE_TITLE": "Errore durante l’apertura del file",
  "ERROR_OPENING_FILE": "Errore durante il tentativo di apertura del file <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Errore durante il tentativo di apertura dei seguenti file:",
  "ERROR_RELOADING_FILE_TITLE": "Errore durante il caricamento delle modifiche dal disco",
  "ERROR_RELOADING_FILE": "Errore durante il tentativo di ricaricare il file <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Errore durante il salvataggio del file",
  "ERROR_SAVING_FILE": "Errore durante il tentativo di salvare il file <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Errore durante il tentativo di rinominare il file",
  "ERROR_RENAMING_FILE": "Errore durante il tentativo di rinominare il file <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Il file o la directory non fa parte del progetto attualmente aperto. Sfortunatamente, solo i file di progetto possono essere rinominati a questo punto.",
  "ERROR_MOVING_FILE_TITLE": "Errore durante lo spostamento di {0}",
  "ERROR_MOVING_FILE": "Si è verificato un errore durante il tentativo di spostare {2} <span class='dialog-filename'>{0}</span> . {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Impossibile spostare il file/la cartella, poiché non fanno parte del progetto corrente.",
  "ERROR_DELETING_FILE_TITLE": "Errore durante il tentativo di eliminazione del file",
  "ERROR_DELETING_FILE": "Errore durante il tentativo di eliminazione del file <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "Il {0} non è valido",
  "CANNOT_PASTE_TITLE": "Impossibile incollare {0}",
  "CANNOT_DOWNLOAD_TITLE": "Impossibile scaricare {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "Si è verificato un errore durante il download di <span class='dialog-filename'>{0}</span>",
  "ERR_TYPE_PASTE_FAILED": "Si è verificato un errore durante l&#39;incollaggio di <span class='dialog-filename'>{0}</span> in <span class='dialog-filename'>{1}</span>",
  "CANNOT_DUPLICATE_TITLE": "Impossibile duplicare",
  "ERR_TYPE_DUPLICATE_FAILED": "Si è verificato un errore durante la duplicazione di <span class='dialog-filename'>{0}</span>",
  "INVALID_FILENAME_MESSAGE": "I {0} non possono usare caratteri di sistema riservati, finire con un punto (.) o contenere i seguenti caratteri: <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Il file o la cartella <span class='dialog-filename'>{0}</span> esiste già.",
  "ERROR_CREATING_FILE_TITLE": "Errore durante la creazione del file",
  "ERROR_CREATING_FILE": "Errore durante il tentativo di creare il file <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_MIXED_DRAGDROP": "Impossibile aprire una cartella contemporaneamente all'apertura di altri file.",
  "ERROR_KEYMAP_TITLE": "Errore nella lettura del Key Map",
  "ERROR_KEYMAP_CORRUPT": "Il tuo file non è in formato JSON valido. Il file sarà riaperto per poter correggere il formato.",
  "ERROR_LOADING_KEYMAP": "La tua Key Map non è un file UTF-8 valido e non può essere caricato",
  "ERROR_RESTRICTED_COMMANDS": "Non puoi riassegnare queste scorciatoie: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Non puoi riassegnare delle scorciatoie a questi comandi: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Stai riassegnando più di una scorciatoia a questi comandi:: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Possiedi più possibilità in queste scorciatoie: {0}",
  "ERROR_INVALID_SHORTCUTS": "Queste scorciatoie non sono valide: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Stai assegnando scorciatoie a comandi inesistenti: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Errore nella lettura delle preferenze",
  "ERROR_PREFS_CORRUPT": "Le tue preferenze non sono in un file JSON valido. Il file verrà aperto in modo da poter correggere il formato. Dovrai riavviare {APP_NAME} affinché le modifiche abbiano effetto.",
  "ERROR_PROJ_PREFS_CORRUPT": "Le preferenze del progetto non sono in un file JSON valido. Il file verrà aperto in modo da poter correggere il formato. Dovrai riavviare {APP_NAME} affinché le modifiche abbiano effetto.",
  "ERROR_IN_BROWSER_TITLE": "Oops! {APP_NAME} non può essere ancora eseguita nel browser.",
  "ERROR_IN_BROWSER": "{APP_NAME} è scritta in HTML, ma al momento viene eseguita come applicazione desktop per avere la possibilità di modificare file locali. Puoi usare la shell dal repository <b>github.com/adobe/brackets-shell</b> per eseguire {APP_NAME}.",
  "ERROR_MAX_FILES_TITLE": "Errore durante l’indicizzazione dei file",
  "ERROR_MAX_FILES": "È stato raggiunto il massimo numero di file indicizzati. Le azioni che controllano file presenti nell’indice posso funzionare in modo non corretto.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Errore durante l’avvio del browser",
  "ERROR_CANT_FIND_CHROME": "Non è stato possibile trovare il browser Google Chrome. Assicurarsi che sia correttamente installato.",
  "ERROR_LAUNCHING_BROWSER": "Errore durante l’avvio del browser. (errore {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Errore durante l’Anteprima Live",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Connessione al Browser in corso",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Per effettuare una connessione con Anteprima Live, Chrome deve essere rilanciato con il debugging remoto abilitato.<br /><br />Vuoi rilanciare Chrome e abilitare il debugging remoto?",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Impossibile caricare l'Anteprima Live",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "Per avviare l'Anteprima Live con un file server-side, è necessario specificare un URL di base per questo progetto.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Errore durante l’avvio del server HTTP server per i file di sviluppo in tempo reale. Riprova ancora.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Per maggiori informazioni leggi <a href='{0}' title='{0}'>Risoluzione dei problemi di connessione a Anteprima Live</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Anteprima Live",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Anteprima Live: Connessione…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Anteprima Live: Inizializzazione…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Disconnetti Anteprima Live",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Anteprima Live",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Seleziona File in anteprima dal vivo",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Ricarica la pagina",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Attiva/disattiva i momenti salienti dell'anteprima dal vivo",
  "LIVE_DEV_CLICK_POPOUT": "Anteprima dal vivo popout in una nuova finestra",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Appunta sulla pagina di anteprima Sblocca",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Anteprima Live (non aggiorna a causa di un errore di sintassi)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "L’Anteprima Live è stata cancellata perché uno strumento di sviluppo è stato aperto nel browser",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "L’Anteprima Live è stata cancellata perché è stato chiuso il browser",
  "LIVE_DEV_NAVIGATED_AWAY": "L’Anteprima Live è stata cancellata perché il browser ha caricato una pagina che non fa parte del progetto corrente",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "L’Anteprima Live è stata cancellata a causa di un errore sconosciuto ({0})",
  "SAVE_CLOSE_TITLE": "Salva le modifiche",
  "SAVE_CLOSE_MESSAGE": "Vuoi cambiare le modifiche apportate al file <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Vuoi cambiare le modifiche apportate ai seguenti file?",
  "EXT_MODIFIED_TITLE": "Modifiche esterne",
  "CONFIRM_DELETE_TITLE": "Confermi l'eliminazione?",
  "CONFIRM_FILE_DELETE": "Sei sicuro di voler eliminare il file <span class='dialog-filename'>{0}</span> ?",
  "CONFIRM_FOLDER_DELETE": "Sei sicuro di eliminare la cartella <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "File Eliminato",
  "EXT_MODIFIED_WARNING": "<span class='dialog-filename'>{0}</span> è stato modificato sul disco.<br /><br />Vuoi salvare il file e sovrascrivere le modifiche?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> è stato modificato sul disco ma ha delle modifiche non ancora salvate in {APP_NAME}.<br /><br />Quale versione vuoi tenere?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> è stato eliminato sul disco ma ha delle modifiche non ancora salvate in {APP_NAME}.<br /><br />Vuoi mantenere le tue modifiche?",
  "WINDOW_UNLOAD_WARNING": "Sei sicuro di voler passare a un URL diverso e lasciare le parentesi?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Hai modifiche non salvate! Sei sicuro di voler passare a un URL diverso e lasciare le parentesi?",
  "DONE": "Fatto",
  "OK": "OK",
  "CANCEL": "Annulla",
  "DONT_SAVE": "Non salvare",
  "SAVE": "Salva",
  "SAVE_AS": "Salva come…",
  "SAVE_AND_OVERWRITE": "Sovrascrivi",
  "DELETE": "Elimina",
  "BUTTON_YES": "Si",
  "BUTTON_NO": "No",
  "FIND_MATCH_INDEX": "{0} di {1}",
  "FIND_NO_RESULTS": "Nessun risultato",
  "FIND_QUERY_PLACEHOLDER": "Trova…",
  "FIND_HISTORY_MAX_COUNT": "Numero massimo di elementi di ricerca nella cronologia delle ricerche",
  "REPLACE_PLACEHOLDER": "Sostituisci con…",
  "BUTTON_REPLACE_ALL": "Tutti…",
  "BUTTON_REPLACE_BATCH": "Lotto…",
  "BUTTON_REPLACE_ALL_IN_FILES": "Sostituire…",
  "BUTTON_REPLACE": "Sostituisci",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Corrispondenza successiva",
  "BUTTON_PREV_HINT": "Corrispondenza precedente",
  "BUTTON_CASESENSITIVE_HINT": "Rispetta maiuscole/minuscole",
  "BUTTON_REGEXP_HINT": "Espressione regolare",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Sostituire senza Annullare",
  "REPLACE_WITHOUT_UNDO_WARNING": "Poichè più di {0} file deve essere modificato, {APP_NAME} modificherà i file aperti sul disco.<br />Non sarai in grado di annullare le modifiche in quei file.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Sostituire senza Annullare",
  "OPEN_FILE": "Apri File",
  "SAVE_FILE_AS": "Salva File",
  "CHOOSE_FOLDER": "Scegli una cartella",
  "RELEASE_NOTES": "Note di rilascio",
  "NO_UPDATE_TITLE": "Sei aggiornato!",
  "NO_UPDATE_MESSAGE": "Stai utilizzando l’ultima versione di {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "Sostituisci",
  "FIND_REPLACE_TITLE_WITH": "con",
  "FIND_TITLE_LABEL": "Trovato",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} in {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "in <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "nel progetto",
  "FIND_IN_FILES_ZERO_FILES": "Filtra esclude tutti i file {0}",
  "FIND_IN_FILES_FILE": "file",
  "FIND_IN_FILES_FILES": "file",
  "FIND_IN_FILES_MATCH": "corrispondenza",
  "FIND_IN_FILES_MATCHES": "corrispondenze",
  "FIND_IN_FILES_MORE_THAN": "Oltre ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Ctrl/Cmd click per Espandere/Comprimi tutto",
  "FIND_IN_FILES_INDEXING": "Indicizzazione per ricerca immediata…",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Indicizzazione di {0} di {1} file per la ricerca istantanea...",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Sostituire errori",
  "REPLACE_IN_FILES_ERRORS": "I seguenti file non sono stati modificati perché hanno cambiato dopo la ricerca o non potevano essere scritti.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Si è verificato un errore nel recuperare le informazioni aggiornate",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Si è verificato un errore nel recuperare le informazioni aggiornate dal server. Assicurati di essere connesso a internet e riprova.",
  "NEW_FILE_FILTER": "Nuova regola di esclusione…",
  "CLEAR_FILE_FILTER": "Non escludere file",
  "NO_FILE_FILTER": "Nessun file escluso",
  "EXCLUDE_FILE_FILTER": "Escludere {0}",
  "EDIT_FILE_FILTER": "Modifica…",
  "FILE_FILTER_DIALOG": "Modifica regole di esclusione",
  "FILE_FILTER_INSTRUCTIONS": "Esclusione di file e cartelle corrispondenti delle seguenti stringhe o sottostringhe <a href='{0}' title='{0}'>caratteri jolly</a>. Immettere ogni stringa su una nuova linea.",
  "FILTER_NAME_PLACEHOLDER": "Nome delle regole di esclusione (facoltativo)",
  "FILTER_NAME_REMAINING": "{0} caratteri rimanenti",
  "FILE_FILTER_CLIPPED_SUFFIX": "e {0} più",
  "FILTER_COUNTING_FILES": "Contando i file…",
  "FILTER_FILE_COUNT": "Consentire {0} di {1} file {2}",
  "FILTER_FILE_COUNT_ALL": "Consentire tutti {0} file {1}",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Quick Edit non disponibile per posizione attuale del cursore",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "CSS Quick Edit: posiziona il cursore sul nome di una classe singola.",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "CSS Quick Edit: attributo classe incompleto",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "CSS Quick Edit: attributo id incompleto",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "CSS Quick Edit: posiziona il cursore su etichetta, classe, oppure id",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "Funzione CSS Timing Quick Edit: sintassi invalida",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "JS Quick Edit: posiziona il cursore su nome della Funzione",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Quick Docs non disponibile per posizione attuale del cursore",
  "PROJECT_LOADING": "Caricamento…",
  "UNTITLED": "Senza titolo",
  "WORKING_FILES": "File attivi",
  "TOP": "Superiore",
  "BOTTOM": "Inferiore",
  "LEFT": "Sinistra",
  "RIGHT": "Destra",
  "CMD_SPLITVIEW_NONE": "Nessuna Divisione",
  "CMD_SPLITVIEW_VERTICAL": "Dividere Verticalmente",
  "CMD_SPLITVIEW_HORIZONTAL": "Dividere Orizzontalmente",
  "SPLITVIEW_MENU_TOOLTIP": "Dividere l'editor verticalmente oppure orizzontalmente",
  "GEAR_MENU_TOOLTIP": "Configura le impostazioni di lavoro",
  "SPLITVIEW_INFO_TITLE": "Già aperto",
  "SPLITVIEW_MULTIPANE_WARNING": "Il file è già aperto in un altro riquadro. {APP_NAME} sarà presto possibile aprire lo stesso file in più di un riquadro. Fino ad allora, il file verrà mostrato nel riquadro che è già aperto.<br /><br />(Tu vedrai questo messaggio solo una volta.)",
  "STATUSBAR_CURSOR_POSITION": "Linea {0}, Colonna {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — Selezionata {0} colonna",
  "STATUSBAR_SELECTION_CH_PLURAL": " — Selezionate {0} colonne",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — Selezionata {0} linea",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — Selezionate {0} linee",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} selezioni",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Clicca per passare alla indentazione a spazi",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Clicca per passare alla indentazione a tabulazione",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Clicca per cambiare il numero di spazi usati per l’indentazione",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Clicca per cambiare la ampiezza della tabulazione",
  "STATUSBAR_SPACES": "Spazi",
  "STATUSBAR_TAB_SIZE": "Ampiezza tabulazione:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} Linea",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} Linee",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Estensioni disabilitate",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "OVR",
  "STATUSBAR_INSOVR_TOOLTIP": "Fare clic per cambiare il cursore tra la modalità Inserisci (INS) e Sovrascrivi (OVR)",
  "STATUSBAR_LANG_TOOLTIP": "Clicca per cambiare il tipo di file",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Clicca per attivare pannello dei report.",
  "STATUSBAR_DEFAULT_LANG": "(default)",
  "STATUSBAR_SET_DEFAULT_LANG": "Imposta come predefinito per .{0} File",
  "STATUSBAR_ENCODING_TOOLTIP": "Seleziona la codifica",
  "ERRORS_PANEL_TITLE_MULTIPLE": "{0} Problemi",
  "SINGLE_ERROR": "1 {0} Problema",
  "MULTIPLE_ERRORS": "{1} {0} Problemi",
  "NO_ERRORS": "Nessun {0} problema trovato - ottimo lavoro!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Nessun problema trovato - ottimo lavoro!",
  "LINT_DISABLED": "Lint disabilitato",
  "NO_LINT_AVAILABLE": "Lint disponibile {0}",
  "NOTHING_TO_LINT": "Niente dal Lint",
  "LINTER_TIMED_OUT": "{0} è scaduto dopo aver atteso per {1} ms",
  "LINTER_FAILED": "{0} terminato con errore: {1}",
  "FILE_MENU": "File",
  "CMD_FILE_NEW_UNTITLED": "Nuovo",
  "CMD_FILE_NEW": "Nuovo File",
  "CMD_FILE_DUPLICATE": "Duplica",
  "CMD_FILE_DOWNLOAD_PROJECT": "Scarica Progetto",
  "CMD_FILE_DOWNLOAD": "Scarica",
  "CMD_FILE_CUT": "Taglia",
  "CMD_FILE_COPY": "Copia",
  "CMD_FILE_COPY_PATH": "Copia percorso",
  "CMD_FILE_PASTE": "Incolla",
  "CMD_PROJECT_NEW": "Nuovo progetto",
  "CMD_FILE_NEW_FOLDER": "Nuova cartella",
  "CMD_FILE_OPEN": "Apri…",
  "CMD_RECENT_FILES_OPEN": "File recenti…",
  "CMD_ADD_TO_WORKING_SET": "Aggiungi all'area di lavoro",
  "CMD_OPEN_DROPPED_FILES": "Apri un file abbandonato",
  "CMD_OPEN_FOLDER": "Apri cartella…",
  "CMD_FILE_CLOSE": "Chiudi",
  "CMD_FILE_CLOSE_ALL": "Chiudi tutto",
  "CMD_FILE_CLOSE_LIST": "Chiudi lista",
  "CMD_FILE_CLOSE_OTHERS": "Chiudi tutto il resto",
  "CMD_FILE_CLOSE_ABOVE": "Chiudi tutto al di sopra",
  "CMD_FILE_CLOSE_BELOW": "Chiudi tutto al di sotto",
  "CMD_FILE_SAVE": "Salva File",
  "CMD_FILE_SAVE_ALL": "Salva tutto",
  "CMD_FILE_SAVE_AS": "Salva come…",
  "CMD_LIVE_FILE_PREVIEW": "Anteprima Live",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Abilita l'Anteprima Live nel tuo browser preferito (sperimentale)",
  "CMD_RELOAD_LIVE_PREVIEW": "Forza ricarica Anteprima Live",
  "CMD_PROJECT_SETTINGS": "Impostazioni del progetto…",
  "CMD_FILE_RENAME": "Rinomina",
  "CMD_FILE_DELETE": "Elimina",
  "CMD_INSTALL_EXTENSION": "Installa Estensioni…",
  "CMD_EXTENSION_MANAGER": "Manager delle Estensioni…",
  "CMD_FILE_REFRESH": "Ricarica il percorso file",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Ordina prima le cartelle",
  "CMD_QUIT": "Abbandona",
  "CMD_EXIT": "Esci",
  "EDIT_MENU": "Modifica",
  "CMD_UNDO": "Annulla",
  "CMD_REDO": "Ripristina",
  "CMD_CUT": "Taglia",
  "CMD_COPY": "Copia",
  "CMD_PASTE": "Incolla",
  "CMD_SELECT_ALL": "Seleziona tutto",
  "CMD_SELECT_LINE": "Seleziona riga",
  "CMD_SPLIT_SEL_INTO_LINES": "Dividi selezione dentro alle righe",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Aggiungi cursore alla riga successiva",
  "CMD_ADD_CUR_TO_PREV_LINE": "Aggiungi il cursore sulla riga precedente",
  "CMD_INDENT": "Aumenta indentazione",
  "CMD_UNINDENT": "Riduci indentazione",
  "CMD_DUPLICATE": "Duplica",
  "CMD_DELETE_LINES": "Elimina linea",
  "CMD_COMMENT": "Commenta/De-commenta linee",
  "CMD_BLOCK_COMMENT": "Commenta/De-commenta blocco",
  "CMD_LINE_UP": "Sposta la riga in alto",
  "CMD_LINE_DOWN": "Sposta la riga in basso",
  "CMD_OPEN_LINE_ABOVE": "Apri linea sopra",
  "CMD_OPEN_LINE_BELOW": "Apri linea sotto",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Chiudi le parentesi automaticamente",
  "CMD_SHOW_CODE_HINTS": "Mostra suggerimenti",
  "CMD_BEAUTIFY_CODE": "Abbellisci il codice",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "Abbellisci il codice dopo il salvataggio",
  "FIND_MENU": "Cerca",
  "CMD_FIND": "Cerca",
  "CMD_FIND_NEXT": "Cerca il successivo",
  "CMD_FIND_PREVIOUS": "Cerca il precedente",
  "CMD_FIND_ALL_AND_SELECT": "Trova tutto e seleziona",
  "CMD_ADD_NEXT_MATCH": "Aggiungi la prossima corrispondenza alla selezione",
  "CMD_SKIP_CURRENT_MATCH": "Salta e aggiungi prossima correspondenza",
  "CMD_FIND_IN_FILES": "Cerca nei file",
  "CMD_FIND_IN_SUBTREE": "Cerca in…",
  "CMD_REPLACE": "Sostituisci",
  "CMD_REPLACE_IN_FILES": "Sostituisci nei file",
  "CMD_REPLACE_IN_SUBTREE": "Sostituisci in…",
  "VIEW_MENU": "Vista",
  "CMD_HIDE_SIDEBAR": "Nascondi barra laterale",
  "CMD_SHOW_SIDEBAR": "Mostra barra laterale",
  "CMD_TOGGLE_SIDEBAR": "Apri/Chiudi la barra laterale",
  "CMD_TOGGLE_PANELS": "Apri/Chiudi i pannelli",
  "CMD_TOGGLE_PURE_CODE": "Nessuna distrazione",
  "CMD_INCREASE_FONT_SIZE": "Aumenta la dimensione del testo",
  "CMD_DECREASE_FONT_SIZE": "Diminuisci la dimensione del testo",
  "CMD_RESTORE_FONT_SIZE": "Ripristina la dimensione del testo",
  "CMD_SCROLL_LINE_UP": "Scorri verso l’alto",
  "CMD_SCROLL_LINE_DOWN": "Scorri verso il basso",
  "CMD_TOGGLE_LINE_NUMBERS": "Numeri linea",
  "CMD_TOGGLE_ACTIVE_LINE": "Evidenzia linea attiva",
  "CMD_TOGGLE_WORD_WRAP": "A capo automaticamente",
  "CMD_LIVE_HIGHLIGHT": "Ispezione Anteprima Live",
  "CMD_VIEW_TOGGLE_INSPECTION": "Lint Files al salvataggio",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Ordina per Aggiunta",
  "CMD_WORKINGSET_SORT_BY_NAME": "Ordina per Nome",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Ordina per Tipo",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Ordina Automaticamente",
  "CMD_THEMES": "Temi…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Chiudi automaticamente la ricerca",
  "NAVIGATE_MENU": "Naviga",
  "CMD_QUICK_OPEN": "Apri velocemente",
  "CMD_GOTO_LINE": "Vai alla linea",
  "CMD_GOTO_DEFINITION": "Vai alla definizione",
  "CMD_GOTO_DEFINITION_PROJECT": "Definizione di ricerca rapida nel progetto",
  "CMD_GOTO_FIRST_PROBLEM": "Vai al primo Errore/Avviso",
  "CMD_TOGGLE_QUICK_EDIT": "Modifica veloce",
  "CMD_TOGGLE_QUICK_DOCS": "Documentazione veloce",
  "CMD_QUICK_EDIT_PREV_MATCH": "Corrispondenza precedente",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Corrispondenza successiva",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Nuova regola",
  "CMD_NEXT_DOC": "Documento successivo",
  "CMD_PREV_DOC": "Documento precedente",
  "CMD_NAVIGATE_BACKWARD": "Naviga indietro",
  "CMD_NAVIGATE_FORWARD": "Naviga in avanti",
  "CMD_NEXT_DOC_LIST_ORDER": "Documento successivo nella lista",
  "CMD_PREV_DOC_LIST_ORDER": "Documento precedente nella lista",
  "CMD_SHOW_IN_TREE": "Mostra nell’albero dei file",
  "CMD_SHOW_IN_EXPLORER": "Mostra in Explorer",
  "CMD_SHOW_IN_FINDER": "Mostra in Finder",
  "CMD_SHOW_IN_OS": "Mostra in SO",
  "CMD_SWITCH_PANE_FOCUS": "Cambia lo stato attivo del riquadro",
  "CMD_OPEN_VFS": "Apri il file system virtuale",
  "CMD_OPEN_VIRTUAL_SERVER": "Apri il server virtuale",
  "HELP_MENU": "Aiuto",
  "CMD_CHECK_FOR_UPDATE": "Controlla aggiornamenti",
  "CMD_HOW_TO_USE_BRACKETS": "Come usare {APP_NAME}",
  "CMD_SUPPORT": "Supporto per {APP_NAME}",
  "CMD_SUGGEST": "Suggerisci una funzionalità",
  "CMD_RELEASE_NOTES": "Note di rilascio",
  "CMD_GET_INVOLVED": "Far parte",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Mostra cartella e