/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "Predvolený v systéme",
  "PROJECT_BUSY": "Operácie projektu prebiehajú",
  "DUPLICATING": "Duplikuje sa {0}",
  "MOVING": "Presúva sa {0}",
  "COPYING": "Kopíruje sa {0}",
  "DELETING": "Odstraňuje sa {0}",
  "RENAMING": "Premenovanie",
  "GENERIC_ERROR": "(chyba {0})",
  "NOT_FOUND_ERR": "Súbor nenájdený.",
  "NOT_READABLE_ERR": "Súbor sa nedá čítať.",
  "EXCEEDS_MAX_FILE_SIZE": "Súbory väčšie ako {0} MB nie je možné otvoriť v aplikácii {APP_NAME}.",
  "NO_MODIFICATION_ALLOWED_ERR": "Cieľový adresár nemôže byť zmenený.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Práva vám neumožňujú robiť zmeny.",
  "CONTENTS_MODIFIED_ERR": "Súbor bol upravený mimo aplikácie {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "Neznámy formát kódovania",
  "ENCODE_FILE_FAILED_ERR": "Aplikácii {APP_NAME} sa nepodarilo zakódovať obsah súboru.",
  "DECODE_FILE_FAILED_ERR": "Aplikácii {APP_NAME} sa nepodarilo dekódovať obsah súboru.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "Aplikácia {APP_NAME} momentálne nepodporuje textové súbory s kódovaním UTF-16.",
  "FILE_EXISTS_ERR": "Súbor alebo adresár už existuje.",
  "FILE": "súbor",
  "FILE_TITLE": "Súbor",
  "DIRECTORY": "adresár",
  "DIRECTORY_TITLE": "Adresár",
  "DIRECTORY_NAMES_LEDE": "Názvy adresárov",
  "FILENAMES_LEDE": "Názvy súborov",
  "FILENAME": "Názov súboru",
  "DIRECTORY_NAME": "Názov adresára",
  "ERROR_LOADING_PROJECT": "Chyba pri otváraní projektu",
  "OPEN_DIALOG_ERROR": "Nastala chyba pri zobrazení dialógu otvorenia súboru. (chyba {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Nastala chyba pri načítaní adresára <span class='dialog-filename'>{0}</span>. (chyba {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Nastala chyba pri načítaní obsahu adresára <span class='dialog-filename'>{0}</span>. (chyba {1})",
  "ERROR_OPENING_FILE_TITLE": "Chyba pri otváraní súboru",
  "ERROR_OPENING_FILE": "Nastala chyba pri otváraní súboru <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Nastala chyba pri otváraní nasledujúcich súborov:",
  "ERROR_RELOADING_FILE_TITLE": "Chyba pri načítaní zmien z disku",
  "ERROR_RELOADING_FILE": "Nastala chyba pri načítaní súboru <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Chyba pri ukladaní súboru",
  "ERROR_SAVING_FILE": "Nastala chyba pri ukladaní súboru <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Chyba pri premenovaní súboru",
  "ERROR_RENAMING_FILE": "Nastala chyba pri premenovaní súboru <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Súbor alebo adresár nie je súčasťou aktuálne otvoreného projektu. Bohužiaľ, v tomto bode je možné premenovať iba súbory projektu.",
  "ERROR_MOVING_FILE_TITLE": "Chyba pri presúvaní {0}",
  "ERROR_MOVING_FILE": "Pri pokuse o presun položky {2} <span class='dialog-filename'>{0}</span> sa vyskytla chyba. {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Nie je možné presunúť súbor/priečinok, pretože nie sú súčasťou aktuálneho projektu.",
  "ERROR_DELETING_FILE_TITLE": "Chyba pri zmazaní súboru",
  "ERROR_DELETING_FILE": "Nastala chyba pri zmazaní súboru <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "Neplatný {0} názov",
  "CANNOT_PASTE_TITLE": "Nie je možné prilepiť {0}",
  "CANNOT_DOWNLOAD_TITLE": "Nedá sa stiahnuť {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "Pri preberaní súboru <span class='dialog-filename'>{0}</span> sa vyskytla chyba",
  "ERR_TYPE_PASTE_FAILED": "Pri vkladaní <span class='dialog-filename'>{0}</span> do <span class='dialog-filename'>{1}</span> sa vyskytla chyba",
  "CANNOT_DUPLICATE_TITLE": "Nie je možné duplikovať",
  "ERR_TYPE_DUPLICATE_FAILED": "Pri duplikovaní <span class='dialog-filename'>{0}</span> sa vyskytla chyba",
  "INVALID_FILENAME_MESSAGE": "Názvy súboru nesmú obsahovať nasledujúce znaky: {0} alebo používať rezervované systémové slová.",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Súbor alebo adresár s názvom <span class='dialog-filename'>{0}</span> už existuje.",
  "ERROR_CREATING_FILE_TITLE": "Chyba pri vytváraní súboru {0}",
  "ERROR_CREATING_FILE": "Nastala chyba pri vytváraní súboru {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "Nie je možné otvoriť priečinok súčasne s otváraním iných súborov.",
  "ERROR_KEYMAP_TITLE": "Chyba pri čítaní mapy používateľských kľúčov",
  "ERROR_KEYMAP_CORRUPT": "Váš súbor mapy kľúčov nie je platný JSON. Súbor sa otvorí, aby ste mohli opraviť formát.",
  "ERROR_LOADING_KEYMAP": "Váš súbor mapy kľúčov nie je platný textový súbor s kódovaním UTF-8 a nemožno ho načítať",
  "ERROR_RESTRICTED_COMMANDS": "Nemôžete zmeniť priradenie skratiek k týmto príkazom: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Nemôžete zmeniť priradenie týchto skratiek: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Znova priraďujete viacero skratiek k týmto príkazom: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Máte viacero väzieb týchto skratiek: {0}",
  "ERROR_INVALID_SHORTCUTS": "Tieto skratky sú neplatné: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Priraďujete skratky k neexistujúcim príkazom: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Chyba čítania predvolieb",
  "ERROR_PREFS_CORRUPT": "Váš súbor predvolieb nie je platný JSON. Súbor sa otvorí, aby ste mohli opraviť formát. Zmeny sa prejavia až po reštartovaní aplikácie {APP_NAME}.",
  "ERROR_PROJ_PREFS_CORRUPT": "Váš súbor predvolieb projektu nie je platný JSON. Súbor sa otvorí, aby ste mohli opraviť formát. Aby sa zmeny prejavili, budete musieť projekt znova načítať.",
  "ERROR_IN_BROWSER_TITLE": "Hopa! {APP_NAME} zatiaľ nejde spustiť v prehliadači.",
  "ERROR_IN_BROWSER": "{APP_NAME} je vytvorený HTML, ale teraz pracuje ako desktopová aplikácia, takže ho môžete využiť na úpravu lokálnych súborov. Prosím, používajte shell aplikácie v <b>github.com/adobe/brackets-shell</b> repozitári pre spustenie {APP_NAME}.",
  "ERROR_MAX_FILES_TITLE": "Chyba pri indexovaní súborov",
  "ERROR_MAX_FILES": "Bol indexovaný maximálny počet súborov. Akcie pre vyhľadávanie súborov podľa indexu nemusia fungovať správne.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Chyba pri spúšťaní prehliadača",
  "ERROR_CANT_FIND_CHROME": "Prehliadač Google Chrome nebol nájdený. Prosím uistite sa, že je nainštalovaný.",
  "ERROR_LAUNCHING_BROWSER": "Nastala chyba pri spúšťaní prehliadača. (chyba {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Chyba pri živom náhľade",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Pripojovanie k prehliadaču",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "V prípade využitia živého náhľadu je treba reštarovať Chrome zo zapnutým vzdialeným ladením.<br /><br />Chceli by ste reštartovať Chrome a zapnúť vzdialené ladenie?",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Nie je možné načítať stránku zo živým náhľadom",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "Pre spustenie živého náhľadu zo súborom na serveri, musíte špecifikovať URL pre tento projekt.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Chyba pri spúšťaní HTTP severa pre súbory živého náhľadu. Prosím, skúste to znovu.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Pre viac informácií pozrite <a class=\"clickable-link\" data-href=\"{0}\">Riešenie chýb pri pripojení do živého náhľadu</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Živý náhľad",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Živý náhľad: Pripájanie…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Živý náhľad: Inicializácia…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Odpojenie živého náhľadu",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Živý náhľad",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Vyberte položku Súbor na živý náhľad",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Znovu načítať stránku",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Prepnúť zvýraznenia živého náhľadu",
  "LIVE_DEV_CLICK_POPOUT": "Vyskakovať živý náhľad do nového okna",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Pripnúť na stránke s ukážkou Odopnúť",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Živá ukážka (neaktualizuje sa kvôli chybe syntaxe)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Živý náhľad bol zrušený kvôli tomu, že boli otvorené vývojárske nástroje v prehliadači",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Živý náhľad bol zrušený kvôli tomu, že stránka bola zatvorená v prehliadači",
  "LIVE_DEV_NAVIGATED_AWAY": "Živý náhľad bol zrušený kvôli tomu, že prehliadač odkazoval na stránku, ktorá nie je súčasťou aktuálneho projektu",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Živý náhľad bol zrušený pre neznámy dôvod ({0})",
  "SAVE_CLOSE_TITLE": "Uložiť zmeny",
  "SAVE_CLOSE_MESSAGE": "Chcete uložiť zmeny, ktoré ste spravili v dokumente <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Chcete uložiť zmeny v následujúcich súboroch?",
  "EXT_MODIFIED_TITLE": "Externé zmeny",
  "CONFIRM_DELETE_TITLE": "Potvrdte odstránenie",
  "CONFIRM_FILE_DELETE": "Naozaj chcete odstrániť súbor <span class='dialog-filename'>{0}</span> ?",
  "CONFIRM_FOLDER_DELETE": "Ste si istý zmazaním priečinku <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "Súbor odstránený",
  "EXT_MODIFIED_WARNING": "Aplikácia <span class='dialog-filename'>{0}</span> bola upravená na disku mimo aplikácie {APP_NAME}.<br /><br /> Chcete súbor uložiť a prepísať tieto zmeny?",
  "EXT_MODIFIED_MESSAGE": "<span class='dialog-filename'>{0}</span> bol upravený na disku, ale tiež ma neuložené zmeny in {APP_NAME}.<br /><br />Ktorú verziu chcete ponechať?",
  "EXT_DELETED_MESSAGE": "<span class='dialog-filename'>{0}</span> bol zmazaný z disku, ale zmeny sa neuložili v {APP_NAME}.<br /><br />Chcete uložiť zmeny?",
  "WINDOW_UNLOAD_WARNING": "Naozaj chcete prejsť na inú adresu URL a opustiť hranaté zátvorky?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Máte neuložené zmeny! Naozaj chcete prejsť na inú adresu URL a opustiť hranaté zátvorky?",
  "DONE": "hotový",
  "OK": "OK",
  "CANCEL": "Zrušiť",
  "DONT_SAVE": "Neukladať",
  "SAVE": "Uložiť",
  "SAVE_AS": "Uložiť ako…",
  "SAVE_AND_OVERWRITE": "Prepísať",
  "DELETE": "Zmazať",
  "BUTTON_YES": "Áno",
  "BUTTON_NO": "Nie",
  "FIND_MATCH_INDEX": "{0} z {1}",
  "FIND_NO_RESULTS": "Žiadne výsledky",
  "FIND_QUERY_PLACEHOLDER": "Nájsť…",
  "FIND_HISTORY_MAX_COUNT": "Maximálny počet hľadaných položiek v histórii vyhľadávania",
  "REPLACE_PLACEHOLDER": "Nahraď s…",
  "BUTTON_REPLACE_ALL": "Nahradiť všetko",
  "BUTTON_REPLACE_BATCH": "Dávka…",
  "BUTTON_REPLACE_ALL_IN_FILES": "Nahradiť…",
  "BUTTON_REPLACE": "Nahradiť",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Ďalšia zhoda",
  "BUTTON_PREV_HINT": "Predchádzajúca zhoda",
  "BUTTON_CASESENSITIVE_HINT": "Match Case",
  "BUTTON_REGEXP_HINT": "Regulárny výraz",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Nahradiť bez vrátenia späť",
  "REPLACE_WITHOUT_UNDO_WARNING": "Keďže je potrebné zmeniť viac ako {0} súborov, {APP_NAME} upraví neotvorené súbory na disku.<br /> Nahradenia v týchto súboroch nebudete môcť vrátiť späť.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Nahradiť bez vrátenia späť",
  "OPEN_FILE": "Otvoriť súbor",
  "SAVE_FILE_AS": "Uložiť súbor",
  "CHOOSE_FOLDER": "Vybrať adresár",
  "RELEASE_NOTES": "Poznámky o verzii",
  "NO_UPDATE_TITLE": "Všetko je aktuálne!",
  "NO_UPDATE_MESSAGE": "Máte najnovšiu verziu {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "Nahradiť",
  "FIND_REPLACE_TITLE_WITH": "s",
  "FIND_TITLE_LABEL": "Nájdené",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} v {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "v <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "v projekte",
  "FIND_IN_FILES_ZERO_FILES": "Filter vylučuje všetky súbory {0}",
  "FIND_IN_FILES_FILE": "súbor",
  "FIND_IN_FILES_FILES": "súbory",
  "FIND_IN_FILES_MATCH": "zhoda",
  "FIND_IN_FILES_MATCHES": "zhody",
  "FIND_IN_FILES_MORE_THAN": "Cez ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "Súbor: <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Kliknutím Ctrl/Cmd všetko rozbalíte/zbalíte",
  "FIND_IN_FILES_INDEXING": "Indexovanie pre Okamžité vyhľadávanie…",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Indexuje sa {0} z {1} súborov pre Okamžité vyhľadávanie…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Nahradiť chyby",
  "REPLACE_IN_FILES_ERRORS": "Nasledujúce súbory neboli upravené, pretože sa zmenili po vyhľadávaní alebo sa nedali zapísať.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Problém pri získavaní informácií o aktualizácii",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Nastal problém pri získavaní aktuálnych informácií zo servera. Prosím uistite sa, že ste pripojený do internetu a skúste znovu.",
  "NEW_FILE_FILTER": "Nová súprava vylúčení…",
  "CLEAR_FILE_FILTER": "Nevylučovať súbory",
  "NO_FILE_FILTER": "Nie sú vylúčené žiadne súbory",
  "EXCLUDE_FILE_FILTER": "Vylúčiť {0}",
  "EDIT_FILE_FILTER": "Upraviť…",
  "FILE_FILTER_DIALOG": "Upraviť množinu vylúčení",
  "FILE_FILTER_INSTRUCTIONS": "Vylúčte súbory a priečinky zodpovedajúce ľubovoľnému z nasledujúcich reťazcov/podreťazcov alebo <a href='{0}' title=\"{0}\">zástupných znakov</a> . Zadajte každý reťazec na nový riadok.",
  "FILTER_NAME_PLACEHOLDER": "Pomenujte túto skupinu vylúčení (voliteľné)",
  "FILTER_NAME_REMAINING": "Počet zostávajúcich znakov: {0}",
  "FILE_FILTER_CLIPPED_SUFFIX": "a ďalšie ({0}).",
  "FILTER_COUNTING_FILES": "Počítanie súborov…",
  "FILTER_FILE_COUNT": "Povoľuje {0} z {1} súborov {2}",
  "FILTER_FILE_COUNT_ALL": "Povoľuje všetky súbory ({0}) {1}",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Pre aktuálnu polohu kurzora nie je k dispozícii žiadna rýchla úprava",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "Rýchla úprava CSS: umiestnite kurzor na názov jednej triedy",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "Rýchla úprava CSS: neúplný atribút triedy",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "Rýchla úprava CSS: neúplný atribút id",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "Rýchla úprava CSS: umiestnite kurzor do značky, triedy alebo id",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "Funkcia časovania CSS Rýchla úprava: neplatná syntax",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "JS Quick Edit: umiestnite kurzor do názvu funkcie",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Pre aktuálnu polohu kurzora nie sú k dispozícii žiadne rýchle dokumenty",
  "PROJECT_LOADING": "Načítavanie…",
  "UNTITLED": "bez názvu",
  "WORKING_FILES": "Otvorené súbory",
  "TOP": "Hore",
  "BOTTOM": "Spodná časť",
  "LEFT": "Vľavo",
  "RIGHT": "Správny",
  "CMD_SPLITVIEW_NONE": "Nie Split",
  "CMD_SPLITVIEW_VERTICAL": "Vertikálne rozdelenie",
  "CMD_SPLITVIEW_HORIZONTAL": "Horizontálne rozdelenie",
  "SPLITVIEW_MENU_TOOLTIP": "Rozdeľte editor vertikálne alebo horizontálne",
  "GEAR_MENU_TOOLTIP": "Konfigurácia pracovnej sady",
  "SPLITVIEW_INFO_TITLE": "Už otvorené",
  "SPLITVIEW_MULTIPANE_WARNING": "Súbor je už otvorený na inom paneli. Aplikácia {APP_NAME} bude čoskoro podporovať otváranie rovnakého súboru na viac ako jednom paneli. Dovtedy sa súbor bude zobrazovať na table, v ktorej je už otvorený.<br /><br /> (Túto správu uvidíte iba raz.)",
  "STATUSBAR_CURSOR_POSITION": "Riadok {0}, Stĺpec {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — Vybraný {0} stĺpec",
  "STATUSBAR_SELECTION_CH_PLURAL": " — Vybraných {0} stĺpcov",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — Vybraný {0} riadok",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — Vybraných {0} riadkov",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} výberov",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Kliknite pre zmenu osadenia na medzery",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Kliknite pre zmenu odsadenia na tabulátory",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Kliknite pre zmenu počet medzier použitých pre odsadenie",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Kliknite pre zmenu šírky tabulátora",
  "STATUSBAR_SPACES": "Medzery",
  "STATUSBAR_TAB_SIZE": "Velkosť tabulátora",
  "STATUSBAR_LINE_COUNT_SINGULAR": "Riadok: — {0}",
  "STATUSBAR_LINE_COUNT_PLURAL": "Riadky: — {0}",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Rozšírenia sú zakázané",
  "STATUSBAR_INSERT": "INS",
  "STATUSBAR_OVERWRITE": "OVR",
  "STATUSBAR_INSOVR_TOOLTIP": "Kliknutím prepínate kurzor medzi režimami Vložiť (INS) a Prepísať (OVR).",
  "STATUSBAR_LANG_TOOLTIP": "Kliknutím zmeníte typ súboru",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Kliknutím prepnete panel prehľadu.",
  "STATUSBAR_DEFAULT_LANG": "(predvolené)",
  "STATUSBAR_SET_DEFAULT_LANG": "Nastaviť ako predvolené pre súbory .{0}",
  "STATUSBAR_ENCODING_TOOLTIP": "Vyberte kódovanie",
  "ERRORS_PANEL_TITLE_MULTIPLE": "Problémy {0}",
  "SINGLE_ERROR": "1 {0} Problém",
  "MULTIPLE_ERRORS": "Problémy {1} {0}",
  "NO_ERRORS": "Nenašli sa žiadne problémy ({0}) – dobrá práca!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Nenašli sa žiadne problémy – dobrá práca!",
  "LINT_DISABLED": "Lining je vypnutý",
  "NO_LINT_AVAILABLE": "Pre {0} nie je k dispozícii žiadny linter",
  "NOTHING_TO_LINT": "Nič, čo by sa prášilo",
  "LINTER_TIMED_OUT": "{0} vypršal po čakaní {1} ms",
  "LINTER_FAILED": "{0} ukončené s chybou: {1}",
  "FILE_MENU": "Súbor",
  "CMD_FILE_NEW_UNTITLED": "Nový",
  "CMD_FILE_NEW": "Nový súbor",
  "CMD_FILE_DUPLICATE": "Duplikovať",
  "CMD_FILE_DOWNLOAD_PROJECT": "Stiahnite si projekt",
  "CMD_FILE_DOWNLOAD": "Stiahnuť ▼",
  "CMD_FILE_CUT": "Vystrihnúť",
  "CMD_FILE_COPY": "Kopírovať",
  "CMD_FILE_COPY_PATH": "Kopírovať cestu",
  "CMD_FILE_PASTE": "Vložiť",
  "CMD_PROJECT_NEW": "Nový projekt",
  "CMD_FILE_NEW_FOLDER": "Nový adresár",
  "CMD_FILE_OPEN": "Otvoriť…",
  "CMD_RECENT_FILES_OPEN": "Posledné súbory…",
  "CMD_ADD_TO_WORKING_SET": "Pridať do pracovnej sady",
  "CMD_OPEN_DROPPED_FILES": "Otvorte zrušené súbory",
  "CMD_OPEN_FOLDER": "Otvoriť adresár…",
  "CMD_FILE_CLOSE": "Zatvoriť",
  "CMD_FILE_CLOSE_ALL": "Zatvoriť všetko",
  "CMD_FILE_CLOSE_LIST": "Zatvoriť zoznam",
  "CMD_FILE_CLOSE_OTHERS": "Zavrieť Ostatné",
  "CMD_FILE_CLOSE_ABOVE": "Zavrieť ostatné vyššie",
  "CMD_FILE_CLOSE_BELOW": "Zavrieť Ostatné nižšie",
  "CMD_FILE_SAVE": "Uložiť súbor",
  "CMD_FILE_SAVE_ALL": "Uložiť všetko",
  "CMD_FILE_SAVE_AS": "Uložiť ako…",
  "CMD_LIVE_FILE_PREVIEW": "Živý náhľad",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Povoliť experimentálny živý náhľad",
  "CMD_RELOAD_LIVE_PREVIEW": "Vynútiť opätovné načítanie živého náhľadu",
  "CMD_PROJECT_SETTINGS": "Nastavenia projektu…",
  "CMD_FILE_RENAME": "Premenovať",
  "CMD_FILE_DELETE": "Zmazať",
  "CMD_INSTALL_EXTENSION": "Inštalovať rozšírenia…",
  "CMD_EXTENSION_MANAGER": "Správca rozšírení…",
  "CMD_FILE_REFRESH": "Obnoviť strom súborov",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Najprv zoraďte priečinky",
  "CMD_QUIT": "Koniec",
  "CMD_EXIT": "Koniec",
  "EDIT_MENU": "Upraviť",
  "CMD_UNDO": "Späť",
  "CMD_REDO": "Znovu",
  "CMD_CUT": "Vystrihnúť",
  "CMD_COPY": "Kopírovať",
  "CMD_PASTE": "Vložiť",
  "CMD_SELECT_ALL": "Vybrať všetko",
  "CMD_SELECT_LINE": "Vybrať riadok",
  "CMD_SPLIT_SEL_INTO_LINES": "Rozdeľte výber na riadky",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Pridajte kurzor na ďalší riadok",
  "CMD_ADD_CUR_TO_PREV_LINE": "Pridať kurzor na predchádzajúci riadok",
  "CMD_INDENT": "Odsadiť",
  "CMD_UNINDENT": "Vrátiť odsadenie",
  "CMD_DUPLICATE": "Duplikovať",
  "CMD_DELETE_LINES": "Zmazať riadok",
  "CMD_COMMENT": "Riadkový komentár",
  "CMD_BLOCK_COMMENT": "Blokový komentár",
  "CMD_LINE_UP": "Posunúť riadok hore",
  "CMD_LINE_DOWN": "Posunúť riadok dole",
  "CMD_OPEN_LINE_ABOVE": "O riadok vyššie",
  "CMD_OPEN_LINE_BELOW": "O riadok nižšie",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Uzatvárať zátvorky",
  "CMD_SHOW_CODE_HINTS": "Zobraziť tipy",
  "CMD_BEAUTIFY_CODE": "Skrášliť kód",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "Skrášliť kód po uložení",
  "FIND_MENU": "Vyhľadať",
  "CMD_FIND": "Vyhľadať",
  "CMD_FIND_NEXT": "Vyhľadať nasledujúci",
  "CMD_FIND_PREVIOUS": "Vyhľadať predchádzajúci",
  "CMD_FIND_ALL_AND_SELECT": "Nájsť všetko a vybrať",
  "CMD_ADD_NEXT_MATCH": "Pridať ďalšiu zhodu do výberu",
  "CMD_SKIP_CURRENT_MATCH": "Preskočiť a pridať ďalšiu zhodu",
  "CMD_FIND_IN_FILES": "Vyhľadať v súboroch",
  "CMD_FIND_IN_SUBTREE": "Vyhľadať v…",
  "CMD_REPLACE": "Nahradiť",
  "CMD_REPLACE_IN_FILES": "Nahradiť v súboroch",
  "CMD_REPLACE_IN_SUBTREE": "Nahradiť v…",
  "VIEW_MENU": "Zobraziť",
  "CMD_HIDE_SIDEBAR": "Skryť bočný panel",
  "CMD_SHOW_SIDEBAR": "Zobraziť bočný panel",
  "CMD_TOGGLE_SIDEBAR": "Prepnúť bočný panel",
  "CMD_TOGGLE_PANELS": "Prepnúť panely",
  "CMD_TOGGLE_PURE_CODE": "Žiadne rozptýlenie",
  "CMD_INCREASE_FONT_SIZE": "Zväčšiť veľkosť písma",
  "CMD_DECREASE_FONT_SIZE": "Zmenšiť veľkosť písma",
  "CMD_RESTORE_FONT_SIZE": "Obnoviť veľkosť písma",
  "CMD_SCROLL_LINE_UP": "Posunúť o riadok hore",
  "CMD_SCROLL_LINE_DOWN": "Posunúť o riadok dole",
  "CMD_TOGGLE_LINE_NUMBERS": "Čísla riadkov",
  "CMD_TOGGLE_ACTIVE_LINE": "Zvýrazniť aktívny riadok",
  "CMD_TOGGLE_WORD_WRAP": "Zalomenie riadkov",
  "CMD_LIVE_HIGHLIGHT": "Zvýraznenie živého náhľadu",
  "CMD_VIEW_TOGGLE_INSPECTION": "Súbory Lint na Uložiť",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Usporiadať podľa dátumu",
  "CMD_WORKINGSET_SORT_BY_NAME": "Usporiadať podľa mena",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Usporiadať podľa typu",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Automatické usporiadanie",
  "CMD_THEMES": "Témy…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Automaticky zavrieť vyhľadávanie",
  "NAVIGATE_MENU": "Navigácia",
  "CMD_QUICK_OPEN": "Rýchle otvorenie",
  "CMD_GOTO_LINE": "Prejsť na riadok",
  "CMD_GOTO_DEFINITION": "Prejsť na definíciu",
  "CMD_GOTO_DEFINITION_PROJECT": "Definícia rýchleho hľadania v projekte",
  "CMD_GOTO_FIRST_PROBLEM": "Prejdite na Prvý problém",
  "CMD_TOGGLE_QUICK_EDIT": "Rýchla úprava",
  "CMD_TOGGLE_QUICK_DOCS": "Rýchla dokumentácia",
  "CMD_QUICK_EDIT_PREV_MATCH": "Predchádzajúca zhoda",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Ďalšia zhoda",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Nové pravidlo",
  "CMD_NEXT_DOC": "Následujúci dokument",
  "CMD_PREV_DOC": "Predchádzajúci dokument",
  "CMD_NAVIGATE_BACKWARD": "Navigovať dozadu",
  "CMD_NAVIGATE_FORWARD": "Navigovať dopredu",
  "CMD_NEXT_DOC_LIST_ORDER": "Ďalší dokument v zozname",
  "CMD_PREV_DOC_LIST_ORDER": "Predchádzajúci dokument v zozname",
  "CMD_SHOW_IN_TREE": "Zobraziť stromovú štruktúru",
  "CMD_SHOW_IN_EXPLORER": "Ukázať v prehliadači",
  "CMD_SHOW_IN_FINDER": "Zobraziť vo Finderi",
  "CMD_SHOW_IN_OS": "Zobraziť v OS",
  "CMD_SWITCH_PANE_FOCUS": "Prepnúť zameranie tably",
  "CMD_OPEN_VFS": "Otvorte virtuálny súborový systém",
  "CMD_OPEN_VIRTUAL_SERVER": "Otvorte virtuálny server",
  "HELP_MENU": "Nápoveda",
  "CMD_CHECK_FOR_UPDATE": "Skontrolovať aktualizácie",
  "CMD_HOW_TO_USE_BRACKETS": "Ako používať {APP_NAME}",
  "CMD_SUPPORT": "Podpora aplikácie {APP_NAME}",
  "CMD_SUGGEST": "Navrhnite funkciu",
  "CMD_RELEASE_NOTES": "Poznámky o verzii",
  "CMD_GET_INVOLVED": "Zapojte sa",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Zobraziť priečinok s doplnkami",
  "CMD_HEALTH_DATA_STATISTICS": "Správa o zdraví",
  "CMD_HOMEPAGE": "Domovská stránka aplikácie {APP_NAME}",
  "CMD_TWITTER": "{TWITTER_NAME} na Twitteri",
  "CMD_ABOUT": "O {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "Otvorte súbor predvolieb",
  "CMD_OPEN_KEYMAP": "Otvorte mapu používateľských kľúčov",
  "EXPERIMENTAL_BUILD": "experimentálna verzia",
  "RELEASE_BUILD": "stavať",
  "DEVELOPMENT_BUILD": "vývojová verzia",
  "PRERELEASE_BUILD": "predbežná verzia",
  "RELOAD_FROM_DISK": "Načítať z disku",
  "KEEP_CHANGES_IN_EDITOR": "Ponechať zmeny v editore",
  "CLOSE_DONT_SAVE": "Zatvoriť (neukladať)",
  "RELAUNCH_CHROME": "Reštartovať Chrome",
  "ABOUT": "O aplikácii",
  "CLOSE": "Zatvoriť",
  "ABOUT_TEXT_LINE1": "Vydanie {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "časová pečiatka zostavy:",
  "ABOUT_TEXT_LINE3": "Knižnice tretích strán, ktoré používame – <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>Licencie a Atribúcie</a> .",
  "ABOUT_TEXT_LINE4": "Dokumentácia a zdroj na <a href='https://github.com/phcode-dev/phoenix/'>https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "Vyrobené pomocou ❤ a JavaScript od:",
  "ABOUT_TEXT_LINE6": "Veľa ľudí (ale práve teraz máme problémy s načítaním týchto údajov).",
  "ABOUT_TEXT_MDN_DOCS": "MDN Docs a the MDN grafické logo sú licencované pod Creative Commons Attribution license, <a class=\"clickable-link\" data-href=\"{MDN_DOCS_LICENSE}\">CC-BY-SA 2.5 Unported</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "Je dostupná nová verzia {APP_NAME}! Kliknite sem pre viac detailov.",
  "UPDATE_AVAILABLE_TITLE": "Dostupná aktualizácia",
  "UPDATE_RELOAD_APP": "Zatvorte všetky okná/karty aplikácie {APP_NAME} a znova otvorte aplikáciu {APP_NAME}, aby ste získali najnovšiu verziu.",
  "UPDATE_MESSAGE": "Hey, je dostupná nová verzia {APP_NAME}. Zoznam niektorých nových vylepšení:",
  "GET_IT_NOW": "Stiahnuť!",
  "PROJECT_SETTINGS_TITLE": "Nastavenia projketu pre: {0}",
  "PROJECT_SETTING_BASE_URL": "Živý náhľad URL",
  "PROJECT_SETTING_BASE_URL_HINT": "Pre použitie lokálneho servera, vložte URL v tvare http://localhost:8000/",
  "BASEURL_ERROR_INVALID_PROTOCOL": "Protokol {0} nie je podporovaný Živým náhľadom&mdash;prosím použite http: alebo https: .",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "URL adresa nemôže obsahovať výrazy pre hľadanie ako \"{0}\".",
  "BASEURL_ERROR_HASH_DISALLOWED": "URL adresa nemôže obsahovať znaky ako \"{0}\".",
  "BASEURL_ERROR_INVALID_CHAR": "Zvláštné znaky ako '{0}' musia byť %-enkódované.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "Neznáma chyba pri spracovávaní URL",
  "EMPTY_VIEW_HEADER": "<em>Otvorte súbor, kým je tento panel aktívny</em>",
  "FLIPVIEW_BTN_TOOLTIP": "Otočte toto zobrazenie na tablu {0}",
  "CURRENT_THEME": 