/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "По подразбиране",
  "PROJECT_BUSY": "Операции по проекта в ход",
  "DUPLICATING": "Дублиране на {0}",
  "MOVING": "Преместване на {0}",
  "COPYING": "Копиране на {0}",
  "DELETING": "Изтриване на {0}",
  "RENAMING": "Преименуване",
  "GENERIC_ERROR": "(грешка {0})",
  "NOT_FOUND_ERR": "Файлът/папката не може да бъде открит.",
  "NOT_READABLE_ERR": "Файлът/папката не може да бъде прочетен.",
  "EXCEEDS_MAX_FILE_SIZE": "Файлове с размер по-голям от {0} МБ не могат да бъдат прочетени от {APP_NAME}.",
  "NO_MODIFICATION_ALLOWED_ERR": "Целевата папка не може да бъде променяна.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Правата не Ви позволяват да правите промени.",
  "CONTENTS_MODIFIED_ERR": "Файлът е бил променен извън {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} в момента поддържа само текстови файлове с кодировка UTF-8.",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} не успя да кодира съдържанието на файла.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} не успя да декодира съдържанието на файла.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "Понастоящем {APP_NAME} не поддържа UTF-16 кодирани текстови файлове.",
  "FILE_EXISTS_ERR": "Файлът или папката вече съществува.",
  "FILE": "файл",
  "FILE_TITLE": "Файл",
  "DIRECTORY": "папка",
  "DIRECTORY_TITLE": "Папка",
  "DIRECTORY_NAMES_LEDE": "Имена на папки",
  "FILENAMES_LEDE": "Имена на файлове",
  "FILENAME": "Име на файл",
  "DIRECTORY_NAME": "Име на папка",
  "ERROR_LOADING_PROJECT": "Грешка при зареждане на проекта",
  "OPEN_DIALOG_ERROR": "Възникна грешка при показването на прозореца за отваряне на файл. (грешка {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Възникна грешка при опита за зареждане на папката <span class='dialog-filename'>{0}</span>. (грешка {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Възникна грешка при прочитането на съдържанието на папката <span class='dialog-filename'>{0}</span>. (грешка {1})",
  "ERROR_OPENING_FILE_TITLE": "Грешка при отваряне на файла",
  "ERROR_OPENING_FILE": "Възникна грешка при опита за отваряне на файла <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Възникна грешка при опита за отваряне на следните файлове:",
  "ERROR_RELOADING_FILE_TITLE": "Грешка при прочитането на промените от диска",
  "ERROR_RELOADING_FILE": "Възникна грешка при опита за презареждане на файла <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Грешка при запазването на файла",
  "ERROR_SAVING_FILE": "Възникна грешка при опита за запазване на файла <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Грешка при преименуването на {0}",
  "ERROR_RENAMING_FILE": "Възникна грешка при опита за преименуване на {2} <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Файлът или папката не е част от текущо отворения проект. За съжаление, само файловете в проекта могат да бъдат преименувани засега.",
  "ERROR_MOVING_FILE_TITLE": "Грешка при преместване на {0}",
  "ERROR_MOVING_FILE": "Възникна грешка при опит за преместване на {2} <span class='dialog-filename'>{0}</span> . {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Не може да премести файла/папката, тъй като те не са част от текущия проект.",
  "ERROR_DELETING_FILE_TITLE": "Грешка при изтриването на {0}",
  "ERROR_DELETING_FILE": "Възникна грешка при опита за изтриване на {2} <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "Грешно {0}",
  "CANNOT_PASTE_TITLE": "Не може да се постави {0}",
  "CANNOT_DOWNLOAD_TITLE": "Не може да се изтегли {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "Възникна грешка при изтеглянето на <span class='dialog-filename'>{0}</span>",
  "ERR_TYPE_PASTE_FAILED": "Възникна грешка при поставяне на <span class='dialog-filename'>{0}</span> в <span class='dialog-filename'>{1}</span>",
  "CANNOT_DUPLICATE_TITLE": "Не може да се дублира",
  "ERR_TYPE_DUPLICATE_FAILED": "Възникна грешка при дублирането на <span class='dialog-filename'>{0}</span>",
  "INVALID_FILENAME_MESSAGE": "{0} не може да използва запазени думи, да завършва с точки (.) или да използва никой от следните знаци: <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Вече съществува файл или папка с името <span class='dialog-filename'>{0}</span>.",
  "ERROR_CREATING_FILE_TITLE": "Грешка при създаването на {0}",
  "ERROR_CREATING_FILE": "Възникна грешка при опита за създаване на {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "Папка и файлове не могат да се отварят едновременно.",
  "ERROR_KEYMAP_TITLE": "Грешка при прочитането на потребителските клавишни настройки",
  "ERROR_KEYMAP_CORRUPT": "Файлът с Вашите клавишни настройки не е правилно форматиран според формата JSON. Файлът ще бъде отворен, за да го поправите.",
  "ERROR_LOADING_KEYMAP": "Файлът с Вашите клавишни настройки не е кодиран в правилната кодировка UTF-8 и не може да бъде зареден.",
  "ERROR_RESTRICTED_COMMANDS": "Не можете да настройвате други клавиши и комбинации за следните команди: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Не можете да пренастройвате следните клавиши и комбинации: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Настройвате твърде много клавишни комбинации за следните команди: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Имате твърде много настроени команди за следните клавишни комбинации: {0}",
  "ERROR_INVALID_SHORTCUTS": "Следните клавишни комбинации са грешни: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Задавате клавишни комбинации на несъществуващи команди: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Грешка при прочитането на настройките",
  "ERROR_PREFS_CORRUPT": "Файлът с настройките не е правилно форматиран според формата JSON. Файлът ще бъде отворен, за да го поправите. След това ще трябва да затворите и пуснете отново {APP_NAME}, за да влязат в сила промените.",
  "ERROR_PROJ_PREFS_CORRUPT": "Файлът с настройките на проекта не е правилно форматиран според формата JSON. Файлът ще бъде отворен, за да го поправите. След това ще трябва да презаредите проекта, за да влязат в сила промените.",
  "ERROR_IN_BROWSER_TITLE": "Опа! {APP_NAME} все още не може да работи в браузър.",
  "ERROR_IN_BROWSER": "Приложението {APP_NAME} е изградено чрез HTML, но в момента работи като настолно приложение, така че да може да го използвате за редактиране на местни файлове. Моля, използвайте приложната обвивка от хранилището <b>github.com/adobe/brackets-shell</b>, за да пуснете {APP_NAME}.",
  "ERROR_MAX_FILES_TITLE": "Грешка при обработката на файловете",
  "ERROR_MAX_FILES": "Този проект има над 30 000 файла. Функционалностите, които работят с множество файлове може да бъдат изключени или да работят така, сякаш проектът е празен. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>Прочете повече относно работата с големи проекти</a>.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Грешка при пускането на браузъра",
  "ERROR_CANT_FIND_CHROME": "Браузърът „Google Chrome“ не може да бъде открит. Моля, уверете се, че той е инсталиран.",
  "ERROR_LAUNCHING_BROWSER": "Възникна грешка при пускането на браузъра. (грешка {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Грешка при прегледа на живо",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Свързване с браузъра",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "За да може да се свърже прегледът на живо, Chrome трябва да бъде пуснат отново с включена възможност за отдалечено отстраняване на грешки.<br /><br />Искате ли да пуснете отново Chrome и да включите тази възможност?<br /><br />",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Неуспешно зареждане на страницата в прегледа на живо.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "За да пуснете прегледа на живо с файл от сървър, трябва да посочите базов адрес за този проект.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Грешка при пускането на HTTP сървъра за преглед на файлове на живо. Моля, опитайте отново.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "За повече информация, вижте <a href='{0}' title='{0}'>Отстраняване на проблеми с връзката на прегледа на живо</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Преглед на живо",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Преглед на живо: свързване…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Преглед на живо: установка…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Разкачане на прегледа на живо",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Преглед на живо",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Изберете File To Live Preview",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Презареди страницата",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Превключване на акценти за преглед на живо",
  "LIVE_DEV_CLICK_POPOUT": "Изскачащ преглед на живо в нов прозорец",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Фиксиране на Unpin Preview Page",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Преглед на живо (без обновяване, поради синтактична грешка)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Прегледът на живо беше прекъснат, тъй като бяха отворени инструментите за разработчици на браузъра.",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Прегледът на живо беше прекъснат, тъй като страницата в браузъра беше затворена.",
  "LIVE_DEV_NAVIGATED_AWAY": "Прегледът на живо беше прекъснат, тъй като бръузърът премина към страница, която не е част от текущия проект.",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Прегледът на живо беше прекъснат поради неизвестна причина ({0})",
  "SAVE_CLOSE_TITLE": "Запазване на промените",
  "SAVE_CLOSE_MESSAGE": "Искате ли да запазите промените, които направихте в документа <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Искате ли да запазите промените си в следните файлове?",
  "EXT_MODIFIED_TITLE": "Външни промени",
  "CONFIRM_DELETE_TITLE": "Потвърждаване на изтриването",
  "CONFIRM_FILE_DELETE": "Сигурни ли сте, че искате да изтриете файла <span class='dialog-filename'>{0}</span> ?",
  "CONFIRM_FOLDER_DELETE": "Наистина ли искате да изтриете папката <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "Изтрит файл",
  "EXT_MODIFIED_WARNING": "Файлът <span class='dialog-filename'>{0}</span> беше променен извън {APP_NAME}.<br /><br />Искате ли да запазите файла и да презапишете промените му?",
  "EXT_MODIFIED_MESSAGE": "Файлът <span class='dialog-filename'>{0}</span> беше променен извън {APP_NAME}, но също така има незапазени промени в {APP_NAME}.<br /><br />Кой вариант искате да запазите?",
  "EXT_DELETED_MESSAGE": "Файлът <span class='dialog-filename'>{0}</span> беше изтрит извън {APP_NAME}, но има незапазени промени в {APP_NAME}.<br /><br />Искате ли да запазите промените си?",
  "WINDOW_UNLOAD_WARNING": "Сигурни ли сте, че искате да отидете до друг URL адрес и да оставите скоби?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Имате незапазени промени! Сигурни ли сте, че искате да отидете до друг URL адрес и да оставите скоби?",
  "DONE": "Готово",
  "OK": "Добре",
  "CANCEL": "Отказ",
  "DONT_SAVE": "Без запазване",
  "SAVE": "Запазване",
  "SAVE_AS": "Запазване като…",
  "SAVE_AND_OVERWRITE": "Презаписване",
  "DELETE": "Изтриване",
  "BUTTON_YES": "Да",
  "BUTTON_NO": "Не",
  "FIND_MATCH_INDEX": "{0} от {1}",
  "FIND_NO_RESULTS": "Няма резултати",
  "FIND_QUERY_PLACEHOLDER": "Търсене…",
  "FIND_HISTORY_MAX_COUNT": "Максимален брой елементи за търсене в историята на търсенията",
  "REPLACE_PLACEHOLDER": "Замяна с…",
  "BUTTON_REPLACE_ALL": "Група…",
  "BUTTON_REPLACE_BATCH": "Партида...",
  "BUTTON_REPLACE_ALL_IN_FILES": "Замяна…",
  "BUTTON_REPLACE": "Замяна",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Следващо съвпадение",
  "BUTTON_PREV_HINT": "Предишно съвпадение",
  "BUTTON_CASESENSITIVE_HINT": "Съвпадение на малки/големи букви",
  "BUTTON_REGEXP_HINT": "Регулярен израз",
  "REPLACE_WITHO