/*
 * GNU AGPL-3.0 License
 *
 * Copyright (c) 2021 - present core.ai . All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see https://opensource.org/licenses/AGPL-3.0.
 *
 */

define({
  "SYSTEM_DEFAULT": "По подразбиране",
  "PROJECT_BUSY": "Операции по проекта в ход",
  "DUPLICATING": "Дублиране на {0}",
  "MOVING": "Преместване на {0}",
  "COPYING": "Копиране на {0}",
  "DELETING": "Изтриване на {0}",
  "RENAMING": "Преименуване",
  "GENERIC_ERROR": "(грешка {0})",
  "NOT_FOUND_ERR": "Файлът/папката не може да бъде открит.",
  "NOT_READABLE_ERR": "Файлът/папката не може да бъде прочетен.",
  "EXCEEDS_MAX_FILE_SIZE": "Файлове с размер по-голям от {0} МБ не могат да бъдат прочетени от {APP_NAME}.",
  "NO_MODIFICATION_ALLOWED_ERR": "Целевата папка не може да бъде променяна.",
  "NO_MODIFICATION_ALLOWED_ERR_FILE": "Правата не Ви позволяват да правите промени.",
  "CONTENTS_MODIFIED_ERR": "Файлът е бил променен извън {APP_NAME}.",
  "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} в момента поддържа само текстови файлове с кодировка UTF-8.",
  "ENCODE_FILE_FAILED_ERR": "{APP_NAME} не успя да кодира съдържанието на файла.",
  "DECODE_FILE_FAILED_ERR": "{APP_NAME} не успя да декодира съдържанието на файла.",
  "UNSUPPORTED_UTF16_ENCODING_ERR": "Понастоящем {APP_NAME} не поддържа UTF-16 кодирани текстови файлове.",
  "FILE_EXISTS_ERR": "Файлът или папката вече съществува.",
  "FILE": "файл",
  "FILE_TITLE": "Файл",
  "DIRECTORY": "папка",
  "DIRECTORY_TITLE": "Папка",
  "DIRECTORY_NAMES_LEDE": "Имена на папки",
  "FILENAMES_LEDE": "Имена на файлове",
  "FILENAME": "Име на файл",
  "DIRECTORY_NAME": "Име на папка",
  "ERROR_LOADING_PROJECT": "Грешка при зареждане на проекта",
  "OPEN_DIALOG_ERROR": "Възникна грешка при показването на прозореца за отваряне на файл. (грешка {0})",
  "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Възникна грешка при опита за зареждане на папката <span class='dialog-filename'>{0}</span>. (грешка {1})",
  "READ_DIRECTORY_ENTRIES_ERROR": "Възникна грешка при прочитането на съдържанието на папката <span class='dialog-filename'>{0}</span>. (грешка {1})",
  "ERROR_OPENING_FILE_TITLE": "Грешка при отваряне на файла",
  "ERROR_OPENING_FILE": "Възникна грешка при опита за отваряне на файла <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_OPENING_FILES": "Възникна грешка при опита за отваряне на следните файлове:",
  "ERROR_RELOADING_FILE_TITLE": "Грешка при прочитането на промените от диска",
  "ERROR_RELOADING_FILE": "Възникна грешка при опита за презареждане на файла <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_SAVING_FILE_TITLE": "Грешка при запазването на файла",
  "ERROR_SAVING_FILE": "Възникна грешка при опита за запазване на файла <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_FILE_TITLE": "Грешка при преименуването на {0}",
  "ERROR_RENAMING_FILE": "Възникна грешка при опита за преименуване на {2} <span class='dialog-filename'>{0}</span>. {1}",
  "ERROR_RENAMING_NOT_IN_PROJECT": "Файлът или папката не е част от текущо отворения проект. За съжаление, само файловете в проекта могат да бъдат преименувани засега.",
  "ERROR_MOVING_FILE_TITLE": "Грешка при преместване на {0}",
  "ERROR_MOVING_FILE": "Възникна грешка при опит за преместване на {2} <span class='dialog-filename'>{0}</span> . {1}",
  "ERROR_MOVING_NOT_IN_PROJECT": "Не може да премести файла/папката, тъй като те не са част от текущия проект.",
  "ERROR_DELETING_FILE_TITLE": "Грешка при изтриването на {0}",
  "ERROR_DELETING_FILE": "Възникна грешка при опита за изтриване на {2} <span class='dialog-filename'>{0}</span>. {1}",
  "INVALID_FILENAME_TITLE": "Грешно {0}",
  "CANNOT_PASTE_TITLE": "Не може да се постави {0}",
  "CANNOT_DOWNLOAD_TITLE": "Не може да се изтегли {0}",
  "ERR_TYPE_DOWNLOAD_FAILED": "Възникна грешка при изтеглянето на <span class='dialog-filename'>{0}</span>",
  "ERR_TYPE_PASTE_FAILED": "Възникна грешка при поставяне на <span class='dialog-filename'>{0}</span> в <span class='dialog-filename'>{1}</span>",
  "CANNOT_DUPLICATE_TITLE": "Не може да се дублира",
  "ERR_TYPE_DUPLICATE_FAILED": "Възникна грешка при дублирането на <span class='dialog-filename'>{0}</span>",
  "INVALID_FILENAME_MESSAGE": "{0} не може да използва запазени думи, да завършва с точки (.) или да използва никой от следните знаци: <code class='emphasized'>{1}</code>",
  "ENTRY_WITH_SAME_NAME_EXISTS": "Вече съществува файл или папка с името <span class='dialog-filename'>{0}</span>.",
  "ERROR_CREATING_FILE_TITLE": "Грешка при създаването на {0}",
  "ERROR_CREATING_FILE": "Възникна грешка при опита за създаване на {0} <span class='dialog-filename'>{1}</span>. {2}",
  "ERROR_MIXED_DRAGDROP": "Папка и файлове не могат да се отварят едновременно.",
  "ERROR_KEYMAP_TITLE": "Грешка при прочитането на потребителските клавишни настройки",
  "ERROR_KEYMAP_CORRUPT": "Файлът с Вашите клавишни настройки не е правилно форматиран според формата JSON. Файлът ще бъде отворен, за да го поправите.",
  "ERROR_LOADING_KEYMAP": "Файлът с Вашите клавишни настройки не е кодиран в правилната кодировка UTF-8 и не може да бъде зареден.",
  "ERROR_RESTRICTED_COMMANDS": "Не можете да настройвате други клавиши и комбинации за следните команди: {0}",
  "ERROR_RESTRICTED_SHORTCUTS": "Не можете да пренастройвате следните клавиши и комбинации: {0}",
  "ERROR_MULTIPLE_SHORTCUTS": "Настройвате твърде много клавишни комбинации за следните команди: {0}",
  "ERROR_DUPLICATE_SHORTCUTS": "Имате твърде много настроени команди за следните клавишни комбинации: {0}",
  "ERROR_INVALID_SHORTCUTS": "Следните клавишни комбинации са грешни: {0}",
  "ERROR_NONEXISTENT_COMMANDS": "Задавате клавишни комбинации на несъществуващи команди: {0}",
  "ERROR_PREFS_CORRUPT_TITLE": "Грешка при прочитането на настройките",
  "ERROR_PREFS_CORRUPT": "Файлът с настройките не е правилно форматиран според формата JSON. Файлът ще бъде отворен, за да го поправите. След това ще трябва да затворите и пуснете отново {APP_NAME}, за да влязат в сила промените.",
  "ERROR_PROJ_PREFS_CORRUPT": "Файлът с настройките на проекта не е правилно форматиран според формата JSON. Файлът ще бъде отворен, за да го поправите. След това ще трябва да презаредите проекта, за да влязат в сила промените.",
  "ERROR_IN_BROWSER_TITLE": "Опа! {APP_NAME} все още не може да работи в браузър.",
  "ERROR_IN_BROWSER": "Приложението {APP_NAME} е изградено чрез HTML, но в момента работи като настолно приложение, така че да може да го използвате за редактиране на местни файлове. Моля, използвайте приложната обвивка от хранилището <b>github.com/adobe/brackets-shell</b>, за да пуснете {APP_NAME}.",
  "ERROR_MAX_FILES_TITLE": "Грешка при обработката на файловете",
  "ERROR_MAX_FILES": "Този проект има над 30 000 файла. Функционалностите, които работят с множество файлове може да бъдат изключени или да работят така, сякаш проектът е празен. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>Прочете повече относно работата с големи проекти</a>.",
  "ERROR_LAUNCHING_BROWSER_TITLE": "Грешка при пускането на браузъра",
  "ERROR_CANT_FIND_CHROME": "Браузърът „Google Chrome“ не може да бъде открит. Моля, уверете се, че той е инсталиран.",
  "ERROR_LAUNCHING_BROWSER": "Възникна грешка при пускането на браузъра. (грешка {0})",
  "LIVE_DEVELOPMENT_ERROR_TITLE": "Грешка при прегледа на живо",
  "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Свързване с браузъра",
  "LIVE_DEVELOPMENT_ERROR_MESSAGE": "За да може да се свърже прегледът на живо, Chrome трябва да бъде пуснат отново с включена възможност за отдалечено отстраняване на грешки.<br /><br />Искате ли да пуснете отново Chrome и да включите тази възможност?<br /><br />",
  "LIVE_DEV_LOADING_ERROR_MESSAGE": "Неуспешно зареждане на страницата в прегледа на живо.",
  "LIVE_DEV_NEED_BASEURL_MESSAGE": "За да пуснете прегледа на живо с файл от сървър, трябва да посочите базов адрес за този проект.",
  "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Грешка при пускането на HTTP сървъра за преглед на файлове на живо. Моля, опитайте отново.",
  "LIVE_DEVELOPMENT_TROUBLESHOOTING": "За повече информация, вижте <a href='{0}' title='{0}'>Отстраняване на проблеми с връзката на прегледа на живо</a>.",
  "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Преглед на живо",
  "LIVE_DEV_STATUS_TIP_PROGRESS1": "Преглед на живо: свързване…",
  "LIVE_DEV_STATUS_TIP_PROGRESS2": "Преглед на живо: установка…",
  "LIVE_DEV_STATUS_TIP_CONNECTED": "Разкачане на прегледа на живо",
  "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Преглед на живо",
  "LIVE_DEV_SELECT_FILE_TO_PREVIEW": "Изберете File To Live Preview",
  "LIVE_DEV_CLICK_TO_RELOAD_PAGE": "Презареди страницата",
  "LIVE_DEV_TOGGLE_LIVE_HIGHLIGHT": "Превключване на акценти за преглед на живо",
  "LIVE_DEV_CLICK_POPOUT": "Изскачащ преглед на живо в нов прозорец",
  "LIVE_DEV_CLICK_TO_PIN_UNPIN": "Фиксиране на Unpin Preview Page",
  "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Преглед на живо (без обновяване, поради синтактична грешка)",
  "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Прегледът на живо беше прекъснат, тъй като бяха отворени инструментите за разработчици на браузъра.",
  "LIVE_DEV_DETACHED_TARGET_CLOSED": "Прегледът на живо беше прекъснат, тъй като страницата в браузъра беше затворена.",
  "LIVE_DEV_NAVIGATED_AWAY": "Прегледът на живо беше прекъснат, тъй като бръузърът премина към страница, която не е част от текущия проект.",
  "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Прегледът на живо беше прекъснат поради неизвестна причина ({0})",
  "SAVE_CLOSE_TITLE": "Запазване на промените",
  "SAVE_CLOSE_MESSAGE": "Искате ли да запазите промените, които направихте в документа <span class='dialog-filename'>{0}</span>?",
  "SAVE_CLOSE_MULTI_MESSAGE": "Искате ли да запазите промените си в следните файлове?",
  "EXT_MODIFIED_TITLE": "Външни промени",
  "CONFIRM_DELETE_TITLE": "Потвърждаване на изтриването",
  "CONFIRM_FILE_DELETE": "Сигурни ли сте, че искате да изтриете файла <span class='dialog-filename'>{0}</span> ?",
  "CONFIRM_FOLDER_DELETE": "Наистина ли искате да изтриете папката <span class='dialog-filename'>{0}</span>?",
  "FILE_DELETED_TITLE": "Изтрит файл",
  "EXT_MODIFIED_WARNING": "Файлът <span class='dialog-filename'>{0}</span> беше променен извън {APP_NAME}.<br /><br />Искате ли да запазите файла и да презапишете промените му?",
  "EXT_MODIFIED_MESSAGE": "Файлът <span class='dialog-filename'>{0}</span> беше променен извън {APP_NAME}, но също така има незапазени промени в {APP_NAME}.<br /><br />Кой вариант искате да запазите?",
  "EXT_DELETED_MESSAGE": "Файлът <span class='dialog-filename'>{0}</span> беше изтрит извън {APP_NAME}, но има незапазени промени в {APP_NAME}.<br /><br />Искате ли да запазите промените си?",
  "WINDOW_UNLOAD_WARNING": "Сигурни ли сте, че искате да отидете до друг URL адрес и да оставите скоби?",
  "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES": "Имате незапазени промени! Сигурни ли сте, че искате да отидете до друг URL адрес и да оставите скоби?",
  "DONE": "Готово",
  "OK": "Добре",
  "CANCEL": "Отказ",
  "DONT_SAVE": "Без запазване",
  "SAVE": "Запазване",
  "SAVE_AS": "Запазване като…",
  "SAVE_AND_OVERWRITE": "Презаписване",
  "DELETE": "Изтриване",
  "BUTTON_YES": "Да",
  "BUTTON_NO": "Не",
  "FIND_MATCH_INDEX": "{0} от {1}",
  "FIND_NO_RESULTS": "Няма резултати",
  "FIND_QUERY_PLACEHOLDER": "Търсене…",
  "FIND_HISTORY_MAX_COUNT": "Максимален брой елементи за търсене в историята на търсенията",
  "REPLACE_PLACEHOLDER": "Замяна с…",
  "BUTTON_REPLACE_ALL": "Група…",
  "BUTTON_REPLACE_BATCH": "Партида...",
  "BUTTON_REPLACE_ALL_IN_FILES": "Замяна…",
  "BUTTON_REPLACE": "Замяна",
  "BUTTON_NEXT": "▶",
  "BUTTON_PREV": "◀",
  "BUTTON_NEXT_HINT": "Следващо съвпадение",
  "BUTTON_PREV_HINT": "Предишно съвпадение",
  "BUTTON_CASESENSITIVE_HINT": "Съвпадение на малки/големи букви",
  "BUTTON_REGEXP_HINT": "Регулярен израз",
  "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Замяна без връщане",
  "REPLACE_WITHOUT_UNDO_WARNING": "Тъй като трябва да бъдат променени повече от {0} файла, {APP_NAME} ще промени и неотворените файлове направо в диска.<br />Няма да можете да отмените замените в тези файлове.",
  "BUTTON_REPLACE_WITHOUT_UNDO": "Замяна без връщане",
  "OPEN_FILE": "Отваряне на файл",
  "SAVE_FILE_AS": "Запазване на файл",
  "CHOOSE_FOLDER": "Изберете папка",
  "RELEASE_NOTES": "Бележки за изданието",
  "NO_UPDATE_TITLE": "Актулно издание!",
  "NO_UPDATE_MESSAGE": "Вие използвате най-новото издание на {APP_NAME}.",
  "FIND_REPLACE_TITLE_LABEL": "Замяна",
  "FIND_REPLACE_TITLE_WITH": "с",
  "FIND_TITLE_LABEL": "Открито:",
  "FIND_TITLE_SUMMARY": "&mdash; {0} {1} {2} в {3}",
  "FIND_NUM_FILES": "{0} {1}",
  "FIND_IN_FILES_SCOPED": "в <span class='dialog-filename'>{0}</span>",
  "FIND_IN_FILES_NO_SCOPE": "в проекта",
  "FIND_IN_FILES_ZERO_FILES": "Филтърът изключва всички файлове {0}",
  "FIND_IN_FILES_FILE": "файл",
  "FIND_IN_FILES_FILES": "файла",
  "FIND_IN_FILES_MATCH": "съвпадение",
  "FIND_IN_FILES_MATCHES": "съвпадения",
  "FIND_IN_FILES_MORE_THAN": "Над ",
  "FIND_IN_FILES_PAGING": "{0}&mdash;{1}",
  "FIND_IN_FILES_FILE_PATH": "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",
  "FIND_IN_FILES_EXPAND_COLLAPSE": "Ctrl/Cmd + щракване за показване/скриване на всички",
  "FIND_IN_FILES_INDEXING": "Обработване за мигновено търсене…",
  "FIND_IN_FILES_INDEXING_PROGRESS": "Индексиране на {0} от {1} файла за незабавно търсене…",
  "REPLACE_IN_FILES_ERRORS_TITLE": "Грешки при замяната",
  "REPLACE_IN_FILES_ERRORS": "Следните файлове не бяха променени, тъй като те самите са били променени след търсенето, или не могат да бъдат записани.",
  "ERROR_FETCHING_UPDATE_INFO_TITLE": "Грешка при получаване на информацията за обновлението",
  "ERROR_FETCHING_UPDATE_INFO_MSG": "Възникна грешка при получаването на информацията за най-новото обновление от сървъра. Моля, уверете се, че имате връзка с Интернет, и опитайте отново.",
  "NEW_FILE_FILTER": "Нов множество за изключване…",
  "CLEAR_FILE_FILTER": "Да не се изключват файлове",
  "NO_FILE_FILTER": "Няма изключени файлове",
  "EXCLUDE_FILE_FILTER": "Изключване на {0}",
  "EDIT_FILE_FILTER": "Редактиране…",
  "FILE_FILTER_DIALOG": "Редактиране на множество за изключване",
  "FILE_FILTER_INSTRUCTIONS": "Изключете файловете и папките, отговарящи на следните низове/поднизове или <a href='{0}' title='{0}'>маски</a>. Въвеждайте всеки низ на нов ред.",
  "FILTER_NAME_PLACEHOLDER": "Въведете име за това множество (незадължително)",
  "FILTER_NAME_REMAINING": "Остават {0} знака",
  "FILE_FILTER_CLIPPED_SUFFIX": "и още {0}",
  "FILTER_COUNTING_FILES": "Броене на файловете…",
  "FILTER_FILE_COUNT": "Позволени са {0} от {1} файл(а) {2}",
  "FILTER_FILE_COUNT_ALL": "Позволени са всички {0} файл(а) {1}",
  "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Няма приложимо бързо редактиране за текущото местоположение на курсора.",
  "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "Бързо редактиране на CSS: поставете курсора върху едно име на клас.",
  "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "Бързо редактиране на CSS: непълен атрибут на клас.",
  "ERROR_CSSQUICKEDIT_IDNOTFOUND": "Бързо редактиране на CSS: непълен атрибут на идентификатор.",
  "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "Бързо редактиране на CSS: поставете кърсора върху елемент, клас или идентификатор.",
  "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "Бързо редактиране на времева функция в CSS: грешен синтаксис.",
  "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "Бързо редактиране на JS: поставете курсора върху име на функция.",
  "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Няма бързи документи за текущото местоположение на курсора.",
  "PROJECT_LOADING": "Зареждане…",
  "UNTITLED": "Неозаглавен",
  "WORKING_FILES": "Работни файлове",
  "TOP": "Горе",
  "BOTTOM": "Долу",
  "LEFT": "Ляво",
  "RIGHT": "Дясно",
  "CMD_SPLITVIEW_NONE": "Без разделяне",
  "CMD_SPLITVIEW_VERTICAL": "Вертикално разделяне",
  "CMD_SPLITVIEW_HORIZONTAL": "Хоризонтално разделяне",
  "SPLITVIEW_MENU_TOOLTIP": "Вертикално или хоризонтално разделяне на редактора",
  "GEAR_MENU_TOOLTIP": "Настройки за работните файлове",
  "SPLITVIEW_INFO_TITLE": "Вече е отворен",
  "SPLITVIEW_MULTIPANE_WARNING": "Файлът вече е отворен в друг раздел. {APP_NAME} скоро ще поддържа отварянето на един и същ файл в повече от един раздел. Дотогава файлът ще бъде показван само в раздела, в който вече е отворен.<br /><br />(Това съобщение се появява само веднъж.)",
  "STATUSBAR_CURSOR_POSITION": "Ред {0}, колона {1}",
  "STATUSBAR_SELECTION_CH_SINGULAR": " — Избрана е {0} колона",
  "STATUSBAR_SELECTION_CH_PLURAL": " — Избрани са {0} колони",
  "STATUSBAR_SELECTION_LINE_SINGULAR": " — Избран е {0} ред",
  "STATUSBAR_SELECTION_LINE_PLURAL": " — Избрани са {0} реда",
  "STATUSBAR_SELECTION_MULTIPLE": " — {0} избора",
  "STATUSBAR_INDENT_TOOLTIP_SPACES": "Щракнете, за да превърнете отстъпите в интервали",
  "STATUSBAR_INDENT_TOOLTIP_TABS": "Щракнете, за да превърнете отстъпите в табулации",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Щракнете, за да промените броя интервали, използвани при отстъпите",
  "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Щракнете, за да промените ширината на табулатора в брой знаци",
  "STATUSBAR_SPACES": "Интервали:",
  "STATUSBAR_TAB_SIZE": "Табулация с размер:",
  "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} ред",
  "STATUSBAR_LINE_COUNT_PLURAL": "— {0} реда",
  "STATUSBAR_USER_EXTENSIONS_DISABLED": "Разширенията са изключени",
  "STATUSBAR_INSERT": "ВМК",
  "STATUSBAR_OVERWRITE": "ЗАМ",
  "STATUSBAR_INSOVR_TOOLTIP": "Щракнете, за да превключите поведените на курсора между вмъкване (ВМК) и заместване (ЗАМ)",
  "STATUSBAR_LANG_TOOLTIP": "Щракнете, за да промените типа на файла",
  "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Щракнете, за да превключите панела да доклади.",
  "STATUSBAR_DEFAULT_LANG": "(по подразбиране)",
  "STATUSBAR_SET_DEFAULT_LANG": "Задаване по подразбиране за файлове с разширение .{0}",
  "STATUSBAR_ENCODING_TOOLTIP": "Изберете кодирането",
  "ERRORS_PANEL_TITLE_MULTIPLE": "Проблеми от {0}",
  "SINGLE_ERROR": "1 проблем от {0} ",
  "MULTIPLE_ERRORS": "{1} проблема от {0}",
  "NO_ERRORS": "Не са открити проблеми от {0} — добра работа!",
  "NO_ERRORS_MULTIPLE_PROVIDER": "Не са открити проблеми — добра работа!",
  "LINT_DISABLED": "Проверката е изключена",
  "NO_LINT_AVAILABLE": "Няма налични системи за проверка на {0}",
  "NOTHING_TO_LINT": "Няма нищо за проверка",
  "LINTER_TIMED_OUT": "Времето на {0} изтече след като чака {1} милисекунди",
  "LINTER_FAILED": "{0} приключи с грешка: {1}",
  "FILE_MENU": "Файл",
  "CMD_FILE_NEW_UNTITLED": "Нов",
  "CMD_FILE_NEW": "Нов файл",
  "CMD_FILE_DUPLICATE": "Копие на реда",
  "CMD_FILE_DOWNLOAD_PROJECT": "Изтеглете проекта",
  "CMD_FILE_DOWNLOAD": "Изтегли",
  "CMD_FILE_CUT": "Отрязване",
  "CMD_FILE_COPY": "Копиране",
  "CMD_FILE_COPY_PATH": "Копиране на пътя",
  "CMD_FILE_PASTE": "Поставяне",
  "CMD_PROJECT_NEW": "Нов проект",
  "CMD_FILE_NEW_FOLDER": "Нова папка",
  "CMD_FILE_OPEN": "Отваряне…",
  "CMD_RECENT_FILES_OPEN": "Скорошни файлове...",
  "CMD_ADD_TO_WORKING_SET": "Отваряне в работните файлове",
  "CMD_OPEN_DROPPED_FILES": "Отваряне на пуснати файлове",
  "CMD_OPEN_FOLDER": "Отваряне на папка…",
  "CMD_FILE_CLOSE": "Затваряне",
  "CMD_FILE_CLOSE_ALL": "Затваряне на всички",
  "CMD_FILE_CLOSE_LIST": "Затваряне на списък",
  "CMD_FILE_CLOSE_OTHERS": "Затваряне на останалите",
  "CMD_FILE_CLOSE_ABOVE": "Затваряне на всички отгоре",
  "CMD_FILE_CLOSE_BELOW": "Затваряне на всички отдолу",
  "CMD_FILE_SAVE": "Запазване на файл",
  "CMD_FILE_SAVE_ALL": "Запазване на всички",
  "CMD_FILE_SAVE_AS": "Запазване като…",
  "CMD_LIVE_FILE_PREVIEW": "Преглед на живо",
  "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Включване на експерименталния преглед на живо",
  "CMD_RELOAD_LIVE_PREVIEW": "Презареждане на прегледа на живо насила",
  "CMD_PROJECT_SETTINGS": "Настройки на проекта…",
  "CMD_FILE_RENAME": "Преименуване",
  "CMD_FILE_DELETE": "Изтриване",
  "CMD_INSTALL_EXTENSION": "Инсталиране на разширение…",
  "CMD_EXTENSION_MANAGER": "Управител на разширения…",
  "CMD_FILE_REFRESH": "Опресняване на дървото от файлове",
  "CMD_FILE_SHOW_FOLDERS_FIRST": "Първо сортирайте папките",
  "CMD_QUIT": "Изход",
  "CMD_EXIT": "Изход",
  "EDIT_MENU": "Редактиране",
  "CMD_UNDO": "Отмяна",
  "CMD_REDO": "Повторение",
  "CMD_CUT": "Отрязване",
  "CMD_COPY": "Копиране",
  "CMD_PASTE": "Поставяне",
  "CMD_SELECT_ALL": "Избиране на всичко",
  "CMD_SELECT_LINE": "Избиране на ред",
  "CMD_SPLIT_SEL_INTO_LINES": "Разделяне на избраното на редове",
  "CMD_ADD_CUR_TO_NEXT_LINE": "Добавяне на курсор на следващия ред",
  "CMD_ADD_CUR_TO_PREV_LINE": "Добавяне на курсор на предишния ред",
  "CMD_INDENT": "Увеличаване на отстъпа",
  "CMD_UNINDENT": "Намаляване на отстъпа",
  "CMD_DUPLICATE": "Копие на реда",
  "CMD_DELETE_LINES": "Изтриване на реда",
  "CMD_COMMENT": "Превключване на коментар на реда",
  "CMD_BLOCK_COMMENT": "Превключване на коментар на блок",
  "CMD_LINE_UP": "Преместване на реда нагоре",
  "CMD_LINE_DOWN": "Преместване на реда надолу",
  "CMD_OPEN_LINE_ABOVE": "Нов ред отгоре",
  "CMD_OPEN_LINE_BELOW": "Нов ред отдолу",
  "CMD_TOGGLE_CLOSE_BRACKETS": "Автоматично затваряне на скобите",
  "CMD_SHOW_CODE_HINTS": "Показване на подсказки за кода",
  "CMD_BEAUTIFY_CODE": "Код за разкрасяване",
  "CMD_BEAUTIFY_CODE_ON_SAVE": "Разкрасете кода след запазване",
  "FIND_MENU": "Търсене",
  "CMD_FIND": "Търсене",
  "CMD_FIND_NEXT": "Търсене на следващото",
  "CMD_FIND_PREVIOUS": "Търсене на предишното",
  "CMD_FIND_ALL_AND_SELECT": "Търсене на всичко и избиране",
  "CMD_ADD_NEXT_MATCH": "Добавяне на следващото съвпадение към избора",
  "CMD_SKIP_CURRENT_MATCH": "Пропускане и добавяне на следващото съвпадение",
  "CMD_FIND_IN_FILES": "Търсене във файлове",
  "CMD_FIND_IN_SUBTREE": "Търсене в…",
  "CMD_REPLACE": "Замяна",
  "CMD_REPLACE_IN_FILES": "Замяна във файлове",
  "CMD_REPLACE_IN_SUBTREE": "Замяна в…",
  "VIEW_MENU": "Преглед",
  "CMD_HIDE_SIDEBAR": "Скриване на страничната лента",
  "CMD_SHOW_SIDEBAR": "Показване на страничната лента",
  "CMD_TOGGLE_SIDEBAR": "Превключване на страничната лента",
  "CMD_TOGGLE_PANELS": "Превключване на панелите",
  "CMD_TOGGLE_PURE_CODE": "Без разсейвания",
  "CMD_INCREASE_FONT_SIZE": "Увеличаване на размера на шрифта",
  "CMD_DECREASE_FONT_SIZE": "Намаляване на размера на шрифта",
  "CMD_RESTORE_FONT_SIZE": "Възстановяване на размера на шрифта",
  "CMD_SCROLL_LINE_UP": "Превъртане един ред нагоре",
  "CMD_SCROLL_LINE_DOWN": "Превъртане един ред надолу",
  "CMD_TOGGLE_LINE_NUMBERS": "Номера на редове",
  "CMD_TOGGLE_ACTIVE_LINE": "Осветяване на текущия ред",
  "CMD_TOGGLE_WORD_WRAP": "Пренасяне",
  "CMD_LIVE_HIGHLIGHT": "Осветяване на прегледа на живо",
  "CMD_VIEW_TOGGLE_INSPECTION": "Проверка на файловете при запазване",
  "CMD_WORKINGSET_SORT_BY_ADDED": "Подреждане по ред на добавяне",
  "CMD_WORKINGSET_SORT_BY_NAME": "Подреждане по име",
  "CMD_WORKINGSET_SORT_BY_TYPE": "Подреждане по тип",
  "CMD_WORKING_SORT_TOGGLE_AUTO": "Автоматично подреждане",
  "CMD_THEMES": "Теми…",
  "CMD_TOGGLE_SEARCH_AUTOHIDE": "Автоматично затваряне на търсенето",
  "NAVIGATE_MENU": "Придвижване",
  "CMD_QUICK_OPEN": "Бързо отваряне",
  "CMD_GOTO_LINE": "Отиване на ред",
  "CMD_GOTO_DEFINITION": "Бързо търсене на определение",
  "CMD_GOTO_DEFINITION_PROJECT": "Определение за бързо намиране в проекта",
  "CMD_GOTO_FIRST_PROBLEM": "Преминаване към първия проблем",
  "CMD_TOGGLE_QUICK_EDIT": "Бързо редактиране",
  "CMD_TOGGLE_QUICK_DOCS": "Бърза документация",
  "CMD_QUICK_EDIT_PREV_MATCH": "Предишно съвпадение",
  "CMD_QUICK_EDIT_NEXT_MATCH": "Следващо съвпадение",
  "CMD_CSS_QUICK_EDIT_NEW_RULE": "Ново правило",
  "CMD_NEXT_DOC": "Следващ документ",
  "CMD_PREV_DOC": "Предишен документ",
  "CMD_NAVIGATE_BACKWARD": "Навигиране назад",
  "CMD_NAVIGATE_FORWARD": "Навигирайте напред",
  "CMD_NEXT_DOC_LIST_ORDER": "Следващ документ в списъка",
  "CMD_PREV_DOC_LIST_ORDER": "Предишен документ в списъка",
  "CMD_SHOW_IN_TREE": "Показване в дървото на файловете",
  "CMD_SHOW_IN_EXPLORER": "Показване в Explorer",
  "CMD_SHOW_IN_FINDER": "Показване във Finder",
  "CMD_SHOW_IN_OS": "Показване в ОС",
  "CMD_SWITCH_PANE_FOCUS": "Превключване на фокуса на екрана",
  "CMD_OPEN_VFS": "Отворете виртуална файлова система",
  "CMD_OPEN_VIRTUAL_SERVER": "Отворете виртуалния сървър",
  "HELP_MENU": "Помощ",
  "CMD_CHECK_FOR_UPDATE": "Проверка за обновления",
  "CMD_HOW_TO_USE_BRACKETS": "Как се използва {APP_NAME}",
  "CMD_SUPPORT": "Поддръжка на {APP_NAME}",
  "CMD_SUGGEST": "Предложете функционалност",
  "CMD_RELEASE_NOTES": "Бележки за изданието",
  "CMD_GET_INVOLVED": "Включете се",
  "CMD_SHOW_EXTENSIONS_FOLDER": "Показване на папката с разширенията",
  "CMD_HEALTH_DATA_STATISTICS": "Здравен доклад",
  "CMD_HOMEPAGE": "Начална страница на {APP_NAME}",
  "CMD_TWITTER": "{TWITTER_NAME} в Тиутър",
  "CMD_ABOUT": "Относно {APP_TITLE}",
  "CMD_OPEN_PREFERENCES": "Отваряне на файла с настройките",
  "CMD_OPEN_KEYMAP": "Отваряне на файла с потребителските клавишни настройки",
  "EXPERIMENTAL_BUILD": "експериментална компилация",
  "RELEASE_BUILD": "компилация",
  "DEVELOPMENT_BUILD": "компилация за разработчици",
  "PRERELEASE_BUILD": "предварителна версия",
  "RELOAD_FROM_DISK": "Презареждане от диска",
  "KEEP_CHANGES_IN_EDITOR": "Използване на промените в редактора",
  "CLOSE_DONT_SAVE": "Затваряне (без запазване)",
  "RELAUNCH_CHROME": "Повторно пускане на Chrome",
  "ABOUT": "Относно",
  "CLOSE": "Затваряне",
  "ABOUT_TEXT_LINE1": "Версия {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
  "ABOUT_TEXT_BUILD_TIMESTAMP": "време на изграждане:",
  "ABOUT_TEXT_LINE3": "Библиотеки на трети страни, които използваме - <a href='https://github.com/phcode-dev/phoenix/tree/main/src/thirdparty/licences'>Лицензи и приписвания</a> .",
  "ABOUT_TEXT_LINE4": "Документация и източник на <a href='https://github.com/phcode-dev/phoenix/'>адрес https://github.com/phcode-dev/phoenix/</a>",
  "ABOUT_TEXT_LINE5": "Направено с ❤ и JavaScript от:",
  "ABOUT_TEXT_LINE6": "Много хора (но в момента имаме проблеми със зареждането на тези данни).",
  "ABOUT_TEXT_MDN_DOCS": "Документацията и логото на MDN са лицензирани под лиценз за признание от вида „Криейтив Комънс“: <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Нелокализиран</a>.",
  "UPDATE_NOTIFICATION_TOOLTIP": "Има ново издание на {APP_NAME}! Щракнете тук за подробности.",
  "UPDATE_AVAILABLE_TITLE": "Има ново обновление",
  "UPDATE_RELOAD_APP": "Моля, затворете всички прозорци/раздели на {APP_NAME} и отворете отново {APP_NAME}, за да получите най-новата версия.",
  "UPDATE_MESSAGE": "Хей, има ново издание на {APP_NAME}. Ето някои от новите функционалности:",
  "GET_IT_NOW": "Вземете го сега!",
  "PROJECT_SETTINGS_TITLE": "Настройки на проекта за: {0}",
  "PROJECT_SETTING_BASE_URL": "Базов адрес за преглед на живо",
  "PROJECT_SETTING_BASE_URL_HINT": "За да използвате местен сървър, въведете адрес като: http://localhost:8000/",
  "BASEURL_ERROR_INVALID_PROTOCOL": "Протоколът {0} не се поддържа от прегледа на живо &mdash; моля, използвайте „http:“ или „https:“.",
  "BASEURL_ERROR_SEARCH_DISALLOWED": "Базовият адрес не може да съдържа параметри за търсене като „{0}“.",
  "BASEURL_ERROR_HASH_DISALLOWED": "Базовият адрес не може да съдържа диези като „{0}“.",
  "BASEURL_ERROR_INVALID_CHAR": "Специалните знаци като „{0}“ трябва да бъдат кодирани с „%“.",
  "BASEURL_ERROR_UNKNOWN_ERROR": "Възникна неизвестна грешка при обработката на базовия адрес.",
  "EMPTY_VIEW_HEADER": "<em>Отворете файл, докато този раздел е на фокус</em>",
  "FLIPVIEW_BTN_TOOLTIP": "Прехвърляне на този изглед към раздела „{0}“.",
  "CURRENT_THEME": "Текуща тема",
  "USE_THEME_SCROLLBARS": "Използване на лентите за превъртане от темата",
  "FONT_SIZE": "Размер на шрифта",
  "FONT_FAMILY": "Семейство на шрифта",
  "THEMES_SETTINGS": "Настройки на темите",
  "THEMES_ERROR": "Теми Грешка",
  "THEMES_ERROR_CANNOT_APPLY": "Темата не можа да се приложи поради грешка.",
  "BUTTON_NEW_RULE": "Ново правило",
  "INSTALL": "Инсталиране",
  "APPLY": "Приложи",
  "UPDATE": "Обновяване",
  "REMOVE": "Премахване",
  "DISABLE": "Изключване",
  "ENABLE": "Включване",
  "OVERWRITE": "Презаписване",
  "CANT_DROP_ZIP": "Пускането на zip файлове скоро ще се поддържа...",
  "CANT_REMOVE_DEV": "Разширенията в папката „dev“ трябва да бъдат изтрити ръчно.",
  "CANT_UPDATE": "Обновлението не е съвместимо с това издание на {APP_NAME}.",
  "CANT_UPDATE_DEV": "Разширенията в папката „dev“ не могат да бъдат обновени автоматично.",
  "INSTALL_EXTENSION_TITLE": "Инсталиране на разширение",
  "UPDATE_EXTENSION_TITLE": "Обновяване на разширението",
  "INSTALL_EXTENSION_LABEL": "Адрес на разширението",
  "INSTALL_EXTENSION_HINT": "Адресът на архивния файл на разширението или хранилището му в GitHub",
  "INSTALLING_FROM": "Инсталиране на разширение от {0}…",
  "INSTALL_SUCCEEDED": "Инсталирането беше успешно!",
  "INSTALL_FAILED": "Инсталирането се провали.",
  "CANCELING_INSTALL": "Отказване…",
  "CANCELING_HUNG": "Отказването на инсталирането отнема много време. Може да е възникнала вътрешна грешка.",
  "INSTALL_CANCELED": "Инсталирането беше отказано.",
  "VIEW_COMPLETE_DESCRIPTION": "Преглед на пълното описание",
  "VIEW_TRUNCATED_DESCRIPTION": "Преглед на съкратеното описание",
  "SORT_EXTENSION_METHOD": "Сортирайте разширенията, като използвате downloadCount или publishedDate",
  "INVALID_ZIP_FILE": "Сваленото съдържание не е правилен архивен файл във формата „zip“.",
  "MISSING_PACKAGE_JSON": "Пакетът няма файл package.json.",
  "INVALID_PACKAGE_JSON": "Файлът „package.json“ не е правилно форматиран (грешката е: {0}).",
  "MISSING_PACKAGE_NAME": "Файлът „package.json“ не указва името на пакета.",
  "BAD_PACKAGE_NAME": "{0} не е правилно име на пакет.",
  "MISSING_PACKAGE_VERSION": "Файлът „package.json“ не указва версията на пакета.",
  "INVALID_VERSION_NUMBER": "Версията на пакета ({0}) е грешна.",
  "INVALID_BRACKETS_VERSION": "Низът за съвместимост ({0}) с {APP_NAME} е грешен.",
  "DISALLOWED_WORDS": "Думите ({1}) не са позволени в полето {0}.",
  "NPM_INSTALL_FAILED": "Неуспешна команда за инсталиране на npm: {0}",
  "API_NOT_COMPATIBLE": "Разширението не е съвместимо с това издание на {APP_NAME}. То е инсталирано във Вашата папка с изключени разширения.",
  "MISSING_MAIN": "В пакета няма файл „main.js“.",
  "EXTENSION_ALREADY_INSTALLED": "Инсталирането на този пакет ще презапише друго, вече инсталирано разширение. Искате ли да презапишете старото разширение?",
  "EXTENSION_SAME_VERSION": "Този пакет има същата версия като вече инсталирания. Искате ли да презапишете текущата инсталация?",
  "EXTENSION_OLDER_VERSION": "Този пакет има версия {0}, която е по-стара от текущо инсталираната ({1}). Искате ли да презапишете текущата инсталация?",
  "DOWNLOAD_ID_IN_USE": "Вътрешна грешка: идентификатора на свалянето вече е зает.",
  "NO_SERVER_RESPONSE": "Неуспешна връзка със сървъра.",
  "BAD_HTTP_STATUS": "Файлът не е открит на сървъра (HTTP {0}).",
  "CANNOT_WRITE_TEMP": "Неуспешно запазване на свалянето като временен файл.",
  "ERROR_LOADING": "Това разширение имаше грешка при стартирането си.",
  "MALFORMED_URL": "Адресът е грешен. Моля, проверете дали сте го въвели правилно.",
  "UNSUPPORTED_PROTOCOL": "Адресът трябва да бъде от вида „http“ или „https“.",
  "UNKNOWN_ERROR": "Неизвестна вътрешна грешка.",
  "EXTENSION_VERIFIED_PUBLISHER": "Този издател е потвърдил собствеността върху {0}",
  "EXTENSION_VERIFIED_SORT": "Проверен",
  "EXTENSION_STAR": "звезда",
  "EXTENSION_STAR_SORT": "Рейтинг със звезди",
  "EXTENSION_MANAGER_TITLE": "Управител на разширенията",
  "EXTENSION_MANAGER_ERROR_LOAD": "Неуспешен достъп до регистъра на разширенията. Моля, опитайте отново по-късно.",
  "INSTALL_EXTENSION_DRAG": "Завлачете .zip тук или",
  "INSTALL_EXTEN